#! /bin/bash

# BananaPi temp
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`
bpi=$(sqlite3 -header $dir/dbf/nettemp.db  "SELECT id FROM sensors WHERE rom='Banana_Pi'")
if [ -n "$bpi" ]
    then
    val=$(cat /sys/devices/platform/sunxi-i2c.0/i2c-0/0-0034/temp1_input| awk '{ getline;  printf "%1.2f\n", $1/1000}' )
    skey=$(sqlite3 $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")
    php-cgi -f $dir/receiver.php key=$skey rom=Banana_Pi value=$val type=temp
fi
