#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

#Banana Pi system temp

if [ -f /boot/bananapi/script.bin ] && [ -f /sys/devices/platform/sunxi-i2c.0/i2c-0/0-0034/temp1_input  ] && [ ! $(cat $dir/tmp/onewire |grep Banana_Pi) ] 
    then
    echo "Banana_Pi" >> $dir/tmp/onewire
    echo "Banana Pi: Internal sensor found"
fi
