#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

#Raspberry system temp
rpi=$(cat /proc/cmdline | awk -v RS=" " -F= '/boardrev/ { print $2 }')
if [ ! $(cat $dir/tmp/onewire |grep Raspberry_Pi) ] && [ -e /opt/vc/bin/vcgencmd ] && [ -n "$rpi" ]; then
    echo "Raspberry_Pi" >> $dir/tmp/onewire
    echo "Raspberry Pi: Internal sensor found"
fi

