#! /bin/bash 

# RaspberryPi temp
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`
rpi=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db  "SELECT id FROM sensors WHERE rom='Raspberry_Pi'")
if [ -n "$rpi" ]; then
        val=$(/opt/vc/bin/vcgencmd measure_temp | cut -c 6-9)
	skey=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")
	php-cgi -f $dir/receiver.php key=$skey rom=Raspberry_Pi value=$val type=temp

	echo Raspberry Pi: $val C
fi
unset wynik
