#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

dev=ttyUSB0

skey=$(sqlite3 $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")

val=$(/usr/local/bin/sdm120c /dev/$dev -p |awk '{print $2}' |sed 's/-//g')
php-cgi -f $dir/receiver.php key=$skey usb=$dev device=usb value=$val type=watt current=$val

val=$(/usr/local/bin/sdm120c /dev/$dev -v |awk '{print $2}' |sed 's/-//g')
php-cgi -f $dir/receiver.php key=$skey usb=$dev device=usb value=$val type=volt current=$val

val=$(/usr/local/bin/sdm120c /dev/$dev -c |awk '{print $2}' |sed 's/-//g')
php-cgi -f $dir/receiver.php key=$skey usb=$dev device=usb value=$val type=amps current=$val





