#! /bin/bash 

# RaspberryPi temp
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

#!/bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

dev=ttyAMA0
PORT=/dev/$dev


va=($(echo "S" > $PORT && read RESPONSE < $PORT && echo $RESPONSE))


  if [ -n "$va" ]; then

     skey=$(sqlite3 $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")

       php-cgi -f $dir/receiver.php key=$skey rom=usb_$dev\_volt value=${va[0]} type=volt
       php-cgi -f $dir/receiver.php key=$skey rom=usb_$dev\_amps value=${va[1]} type=amps

       echo V: ${va[0]}
       echo A: ${va[1]}

  fi
