#! /bin/bash 

# RaspberryPi temp
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

da=$(( ( RANDOM % 10 )  + 1 ))
dv=$(( ( RANDOM % 10 )  + 1 ))
#va=($(cat /dev/ttyACM0))
va=($dv $da)
if [ -n "$va" ]; then
    skey=$(sqlite3 $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")
    
    php-cgi -f $dir/receiver.php key=$skey rom=ups_usb_volt value=${va[0]} type=volt
    php-cgi -f $dir/receiver.php key=$skey rom=ups_usb_amper value=${va[1]} type=amper
    
    echo V: ${va[0]}
    echo A: ${va[1]}
fi

