#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M%S`
action="$1"
file="$2"
mkdir -p $dir/tmp/backup > /dev/null

if [ -n "$1" ] || [ -n "$2" ]
    then

if [ $action = "b" ]
    then
	git log |head -1 |awk '{print $2}' > $dir/tmp/backup/commit
	cd $dir/modules/tools/backup/files
	tar -rpvf nettemp-$date.tar.gz -C $dir/db/ .
        tar -rpvf nettemp-$date.tar.gz -C $dir/dbf/ .  
	chmod 775 nettemp-$date.tar.gz
	rm -rf $dir/tmp/backup/*
fi
if [ $action = "r" ] && [ -n "$file" ]
    then
	tar -xpvf $file -C $dir/tmp/backup
	rm -rf $dir/db/*
	rm -rf $dir/dbf/*
	mv -f $dir/tmp/backup/*.sql $dir/db/
	mv -f $dir/tmp/backup/*.db $dir/dbf/
	chmod 775 $dir/dbf/nettemp.db
	git reset --hard $(cat $dir/tmp/backup/commit)
	rm -rf $dir/tmp/backup/* 
fi
else
    echo "no option: b or r"
fi
