#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
/etc/init.d/apcupsd stop
killall apcupsd
apt-get purge -y apcupsd
apt-get install -y apcupsd
sed -i 's|UPSCABLE smart|UPSCABLE usb|g' /etc/apcupsd/apcupsd.conf
sed -i 's|UPSTYPE apcsmart|UPSTYPE usb|g' /etc/apcupsd/apcupsd.conf
sed -i 's|DEVICE /dev/ttyS0|DEVICE|g' /etc/apcupsd/apcupsd.conf
sed -i 's|ISCONFIGURED=no|ISCONFIGURED=yes|g' /etc/default/apcupsd
/etc/init.d/apcupsd start
sed -i '/exit 0/i /bin/bash $dir/modules/ups/onbattery on' /etc/apcupsd/onbattery 
sed -i '/exit 0/i /bin/bash $dir/modules/ups/onbattery off' /etc/apcupsd/offbattery 
update-rc.d apcupsd enable
chown -R root.www-data $dir/modules/ups
chmod -R 775 $dir/modules/ups

