#! /bin/bash


#/etc/init.d/apcupsd stop
#killall apcupsd
#apt-get purge -y apcupsd

apt-get install -y apcupsd
sed -i 's|UPSCABLE smart|UPSCABLE usb|g' /etc/apcupsd/apcupsd.conf
sed -i 's|UPSTYPE apcsmart|UPSTYPE usb|g' /etc/apcupsd/apcupsd.conf
sed -i 's|DEVICE /dev/ttyS0|DEVICE|g' /etc/apcupsd/apcupsd.conf
sed -i 's|ISCONFIGURED=no|ISCONFIGURED=yes|g' /etc/default/apcupsd
/etc/init.d/apcupsd start

echo "/var/www/nettemp/modules/ups/onbattery on" >> /etc/apcupsd/onbattery 
echo "/var/www/nettemp/modules/ups/onbattery off" >> /etc/apcupsd/onbattery 