#! /bin/bash

dir=$(cd "$( dirname "$0" )" && cat ../../conf.php |grep global | awk -F"'" '{ print $2 }')

mkdir -p $dir/tmp/kwh 1> /dev/null
gpio=$(sqlite3 $dir/dbf/nettemp.db  "SELECT gpio FROM gpio WHERE gpio_kwh='on'")

if [ -n "$gpio" ]; then
divider=$(sqlite3 $dir/dbf/nettemp.db  "SELECT gpio_kwh_divider FROM gpio WHERE gpio='$gpio'")
if [ -z "$divider" ]; then 
divider="1"
fi

# org
#i=$(cat $dir/tmp/kwh/kwh_count_$(date +%y%m%d) 2> /dev/null )
#echo "$[($(date +%s)+7200)*1000],$[$i/$divider]" > $dir/tmp/kwh/kwh_daily_$(date +%y%m%d)
#cat $dir/tmp/kwh/kwh_daily* > $dir/db/kwh.all
#echo $(echo '[' ; cat $dir/db/kwh.all |sed -e 's/^/[/'|sed -e 's/,$/,/'|sed -e 's/\([^,]\)$/\1\],/' |sed '$s/,$//' ; echo  ']') > $dir/db/data.json 


# new
i=$(cat $dir/tmp/kwh/kwh_count_$(date +%y%m%d) 2> /dev/null )
echo "$[($(date +%s)+7200)*1000],$[$i]" > $dir/tmp/kwh/kwh_daily_$(date +%y%m%d)
cat $dir/tmp/kwh/kwh_daily* > $dir/db/gpio_kwh.db
echo $(echo '[' ; cat $dir/db/gpio_kwh.db | awk -F "," '{print $1","$2 / '$divider' }' |sed -e 's/^/[/'|sed -e 's/,$/,/'|sed -e 's/\([^,]\)$/\1\],/' |sed '$s/,$//' ; echo  ']') > $dir/db/gpio_kwh_highcharts.json 
#

else 
    echo "kWh OFF"
fi
