#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

if pidof -o %PPID -x $(basename $0) > /dev/null; then
echo runnning
echo "run" >> $dir/log.txt
exit
fi



mkdir -p $dir/tmp/kwh 1> /dev/null
gpio=$(sqlite3 $dir/dbf/nettemp.db  "SELECT gpio FROM gpio WHERE mode='kwh'")

if [ -n "$gpio" ]; then
divider=$(sqlite3 $dir/dbf/nettemp.db  "SELECT kwh_divider FROM gpio WHERE gpio='$gpio'")
if [ -z "$divider" ]; then 
divider="1"
fi

if base=$(sqlite3 $dir/dbf/kwh.db "select strftime('%s', time),pulse FROM kwh;") ;
    then
	middle=$(printf "$base %s\n" | awk -F "|" '{printf "["}{ printf "%3.0f",($1)*1000}{printf ","}{printf "%3.3f", $2/'$divider'}{print "]," }')
	echo -e "[ ${middle%?} ]" > $dir/tmp/kwh/gpio_kwh_min.json
    else 
	echo "cannot read base"
fi
else 
    echo "kWh OFF"
fi
