#! /bin/bash -x

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

mkdir -p $dir/tmp/kwh 1> /dev/null
gpio=$(sqlite3 $dir/dbf/nettemp.db  "SELECT gpio FROM gpio WHERE mode='kwh'")

if [ -n "$gpio" ]; then
divider=$(sqlite3 $dir/dbf/nettemp.db  "SELECT kwh_divider FROM gpio WHERE gpio='$gpio'")
if [ -z "$divider" ]; then 
divider="1"
fi

middle=$(sqlite3 /var/www/nettemp/dbf/kwh.db  "SELECT * FROM kwh" | awk -F "|" '{print "["}{ printf "%3.0f",($1+3600)*1000}{print ","$3 / '$divider' "]," }')
echo -e "[ ${middle%?} ]" > $dir/tmp/kwh/gpio_kwh_min.json

else 
    echo "kWh OFF"
fi
