#! /bin/bash

dir=$(cd "$( dirname "$0" )" && cat ../../conf.php |grep global | awk -F"'" '{ print $2 }')

sqlite3 $dir/dbf/nettemp.db  "ALTER TABLE gpio ADD gpio_kwh type TEXT";
sqlite3 $dir/dbf/nettemp.db  "ALTER TABLE gpio ADD gpio_kwh_divider type TEXT";
sqlite3 $dir/dbf/nettemp.db  "ALTER TABLE gpio ADD gpio_kwh_hilo type TEXT";

apt-get -y install bc

sed -i '$a @reboot '$dir'/modules/kwh/reset' /var/spool/cron/crontabs/root
sed -i '$a */1 * * * * '$dir'/modules/kwh/highcharts' /var/spool/cron/crontabs/root

sed -i '$a www-data ALL=(ALL) NOPASSWD: /usr/bin/whoami, /usr/bin/killall *, /usr/bin/nohup *' /etc/sudoers

chown -R root.www-data $dir/modules/kwh
chmod -R 775 $dir/modules/kwh
