#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

gpio=$(sqlite3 $dir/dbf/nettemp.db  "SELECT gpio FROM gpio WHERE mode='kwh'")
divider=$(sqlite3 $dir/dbf/nettemp.db  "SELECT kwh_divider FROM gpio WHERE $gpio")

kwh=$(cat $dir/db/gpio_kwh.db  | awk -F "," '{ sum+=$2 / '$divider' } END {print sum }')
echo "All consumption: $kwh kWh"
#wh=$(cat $dir/tmp/kwh/wh)
#echo "Current consumption: $wh Wh "
