#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

gpio=$(sqlite3 $dir/dbf/nettemp.db  "SELECT gpio FROM gpio WHERE mode='kwh'")
divider0=$(sqlite3 $dir/dbf/nettemp.db  "SELECT kwh_divider FROM gpio WHERE $gpio")
divider=$( echo $divider0/1 |bc -l )

kwh_month=$(sqlite3 $dir/dbf/kwh.db "select round((sum(pulse)/$divider),3) from kwh where time >= date('now','start of month')")
kwh_day=$(sqlite3 $dir/dbf/kwh.db "select round((sum(pulse)/$divider),3) from kwh where time >= date('now','start of day')")
kwh_current=$(sqlite3 $dir/dbf/kwh.db "select pulse*60 from kwh where time = (select max(time) from kwh)")
echo " Current   : $kwh_current Watt"
echo " Today kWh : $kwh_day kWh"
echo " Month kWh : $kwh_month kWh"