#! /bin/bash  

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )



if [ ! -s $dir/dbf/kwh.db ]
    then
	sudo echo "" > $dir/dbf/kwh.db
	sudo chmod 775 $dir/dbf/kwh.db
	sudo chown root.www-data $dir/dbf/kwh.db
	sqlite3 $dir/dbf/kwh.db "PRAGMA journal_mode=WAL;"
	sqlite3 $dir/dbf/kwh.db  "CREATE TABLE kwh ( time DATE DEFAULT (datetime('now','localtime')), pulse INTEEGER );"
    else 
	echo kwh.db exist
fi
