#! /bin/bash 

dir=$(cd "$( dirname "$0" )" && cat ../../conf.php |grep global | awk -F"'" '{ print $2 }')


pid=$(pgrep nettemp_kwh)
sudo killall nettemp_kwh
sudo nohup $dir/modules/kwh/nettemp_kwh  > /dev/null & echo $!
exit 

