#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../ && pwd )
date=`date +%y%m%d-%H%M`

dev=ttyACM0
dev2=ttyUSB0
ip=172.18.10.101
i2c=500
gpio=1

skey=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")


for i in temp humid relay lux press volt amps watt trigger gas water elec
	 do
		val=$(( ( RANDOM % 10 )  + 1 ))
		php-cgi -f $dir/receiver.php key=$skey type=$i value=$val device=wireless ip=$ip  current=$val
		val=$(( ( RANDOM % 10 )  + 1 ))
		php-cgi -f $dir/receiver.php key=$skey type=$i value=$val device=gpio gpio=$gpio  current=$val
		val=$(( ( RANDOM % 10 )  + 1 ))
		php-cgi -f $dir/receiver.php key=$skey type=$i value=$val device=i2c i2c=$i2c  current=$val
		val=$(( ( RANDOM % 10 )  + 1 ))
		php-cgi -f $dir/receiver.php key=$skey type=$i value=$val device=usb usb=$dev2  current=$val
	done



#sqlite3 dbf/nettemp.db "DELETE FROM newdev"
#sqlite3 dbf/nettemp.db "DELETE  FROM sensors"