#! /bin/bash


#fstab
sed -i 's/defaults,noatime/defaults,noatime,nodiratime/g' /etc/fstab

#ipv6
echo "net.ipv6.conf.all.disable_ipv6=1" > /etc/sysctl.d/disableipv6.conf
echo 'blacklist ipv6' >> /etc/modprobe.d/blacklist
sed -i '/::/s%^%#%g' /etc/hosts

#safe overclock
echo -e "arm_freq=850\nsdram_freq=450\ncore_freq=350\nforce_turbo=1" >> /boot/config.txt

#io
sed -i 's/deadline/noop/g' /boot/cmdline.txt

#swap
echo "CONF_SWAPSIZE=512" > /etc/dphys-swapfile
dphys-swapfile setup
dphys-swapfile swapon
echo 'vm.vfs_cache_pressure=50' >> /etc/sysctl.conf
