#! /bin/bash

#sqlite3 dbx.sql "CREATE TABLE def (time DATE DEFAULT (datetime('now','localtime')), value INTEEGER)"


db=$(ls /var/www/nettemp/db)
for i in $db
  do
    sqlite3 /var/www/nettemp/db/$i "CREATE INDEX time_index ON def(time);"
done