#! /bin/bash 

#sqlite3 dbx.sql "CREATE TABLE def (time DATE DEFAULT (datetime('now','localtime')), value INTEGER)"


for i in {0..50000}
  do
    echo $i
    sqlite3 dbx.sql "INSERT OR IGNORE INTO def (value) VALUES ('$(( ( RANDOM % 100 ) ))')"
done