#! /bin/bash 


dir=../..


# my settings

sqlite3 $dir/dbf/nettemp.db "UPDATE mail_settings SET host='smtp.gmail.com' WHERE id='1'"
sqlite3 $dir/dbf/nettemp.db "UPDATE mail_settings SET port='587' WHERE id='1'"
sqlite3 $dir/dbf/nettemp.db "UPDATE mail_settings SET user='nettempnotifications@gmail.com' WHERE id='1'"

sqlite3 $dir/dbf/nettemp.db "INSERT INTO sensors (name, rom, tmp, tmp_min, tmp_max, alarm, hour, day, week, month, year, logoterma ) VALUES('Taras','0x280x880x9D0xF70x020x000x000xB6','0','-10','30.0','on','on','on','on','on','on','on')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO sensors (name, rom, tmp, tmp_min, tmp_max, alarm, hour, day, week, month, year, logoterma ) VALUES('Korytarz','0x280xF80x790xF70x020x000x000xEB','0','20','25','on','on','on','on','on','on','on')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO sensors (name, rom, tmp, tmp_min, tmp_max, alarm, hour, day, week, month, year, logoterma ) VALUES('Sypialnia','0x280x040x5E0x250x030x000x000xE0','0','20.0','23.0','on','on','on','on','on','on','on')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO sensors (name, rom, tmp, tmp_min, tmp_max, alarm, hour, day, week, month, year, logoterma ) VALUES('Kuchnia','0x280x6C0x580x250x030x000x000x1E','0','20.0','25.0','on','on','on','on','on','on','on')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO sensors (name, rom, tmp, tmp_min, tmp_max, alarm, hour, day, week, month, year, logoterma ) VALUES('Maly pokoj','0x280xDE0x6E0x250x030x000x000x6F','0','20.0','23.0','on','on','on','on','on','on','on')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO sensors (name, rom, tmp, tmp_min, tmp_max, alarm, hour, day, week, month, year, logoterma ) VALUES('Salon','0x280x890x360x250x030x000x000x6F','0','20.0','23.0','on','on','on','on','on','on','on')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO sensors (name, rom, tmp, tmp_min, tmp_max, alarm, hour, day, week, month, year, logoterma ) VALUES('Szafka komp','0x280xCD0xFB0xFA0x010x000x000xDC','0','0','33.0','on','on','on','on','on','on','on')"

rom=`sqlite3 $dir/dbf/nettemp.db "SELECT rom from sensors"`

for ss in $rom
do
/usr/bin/rrdtool create $dir/db/$ss.rrd -s 600 DS:temp:GAUGE:700:-50:50 RRA:AVERAGE:0.5:1:48384 RRA:MAX:0.5:1:48384 RRA:MIN:0.5:1:48384 RRA:LAST:0.5:1:48384
chmod 777 $dir/db/$ss.rrd
done
# end my settings