#! /bin/bash  
#dir=../..
dir=/var/www/nettemp

date=`date +%y%m%d-%H%M`

rm -rf $dir/dbf/nettemp.db
rm -rf $dir/db/*.rrd
rm -rf $dir/img/view1/*.png                                           
rm -rf $dir/img/instant/*.png                                         
rm -rf $dir/tmp/log.txt
rm -rf $dir/tmp/.digitemprc
rm -rf $dir/tmp/onewire
rm -rf $dir/tmp/gammu*

sqlite3 $dir/dbf/nettemp.db  "CREATE TABLE sensors (
  id INTEGER PRIMARY KEY,
  name UNIQUE,
  rom UNIQUE,
  tmp REAL,
  tmp_min REAL,
  tmp_max REAL,
  alarm TEXT,
  hour TEXT,
  day TEXT,
  week TEXT,
  month TEXT,
  year TEXT,
  color TEXT,
  type TEXT,
  gpio TEXT
  );"
 
sqlite3 $dir/dbf/nettemp.db "CREATE TABLE recipient (
  id INTEGER PRIMARY KEY,
  name TEXT,
  mail TEXT,
  tel NUMERIC,
  mail_alarm TEXT,
  sms_alarm TEXT
  );"
 
sqlite3 $dir/dbf/nettemp.db "CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  login UNIQUE, 
  password TEXT, 
  perms TEXT
  );"

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE mail_settings (
  id INTEGER PRIMARY KEY,
  host TEXT,
  port TEXT,
  user TEXT,
  password TEXT,
  address TEXT,
  test_mail TEXT
  );" 

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE sms_settings (
  id INTEGER PRIMARY KEY,
  name TEXT,
  dev TEXT,
  sms_test TEXT,
  smsc TEXT,
  default_dev TEXT
  );" 

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE device (
   id INTEGER PRIMARY KEY,
   usb UNIQUE,
   onewire UNIQUE,
   serial UNIQUE
  );" 

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE gpio (
  id INTEGER PRIMARY KEY,
  gpio UNIQUE,
  name TEXT,
  time_checkbox TEXT,
  time_run TEXT,
  time_offset TEXT,
  time_start TEXT,
  temp_checkbox TEXT,
  temp_run TEXT,
  temp_sensor TEXT,
  temp_onoff TEXT,
  temp_temp REAL,
  gpio_rev_hilo TEXT,
  gpio_mode TEXT,
  humi_checkbox TEXT,
  humi_type TEXT,
  day_checkbox TEXT,
  day_zone1s TEXT,
  day_zone1e TEXT,
  tempday_checkbox TEXT,
  simple_run TEXT
    );"


sqlite3 $dir/dbf/nettemp.db "CREATE TABLE settings (
   id INTEGER PRIMARY KEY,
   mail TEXT,
   sms TEXT,
   highcharts TEXT,
   rrd TEXT
  );"


sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO users (login, password, perms ) VALUES ('admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', 'adm')"
#sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO users (login, password, perms ) VALUES ('temp', 'd969831eb8a99cff8c02e681f43289e5d3d69664', 'ops')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO device (usb, onewire, serial) VALUES ('off','off','off')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO settings (mail, sms, rrd, highcharts) VALUES ('off','off', 'on', 'on')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO mail_settings (host, port, user ) VALUES ('smtp.gmail.com', '587', 'yourmail@gmail.com' )"



chmod 777 $dir/dbf/nettemp.db
echo "$date Default settings restored" >> $dir/tmp/log.txt
chmod 777 $dir/tmp/log.txt
