#! /bin/bash  

dir=$(cd "$( dirname "$0" )" && cat ../../conf.php |grep global | awk -F"'" '{ print $2 }')
date=`date +%y%m%d-%H%M`
git reset --hard

rm -rf $dir/dbf/nettemp.db
#rm -rf $dir/db/*.rrd #uncomment will delete all stored data
rm -rf $dir/tmp/log.txt
rm -rf $dir/tmp/.digitemprc
rm -rf $dir/tmp/onewire
rm -rf $dir/tmp/gammu*

sqlite3 $dir/dbf/nettemp.db  "CREATE TABLE sensors (
  id INTEGER PRIMARY KEY,
  name UNIQUE,
  rom UNIQUE,
  tmp REAL,
  tmp_min REAL,
  tmp_max REAL,
  alarm TEXT,
  hour TEXT,
  day TEXT,
  week TEXT,
  month TEXT,
  year TEXT,
  color TEXT,
  type TEXT,
  gpio TEXT
  );"
 
sqlite3 $dir/dbf/nettemp.db "CREATE TABLE recipient (
  id INTEGER PRIMARY KEY,
  name TEXT,
  mail TEXT,
  tel NUMERIC,
  mail_alarm TEXT,
  sms_alarm TEXT
  );"
 
sqlite3 $dir/dbf/nettemp.db "CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  login UNIQUE, 
  password TEXT, 
  perms TEXT
  );"

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE mail_settings (
  id INTEGER PRIMARY KEY,
  host TEXT,
  port TEXT,
  user TEXT,
  password TEXT,
  address TEXT,
  test_mail TEXT
  );" 

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE sms_settings (
  id INTEGER PRIMARY KEY,
  name TEXT,
  dev TEXT,
  sms_test TEXT,
  smsc TEXT,
  default_dev TEXT
  );" 

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE device (
   id INTEGER PRIMARY KEY,
   usb UNIQUE,
   onewire UNIQUE,
   serial UNIQUE,
   i2c UNIQUE
  );" 

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE gpio (
  id INTEGER PRIMARY KEY,
  gpio UNIQUE,
  name TEXT,
  time_checkbox TEXT,
  time_run TEXT,
  time_offset TEXT,
  time_start TEXT,
  temp_checkbox TEXT,
  temp_run TEXT,
  temp_sensor TEXT,
  temp_onoff TEXT,
  temp_temp REAL,
  temp_op TEXT,
  gpio_rev_hilo TEXT,
  gpio_mode TEXT,
  humi_checkbox TEXT,
  humi_type TEXT,
  day_checkbox TEXT,
  day_zone1s TEXT,
  day_zone1e TEXT,
  day_run TEXT,
  tempday_checkbox TEXT,
  tempday_run TEXT,
  simple_run TEXT,
  trigger_checkbox TEXT,
  trigger_run TEXT,
  trigger_notice TEXT,
  gpio_kwh TEXT,
  gpio_kwh_divider TEXT,
  gpio_kwh_hilo TEXT
    );"

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE settings (
   id INTEGER PRIMARY KEY,
   mail TEXT,
   sms TEXT,
   highcharts TEXT,
   rrd TEXT,
   fw TEXT,
   vpn TEXT,
   gpio TEXT,
   kwh TEXT
  );"

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE fw (
   id INTEGER PRIMARY KEY,
   ssh TEXT,
   icmp TEXT,
   openvpn TEXT,
   ext TEXT
    );"

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE vpn ( 
    id INTEGER PRIMARY KEY, 
    users UNIQUE 
    );"

sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO users (login, password, perms ) VALUES ('admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', 'adm')"
#sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO users (login, password, perms ) VALUES ('temp', 'd969831eb8a99cff8c02e681f43289e5d3d69664', 'ops')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO device (usb, onewire, serial, i2c) VALUES ('off','off','off','off')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO settings (mail, sms, rrd, highcharts, fw, vpn, gpio ) VALUES ('off','off', 'on', 'on', 'off', 'off', 'off' )"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO fw (ssh, icmp, ext, openvpn ) VALUES ('off','off', '0.0.0.0/0', 'off' )"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO mail_settings (host, port, user ) VALUES ('smtp.gmail.com', '587', 'yourmail@gmail.com' )"


chmod 775 $dir/dbf/nettemp.db
chgrp www-data $dir/dbf/nettemp.db
echo "$date Default settings restored" >> $dir/tmp/log.txt

# SNMP

rm -rf $dir/dbf/snmp.db
sqlite3 $dir/dbf/snmp.db  "CREATE TABLE snmp (
  id INTEGER PRIMARY KEY,
  name UNIQUE,
  community TEXT,
  host TEXT,
  oid TEXT,
  divider TEXT
  );"

chmod 775 $dir/dbf/snmp.db
chgrp www-data $dir/dbf/snmp.db


