#! /bin/bash  

dir=$(cd "$( dirname "$0" )" && cat ../../conf.php |grep global | awk -F"'" '{ print $2 }')
date=`date +%y%m%d-%H%M`

name="snmp"

rm -rf $dir/dbf/$name.db

sqlite3 $dir/dbf/$name.db  "CREATE TABLE snmp (
  id INTEGER PRIMARY KEY,
  name UNIQUE,
  community TEXT,
  host TEXT,
  oid TEXT,
  divider TEXT
  );"

chmod 777 $dir/dbf/snmp.db
echo "$date Default settings restored for snmp" >> $dir/tmp/log.txt
chmod 777 $dir/tmp/log.txt
