#! /bin/bash

dir=$(cd "$( dirname "$0" )" && cat ../../conf.php |grep global | awk -F"'" '{ print $2 }')

sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD vpn type TEXT";
sqlite3 $dir/dbf/nettemp.db "CREATE TABLE vpn (id INTEGER PRIMARY KEY,users UNIQUE);"
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD fw type TEXT";
sqlite3 $dir/dbf/nettemp.db "CREATE TABLE fw (id INTEGER PRIMARY KEY,ssh TEXT,icmp TEXT,openvpn TEXT,ext TEXT);"
sqlite3 $dir/dbf/nettemp.db "INSERT OR REPLACE INTO fw (id, ssh, icmp, ext, openvpn ) VALUES (1,'off','off', '0.0.0.0/0', 'off');"
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD kwh type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD gpio type TEXT";
sqlite3 $dir/dbf/nettemp.db "INSERT OR REPLACE INTO settings (id,gpio) VALUES (1,'off');"
