#! /bin/bash 

sqlite3 ../../../dbf/nettemp.db "drop table logoterma"

sqlite3 dbf/nettemp.db "CREATE TABLE logoterma (
  id INTEGER PRIMARY KEY,
  mode TEXT,
  manual_end_time TEXT,
  manual_temp TEXT,
  auto_temp TEXT
  );" 

sqlite3 dbf/nettemp.db "INSERT INTO logoterma (mode) VALUES('manual')"