version: '3.9'

services:
  nettemp:
    container_name: nettemp
    image: przemeksdocker/nettemp
    restart: unless-stopped
    volumes:
      - nettemp-data:/var/www/nettemp/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "443:443"   # selfsigned ssl cert
      #- "8000:8000"  # no ssl
      #- "80:80"     # redirect to 443
    environment:
        DATABASE_TYPE: "sqlite" # sqlite, mysql
        # HTTPS: False  # if not using https

volumes:
    nettemp-data:

