#! /bin/bash

R='\033[0m'
RED='\033[00;31m'
REDB='\033[01;41;35m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'

dir=/var/www/nettemp

if [[ ! $(pwd) = "$dir" ]]; then
        whiptail --title "Nettemp installer" --msgbox "Nettemp installer must be in /var/www/nettemp dir. Hit OK to exit." 8 78
exit 1
fi 

if [[ $UID -ne 0 ]]; then
    whiptail --title "Nettemp installer" --msgbox "You must be root. Hit OK to exit." 8 78
exit 1
fi 

function fexit {
$1
exitstatus=$?
if [ $exitstatus = 1 ]; then
    whiptail --clear  --title "Nettemp installer" --msgbox "Error $1" 8 78
    echo -e "[ ${red}error${R} ] Error in $1"
    exit 1
else
    echo -e "[ ${GREEN}ok${R} ] $1"
fi
}

function end {
whiptail  --title "Nettemp installer" --msgbox "Nettemp successfully installed. Your user and password is \"admin\"." 8 78
whiptail  --title "Nettemp installer" --msgbox "admin admin - remember!" 8 78
exitstatus=$?
if [ $exitstatus = 0 ]; then
    if int=$(ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'); then
	echo -e "[ ${GREEN}ok${R} ] Go to http://$int"
    else
	int=$(ifconfig wlan0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://')
	echo -e "[ ${GREEN}ok${R} ] Go to http://$int"
    fi
    echo -e "Bye..."
    exit 1
fi
}

function checkifrpi {
rpi=$(cat /proc/cmdline | awk -v RS=" " -F= '/boardrev/ { print $2 }')
if [ -n "$rpi" ]; then
    echo -e "[ ${GREEN}ok${R} ] Raspberry Pi detected"
else
    echo -e "[ ${GREEN}ok${R} ] no Raspberry Pi detected"
fi
}

function services {
service ntp start
service lighttpd restart
}

function perms {
$dir/modules/tools/update_su
$dir/modules/tools/update_perms
umask 002 $dir/tmp
umask 002 $dir/db
umask 002 $dir/dbf
}

function i2c {
if [ -n "$rpi" ]; then
    if cat /etc/modules |grep i2c-bcm2708 1> /dev/null; then
	echo -e "[ ${GREEN}ok${R} ] i2c-bcm2708  allready added"
    else
	sed -i '$ai2c-bcm2708' /etc/modules
    fi
    sed -i 's/blacklist spi-bcm2708/#blacklist spi-bcm2708/g' /etc/modprobe.d/raspi-blacklist.conf
    sed -i 's/blacklist i2c-bcm2708/#blacklist i2c-bcm2708/g' /etc/modprobe.d/raspi-blacklist.conf
fi

    if cat /etc/modules |grep i2c-dev 1> /dev/null; then
	echo -e "[ ${GREEN}ok${R} ] i2c-dev allready added"
    else
	sed -i '$ai2c-dev' /etc/modules
    fi
    if cat /etc/modules |grep ds2482 1> /dev/null; then
	echo -e "[ ${GREEN}ok${R} ] ds2482 allready added"
    else
	sed -i '$ads2482' /etc/modules
    fi
}

function ups {
if dpkg --get-selections | grep -q apcupsd; then
    echo -e "[ ${GREEN}ok${R} ] ups function already installed"
    else
    $dir/modules/ups/install
fi
}
function vpn {
    echo -e "[ ${GREEN}ok${R} ] Generating certs for OpenVPN. Please wait.."
    {
    $dir/modules/security/vpn/install
    } &> /dev/null
}

function firewall {
    $dir/modules/security/fw/install
} &> /dev/null



function sensors {
#1wire
$dir/install/1wire on off off

#dht 11/22
cd $dir/modules/sensors/GPIO/DHT/dhtlib/
./install
cd -

}


function wiringpi {
if [ -n "$rpi" ];then
        git clone git://git.drogon.net/wiringPi
	cd wiringPi
	./build
fi
}
# echo -e "${GREEN}Add watchdog${R}"
# update-rc.d watchdog defaults
# if cat /etc/modules |grep bcm2708_wdog 1> /dev/null
# then
# echo "bcm2708_wdog exist in file"
# else
# echo "bcm2708_wdog" | sudo tee -a /etc/modules
# fi
# sed -i -e '10s/#max-load-1/max-load-1/' /etc/watchdog.conf
# sed -i -e '23s/#watchdog-device/watchdog-device/' /etc/watchdog.conf
# /etc/init.d/watchdog start
#fi
#}

function cron {
if crontab -l |grep nettemp 1> /dev/null; then
echo -e "[ ${GREEN}ok${R} ] Cron lines already exist"
else
echo "*/1 * * * * $dir/modules/cron/1" > /var/spool/cron/crontabs/root
echo "*/5 * * * * $dir/modules/cron/5" >> /var/spool/cron/crontabs/root
echo "0 * * * * $dir/modules/cron/1h" >> /var/spool/cron/crontabs/root
echo "@reboot $dir/modules/cron/r" >> /var/spool/cron/crontabs/root
chmod 600 /var/spool/cron/crontabs/root
fi
}
function database {
$dir/modules/tools/db_reset
} &>/dev/null

function check-other-www-servers {
if dpkg --get-selections | grep apache; then
service apache2 stop
update-rc.d apache2 disable
echo -e "[ ${GREEN}ok${R} ] Looks like You have Apache, service was stoped, until reboot.$old"
fi
}

function www-server {
#lighttpd
$dir/install/lighttpd
#ssl
#$dir/install/lighttpd_ssl_on

}

function packages { 
echo -e "[ ${GREEN}ok${R} ] Installing packages. Please wait.."
{
package="lighttpd php5-cgi php5-sqlite rrdtool sqlite3 msmtp digitemp gammu git-core mc sysstat \
    sharutils bc htop snmp sudo ntp watchdog python-smbus i2c-tools openvpn iptables rcconf arp-scan snmpd httping fping make gcc lynx expect socat"
    apt-get -y install $package
} &> /dev/null
}

function update {
    echo -e "[ ${GREEN}ok${R} ] apt-get repo updating. Please wait.."
    {
    apt-get -y update
    } &> /dev/null
}


function start {
whiptail  --backtitle "Nettemp.pl" --title "Nettemp installer" --yesno "Do You want install nettemp?" 8 78
exitstatus=$?
if [ $exitstatus = 1 ]; then
    echo "bye.."
    exit 1
fi
}

function smstools {
    echo -e "[ ${GREEN}ok${R} ] Installing SMStools. Please wait.."
    {
    chmod +x $dir/install/smstools
    $dir/install/smstools
    } &> /dev/null
}




start
fexit checkifrpi
fexit update
fexit packages
fexit smstools
fexit check-other-www-servers
fexit www-server
fexit database
fexit cron
fexit wiringpi
fexit sensors
fexit ups
fexit vpn
fexit firewall
fexit i2c
fexit perms
fexit services
end

#echo "(Exit status was $exitstatus)"

