#! /bin/bash

R='\033[0m'
RED='\033[00;31m'
REDB='\033[01;41;35m'
GREEN='\033[00;32m'
YELLOW='\033[00;33m'

dir=/var/www/nettemp

if [[ ! $(pwd) = "$dir" ]]; then
        whiptail --title "Nettemp installer" --msgbox "Nettemp installer must be in /var/www/nettemp dir. Hit OK to exit." 8 78
exit 1
fi 

if [[ $UID -ne 0 ]]; then
    whiptail --title "Nettemp installer" --msgbox "You must be root. Hit OK to exit." 8 78
exit 1
fi 

function fexit {
$1
exitstatus=$?
if [ $exitstatus = 1 ]; then
    whiptail --clear  --title "Nettemp installer" --msgbox "Error $1" 8 78
    echo -e "[ ${red}error${R} ] Error in $2"
    exit 1
else
    echo -e "[ ${GREEN}ok${R} ] $2"
fi
}

function end {
whiptail  --title "Nettemp installer" --msgbox "Nettemp successfully installed. Your user and password is \"admin\"." 8 78
whiptail  --title "Nettemp installer" --msgbox "admin admin - remember!" 8 78
exitstatus=$?
if [ $exitstatus = 0 ]; then
    if int=$(ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'); then
	echo -e "[ ${GREEN}ok${R} ] Go to http://$int"
    else
	int=$(ifconfig wlan0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://')
	echo -e "[ ${GREEN}ok${R} ] Go to http://$int"
    fi
    echo -e "Bye..."
    exit 1
fi
}


function run {
source $dir/install/run.sh
} #>> install_log.txt 2>&1


function start {
whiptail  --backtitle "Nettemp.pl" --title "Nettemp installer" --yesno "Do You want install nettemp?" 8 78
exitstatus=$?
if [ $exitstatus = 1 ]; then
    echo "bye.."
    exit 1s
fi

whiptail  --backtitle "Nettemp.pl" --title "Nettemp installer" --yesno "Do You want generate OpenVPN certificate? (Long installation)" 8 78
exitstatus2=$?
if [ $exitstatus2 = 0 ]; then
    OVCA=yes
fi

whiptail  --backtitle "Nettemp.pl" --title "Nettemp installer" --yesno "Do You want start APC UPS?" 8 78
exitstatus2=$?
if [ $exitstatus2 = 0 ]; then
    APCUPS=yes
fi

whiptail  --backtitle "Nettemp.pl" --title "Nettemp installer" --yesno "Do You want send anonymous stats to stats.nettemp.pl" 8 78
exitstatus3=$?
if [ $exitstatus3 = 0 ]; then
    SENDSTATS=yes
fi

}

start
fexit run Installation
end

