#! /bin/bash

if cat /etc/lighttpd/lighttpd.conf |grep Password  1> /dev/null ; then 
	echo "Password already set"
	echo "Do You want change password? (Y/N) Disable (D) Enable (E)?"
	read q
	if [ "$q" = "Y" ];then
	echo "Enter password"
	read pass2
	echo "Confirm password"
	read pass22
	    if [ "$pass2" == "$pass22" ]; then
        echo "admin:$pass22" > /etc/lighttpd/.lighttpdpassword
	echo "User is nettempadmin"
	echo "Password set successfully"
	    else 
		echo "Pass not match"
	    fi
	elif [ "$q" = "D" ];then
	     sed -i -e '2s/"mod_auth",/#	"mod_auth",/' /etc/lighttpd/lighttpd.conf
	    /etc/init.d/lighttpd restart
	    echo "Passowrd Disabled"
	elif [ "$q" = "E" ];then
	     sed -i -e '2s/#	"mod_auth",/	"mod_auth",/' /etc/lighttpd/lighttpd.conf
	    /etc/init.d/lighttpd restart
	    echo "Passowrd Enabled"
	
	else
	echo "Bye"
	fi

    else
	echo "Enter password"
	read pass
	echo "Confirm password"
	read pass2
    if [ "$pass" == "$pass2" ]; then
	sed -i 's/.*server.modules = (.*/&\n	"mod_auth",/' /etc/lighttpd/lighttpd.conf
	sed -i '$aauth.debug = 2' /etc/lighttpd/lighttpd.conf
	sed -i '$aauth.backend = "plain"' /etc/lighttpd/lighttpd.conf
	sed -i '$aauth.backend.plain.userfile = "/etc/lighttpd/.lighttpdpassword"' /etc/lighttpd/lighttpd.conf
	sed -i '$aauth.require = ( "/" =>' /etc/lighttpd/lighttpd.conf
	sed -i '$a(' /etc/lighttpd/lighttpd.conf
	sed -i '$a"method" => "basic",' /etc/lighttpd/lighttpd.conf
	sed -i '$a"realm" => "Password protected area",' /etc/lighttpd/lighttpd.conf
	sed -i '$a"require" => "user=nettempadmin"' /etc/lighttpd/lighttpd.conf
	sed -i '$a)' /etc/lighttpd/lighttpd.conf
	sed -i '$a)' /etc/lighttpd/lighttpd.conf
	touch /etc/lighttpd/.lighttpdpassword
	chown www-data:www-data /etc/lighttpd/.lighttpdpassword
	echo "nettempadmin:$pass" > /etc/lighttpd/.lighttpdpassword
	/etc/init.d/lighttpd restart
	echo "User is nettempadmin"
	echo "Password set successfully"
    else 
	echo "Pass not match"

    fi

fi