#! /bin/bash

sudo update-usbids
apt-get install hostapd dnsmasq

#iface wlan0 inet manual
#wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf
#iface default inet dhcp

iface wlan0 inet static
address 192.168.0.1
netmask 255.255.255.0

ifup wlan0

/etc/hostapd/hostapd.conf

interface=wlan0
driver=nl80211
ssid=nettemppl
hw_mode=g
channel=6
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=nettemppl
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP


service hostapd restart

/etc/dnsmasq.conf 

interface=wlan0
dhcp-range=192.168.0.1,192.168.0.250,255.255.255.0,1h


forward

service dnsmasq restart




