#! /bin/bash 

sqlite3 ../../../dbf/nettemp.db "drop table relays"

sqlite3 ../../../dbf/nettemp.db "CREATE TABLE relays (
  id INTEGER PRIMARY KEY,
  gpio UNIQUE,
  name TEXT,
  time_settings TEXT,
  end_time TEXT
    );" 


