#! /bin/bash

action="$1"
ip="$2"
proto="$3"
rule="$2"

tunnet="10.8.0.0/24"
localnet=$(ifconfig $(/sbin/route -n | grep "^0.0.0.0" | rev | cut -d' ' -f1 | rev) |grep -m 1 inet |awk -F":" '{print $2 $4}' | sed 's/Bcast/ /g' | awk -F '.' '{printf("%d.%d.%d.%d", $1, $2, $3, 0)} {print "/"255"."$5"."$6"."$7}')

if [ "$action" == "on" ];then
    sudo /sbin/iptables -F
    sudo /sbin/iptables -X
    sudo /sbin/iptables -t nat -X
    sudo /sbin/iptables -t nat -F
    sudo /sbin/iptables -P INPUT ACCEPT
    sudo /sbin/iptables -P OUTPUT ACCEPT
    sudo /sbin/iptables -P FORWARD DROP
    
    sudo /sbin/iptables -N DEFAULT
	sudo /sbin/iptables -N NETTEMP	
	 
    sudo /sbin/iptables -A DEFAULT -s localhost -j ACCEPT
    sudo /sbin/iptables -A DEFAULT -j ACCEPT -m state --state ESTABLISHED,RELATED
    sudo /sbin/iptables -A DEFAULT -s $localnet -j ACCEPT
    
    sudo /sbin/iptables -A DEFAULT -j NETTEMP
    sudo /sbin/iptables -A DEFAULT -j DROP
    
    sudo /sbin/iptables -A INPUT -j DEFAULT
    sudo /sbin/iptables -A NETTEMP -s 0.0.0.0/0 -m limit --limit 1/second -p tcp --dport 22 -j ACCEPT
	sudo /sbin/iptables -A NETTEMP -s 0.0.0.0/0 -m limit --limit 1/second -p tcp --dport 80 -j ACCEPT

 elif [ "$action" == "off" ]; then
    sudo /sbin/iptables -F
    sudo /sbin/iptables -X
    sudo /sbin/iptables -t nat -X
    sudo /sbin/iptables -t nat -F
    sudo /sbin/iptables -P INPUT ACCEPT
    sudo /sbin/iptables -P OUTPUT ACCEPT
    sudo /sbin/iptables -P FORWARD ACCEPT	
fi
 
 if [ "$action"=="add" ] && [ "$proto" == "icmp" ];then
	sudo /sbin/iptables -A NETTEMP -s $ip -p icmp --icmp-type echo-request -j ACCEPT
 elif [ "$action"=="add" ] && [ "$proto" == "ssh" ];then
	sudo /sbin/iptables -A NETTEMP -s $ip -m limit --limit 1/second -p tcp --dport 22 -j ACCEPT
 elif [ "$action"=="add" ] && [ "$proto" == "http" ];then
   sudo /sbin/iptables -A NETTEMP -s $ip -p tcp --dport 80 -j ACCEPT
 elif [ "$action"=="add" ] && [ "$proto" == "https" ];then
   sudo /sbin/iptables -A NETTEMP -s $ip -p tcp --dport 443 -j ACCEPT
 elif [ "$action"=="add" ] && [ "$proto" == "vpn" ];then
   sudo /sbin/iptables -A NETTEMP -s $ip -p udp --dport 1194 -j ACCEPT
	#sudo /sbin/iptables -A NETTEMP -i tun0 -j ACCEPT
	sudo /sbin/iptables -A FORWARD -s $tunnet -j ACCEPT
	sudo /sbin/iptables -A FORWARD -s $localnet -j ACCEPT
	sudo /sbin/iptables -t nat -A POSTROUTING -s $tunnet -j MASQUERADE
 elif [ "$action"=="add" ] && [ "$proto" == "radius" ];then
	sudo /sbin/iptables -A NETTEMP -s $ip -p udp --dport 1812 -j ACCEPT
	sudo /sbin/iptables -A NETTEMP -s $ip -p udp --dport 1813 -j ACCEPT
 elif [ "$action"=="add" ] && [ "$proto" == "mysql" ];then
   sudo /sbin/iptables -A NETTEMP -s $ip -p tcp --dport 3306 -j ACCEPT
 elif [ "$action"=="add" ] && [ -n "$proto" ];then
   sudo /sbin/iptables -A NETTEMP -s $ip -p tcp --dport $proto -j ACCEPT
 fi
 
 if [ "$action"=="rm" ] && [ -n "$rule" ];then
  sudo /sbin/iptables -D NETTEMP $rule
 fi
 
 if [ ! -e /etc/iptables/rules.v4 ];then
		sudo /bin/mkdir -p /etc/iptables
		sudo /usr/bin/touch /etc/iptables/rules.v4
 fi
 sudo /bin/chmod 777 /etc/iptables/rules.v4
 sudo /sbin/iptables-save > /etc/iptables/rules.v4

     






