#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
$dir/modules/tools/check_update
php -f /var/www/nettemp/modules/thingspeak/thing_send.php intv=60
php -f $dir/modules/notifications/send_notifications.php ninterval=1h
