#!/bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

php -f /var/www/nettemp/modules/thingspeak/thing_send.php intv=2
php -f $dir/modules/notifications/send_notifications.php ninterval=2m
