#!/bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

php-cgi -f $dir/modules/sensors/virtual.php
php -f /var/www/nettemp/modules/thingspeak/thing_send.php intv=5
php -f $dir/modules/notifications/send_notifications.php ninterval=5m
