#!/bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
(tme $dir/modules/sms/sms_send) 2> $dir/tmp/debug/sms_send && \
(time $dir/modules/kwh/highcharts) 2> $dir/tmp/debug/kwh && \
(time $dir/modules/highcharts/highcharts2) 2> $dir/tmp/debug/highcharts
