#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
echo "$(date +\%y\%m\%d-\%H\%M) RPI rebooted" >> $dir/tmp/log.txt
$dir/modules/tools/restart
$dir/modules/counters/reset_water
$dir/modules/counters/reset_gas
$dir/modules/counters/reset_elec
nohup $dir/modules/lcd/lcd &
nohup $dir/modules/call/call_proc &

