#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
file=$dir/tmp/lcd

lcd=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db  "SELECT lcd FROM settings WHERE id='1'")
lcd4=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db  "SELECT lcd4 FROM settings WHERE id='1'")

if [[ "$lcd" == "on" ]]
then

    $dir/modules/lcd/lcdi2c -i -l -b 1 "$(printf "%-15s %-15s" "$(echo nettemp.pl| cut -c 1-15) " "$(echo lcd mod| cut -c 1-15)")"
    sleep 2
    while :
	do
	
	IFS=$'\n' lines=($(cat $file))
	max=$(cat $file |wc -l)
	f="0"
	s="1"
	    
	while [ "$s" -le "$max" ] ; do
	     $dir/modules/lcd/lcdi2c -l -b 1 "$(printf "%-15s %-15s" "$(echo ${lines[$f]} | sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humi/%/g' | cut -c 1-15)" "$(echo ${lines[$s]}| sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humi/%/g' | sed 's/volts/V/g' | sed 's/amps/A/g' | sed 's/watt/W/g' | cut -c 1-15)")"
					echo "$(printf "%-15s %-15s" "$(echo ${lines[$f]} | sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humi/%/g' | cut -c 1-15)" "$(echo ${lines[$s]}| sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humi/%/g' | sed 's/volts/V/g' | sed 's/amps/A/g' | sed 's/watt/W/g' | cut -c 1-15)")"
	    sleep 2
	    f=$(expr $f + 1)
	    s=$(expr $s + 1)
	done
	done

elif [[ "$lcd4" == "on" ]]
then

    $dir/modules/lcd/lcdi2c -i -l -b 1 "$(printf "%-15s %-15s" "$(echo nettemp.pl| cut -c 1-15) " "$(echo lcd mod| cut -c 1-15)")"
    sleep 2
    while :
	do
	
	IFS=$'\n' lines=($(cat $file))
	max=$(cat $file |wc -l)
	f="0"
	s="1"
	t="2"
      
	while [ "$s" -le "$max" ] ; do
            $dir/modules/lcd/lcdi2c4 -l -b 1 -r 0  "$(printf "%-19s %-19s %-19s %-19s" "$(echo ${lines[$f]} | sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humid/%/g' | cut -c 1-19)" "$(echo ${lines[$s]} | sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humid/%/g' | cut -c 1-19)" "$(echo ${lines[$t]} | sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humid/%/g' | sed 's/volts/V/g' | sed 's/amps/A/g' | sed 's/watt/W/g' | cut -c 1-19)" "$(date | cut -c 1-16)")"
        				     echo  "$(printf "%-19s %-19s %-19s %-19s" "$(echo ${lines[$f]} | sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humid/%/g' | cut -c 1-19)" "$(echo ${lines[$s]} | sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humid/%/g' | cut -c 1-19)" "$(echo ${lines[$t]} | sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humid/%/g' | sed 's/volts/V/g' | sed 's/amps/A/g' | sed 's/watt/W/g' | cut -c 1-19)" "$(echo ${lines[$l]} | sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humid/%/g' | sed 's/volts/V/g' | sed 's/amps/A/g' | sed 's/watt/W/g'  | cut -c 1-19)")"
    	    sleep 3
    	    f=$(expr $f + 1)
    	    s=$(expr $s + 1)
    	    t=$(expr $t + 1)
	done
	done

fi
