#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
file=$dir/tmp/lcd

onoff=$(sqlite3 $dir/dbf/nettemp.db  "SELECT lcd FROM settings WHERE id='1'")

if [ "$onoff" == "on" ]
then
$dir/modules/lcd/lcdi2c -i -l -b 1 "$(printf "%-15s %-15s" "$(echo nettemp.pl| cut -c 1-15) " "$(echo lcd mod| cut -c 1-15)")"
sleep 2
while :
    do
	
	IFS=$'\n' lines=($(cat $file))
	max=$(cat $file |wc -l)
	f="0"
	s="1"
	    
	while [ "$s" -le "$max" ] ; do
	    $dir/modules/lcd/lcdi2c -l -b 1 "$(printf "%-15s %-15s" "$(echo ${lines[$f]} | sed 's/pressure/hPa/g' | sed 's/temp/C/g' | sed 's/humi/%/g' | cut -c 1-15)" "$(echo ${lines[$s]} | sed 's/pressure/hPa/g' | sed 's/temp/C/g' | sed 's/humi/%/g' | cut -c 1-15)")"
	    echo "$(printf "%-15s %-15s" "$(echo ${lines[$f]} | sed 's/pressure/hPa/g' | sed 's/temp/C/g' | sed 's/humi/%/g' | cut -c 1-15 )" "$(echo ${lines[$s]}|  sed 's/pressure/hPa/g' | sed 's/temp/C/g' | sed 's/humi/%/g' |cut -c 1-15)")"
	    sleep 2
	    f=$(expr $f + 1)
	    s=$(expr $s + 1)
	done
done

fi
