#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

while : 
    do
    clear
    figlet nettemp
    echo -n "version "; echo -n "$(cd $dir && /usr/bin/git branch |grep [*]|awk '{print $2}') "; awk '/Changelog/{y=1;next}y' $dir/readme.md |head -2 |grep -v '^$'
    echo ""
    cat /var/www/nettemp/tmp/lcd | sed 's/temp/C/g' | sed 's/humid/%/g' | sed 's/press/Pa/g' | sed 's/humid/%/g' | column -t
    echo ""
    echo ""
    sleep 60
done