#! /bin/bash

list="/usr/sbin/lighttpd-enable-mod /usr/sbin/lighttpd-disable-mod /usr/sbin/chpasswd /usr/sbin/useradd \
/usr/sbin/userdel /usr/sbin/groupadd /usr/sbin/service /usr/sbin/update-rc.d /bin/sed /bin/cat \
/sbin/iptables /sbin/iptables-save /usr/sbin/i2cdetect /bin/chmod /bin/chgrp /sbin/reboot \
/usr/bin/whoami /usr/bin/killall /usr/bin/nohup /bin/chown"


for i in $list
    do
     if ! sudo cat /etc/sudoers |grep $i > /dev/null
	then 
	    echo Add missing $i to /etc/sudoers
	    sudo sed -i '$a www-data ALL=(ALL) NOPASSWD: '$i' *' /etc/sudoers
    fi
done