#! /bin/bash  

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M`

if [[ "$1" == git ]]; then 
    cd $dir && git reset --hard && cd -
fi

rm -rf $dir/dbf/*.db
#rm -rf $dir/db/*.rrd #uncomment will delete all stored data
rm -rf $dir/tmp
mkdir $dir/tmp

#for i in snmp hosts nettemp; do 
for i in nettemp; do
    rm -rf $dir/dbf/$i.db
    sqlite3 -cmd ".timeout 2000" $dir/dbf/$i.db < $dir/modules/tools/$i.schema
    chmod 775 $dir/dbf/$i.db
    chown root.www-data $dir/dbf/$i.db
done

php-cgi -f $dir/modules/tools/html/update_db.php









