#! /bin/bash  

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M`
cd $dir && git reset --hard && cd -

rm -rf $dir/dbf/*.db
#rm -rf $dir/db/*.rrd #uncomment will delete all stored data
rm -rf $dir/tmp
mkdir $dir/tmp

for i in snmp hosts kwh nettemp; do 
    rm -rf $dir/dbf/$i.db
    sqlite3 $dir/dbf/$i.db < $dir/modules/tools/$i.schema
    chmod 775 $dir/dbf/$i.db
    chown root.www-data $dir/dbf/$i.db
done


sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO users (login, password, perms ) VALUES ('admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', 'adm')"
#sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO users (login, password, perms ) VALUES ('temp', 'd969831eb8a99cff8c02e681f43289e5d3d69664', 'ops')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO device (usb, onewire, serial, i2c, lmsensors, wireless ) VALUES ('off','off','off','off','off','off')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO settings (mail, sms, rrd, highcharts, fw, vpn, gpio, authmod ) VALUES ('off','off', 'off', 'on', 'off', 'off', 'off', 'on' )"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO fw (ssh, icmp, ext, openvpn ) VALUES ('off','off', '0.0.0.0/0', 'off' )"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO mail_settings (host, port, user, auth, tls, tlscheck ) VALUES ('smtp.gmail.com', '587', 'yourmail@gmail.com', 'on', 'on', 'off' )"



