#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE sensors SET name='Taras' WHERE rom='0x280x880x9D0xF70x020x000x000xB6' OR rom='28-000002f79d88'"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE sensors SET name='Sypialnia' WHERE rom='0x280x040x5E0x250x030x000x000xE0' OR rom='28-000003255e04'"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE sensors SET name='Kuchnia' WHERE rom='0x280x6C0x580x250x030x000x000x1E' OR rom='28-00000325586c'"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE sensors SET name='Dziewczyny' WHERE rom='0x280xDE0x6E0x250x030x000x000x6F' OR rom='28-000003256ede'"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE sensors SET name='Salon' WHERE rom='0x280x890x360x250x030x000x000x6F' OR rom='28-000003253689'"
