#! /bin/bash

dir=/var/www/nettemp
date=`date +%y%m%d-%H%M`

get_mail=`sqlite3 $dir/dbf/nettemp.db "SELECT mail FROM recipient WHERE mail_alarm='yes'" | awk '{ printf " "$1 }'`
$dir/modules/mail/mail_test "$get_mail" "Nettemp restart" "Nettemp restarted at $date"