#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
dir2=$dir/tmp/system_stats
mkdir -p $dir2

#cpu=$(mpstat | grep all | sed -s 's/.* all// ; s/ * / /g' | cut -d ' ' -f10 | awk '{print 100-$1}')
cpu=$(mpstat | grep all | sed 's/.* all// ; s/ * / /g' | cut -d ' ' -f10 | awk '{print 100-$1}')
if [[ $cpu == "100" ]]; then
    cpu=$(mpstat | grep all | sed 's/.* all// ; s/ * / /g' | cut -d ' ' -f11 | awk '{print 100-$1}')
fi
max=$(free |grep Mem |awk '{print $2}')
memoryc=$(free | grep Mem | awk '{printf "%3.1f", ($3/'$max') * 100.0}')
memory=$(free | grep cache: | awk '{printf "%3.1f", ($3/'$max') * 100.0}')

#echo $cpu %
#echo $memoryc %
#echo $memory %

if [ ! -e $dir/db/system_cpu.sql ]; then
    for i in cpu memory memory_cached; do
	sqlite3 $dir/db/system\_$i.sql < $dir/modules/tools/system.schema
	chmod 775 $dir/db/$i.sql
	chown root.www-data $dir/db/$i.sql
    done
fi
rm -rf $dir/db/system*.rrd

sqlite3 $dir/db/system_cpu.sql "INSERT OR IGNORE INTO def (value) VALUES ('$cpu');"
sqlite3 $dir/db/system_memory_cached.sql "INSERT OR IGNORE INTO def (value) VALUES ('$memoryc');"
sqlite3 $dir/db/system_memory.sql "INSERT OR IGNORE INTO def (value) VALUES ('$memory');"






