#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
dir2=$dir/tmp/system_stats
mkdir -p $dir2

if [ ! -e $dir/db/system_cpu.rrd ]
then { echo "tworze bazy";

rrdtool create $dir/db/system_cpu.rrd -s 60 DS:cpu:GAUGE:100000:0:100000 \
RRA:AVERAGE:0.5:1:48384 \
RRA:MAX:0.5:1:48384 \
RRA:MIN:0.5:1:48384 \
RRA:LAST:0.5:1:48384

rrdtool create $dir/db/system_memory.rrd -s 60 DS:mem:GAUGE:100000:0:100000 \
RRA:AVERAGE:0.5:1:48384 \
RRA:MAX:0.5:1:48384 \
RRA:MIN:0.5:1:48384 \
RRA:LAST:0.5:1:48384

}
else 
{ 
echo "bazy sa";
}
fi

#cpu=$(mpstat | grep all | sed -s 's/.* all// ; s/ * / /g' | cut -d ' ' -f10 | awk '{print 100-$1}')
cpu=$(mpstat | grep all | sed 's/.* all// ; s/ * / /g' | cut -d ' ' -f10 | awk '{print 100-$1}')
memory=`free | grep Mem | awk '{print $3/$2 * 100.0}'`


echo $cpu
echo $memory

rrdtool update $dir/db/system_cpu.rrd N:$cpu
rrdtool update $dir/db/system_memory.rrd N:$memory


for i in hour day week month
do 
rrdtool graph $dir/tmp/system_stats/$i.png \
--imgformat PNG \
--title="$i" \
--width 390 --height 150 \
--vertical-label="RPi system `date +%H%M`" \
-s -1$i \
DEF:cpu=$dir/db/system_cpu.rrd:cpu:AVERAGE \
DEF:mem=$dir/db/system_memory.rrd:mem:AVERAGE \
LINE1:cpu#0000ff:"Used % CPU" \
GPRINT:cpu:LAST:"last %2.2lf " \
GPRINT:cpu:MIN:"min %2.2lf " \
GPRINT:cpu:MAX:"max %2.2lf " \
GPRINT:cpu:AVERAGE:"ave %2.2lf  \n" \
LINE1:mem#FF0000:"Used % Memory" \
GPRINT:mem:LAST:"last %2.2lf " \
GPRINT:mem:MIN:"min %2.2lf " \
GPRINT:mem:MAX:"max %2.2lf " \
GPRINT:mem:AVERAGE:"ave %2.2lf  \n" 

done



