#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

sudo chmod -R 775 $dir
sudo chown -R root.www-data $dir


for i in hosts snmp; do
if [ -e $dir/dbf/$i.db ]; 
    then
	sqlite3 $dir/dbf/$i.db .dump > $dir/dbf/$i.dump
	sqlite3 $dir/dbf/nettemp.db .dump > $dir/dbf/nettemp.dump
	sqlite3 $dir/dbf/nettemp.db < $dir/dbf/$i.dump
	rm $dir/dbf/$i.db
fi
done


sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD vpn type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE vpn (id INTEGER PRIMARY KEY,users UNIQUE);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD fw type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE fw (id INTEGER PRIMARY KEY,ssh TEXT,icmp TEXT,openvpn TEXT,ext TEXT);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE fw ADD radius type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD kwh type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD gpio type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE device ADD lmsensors type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD authmod type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE device ADD i2c type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD mode type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD simple type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD rev type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD humid_type type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD kwh_run type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD kwh_divider type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD day_run type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_run type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_status type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Mon type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Tue type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Wed type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Thu type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Fri type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Sat type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Sun type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD day_zone2s type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD day_zone2e type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD day_zone3s type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD day_zone3e type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD tempnum type TEXT";

#for i in $(seq 1 10);
 #   do
  #  sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_sensor$i type TEXT";
   # sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_sensor_diff$i type TEXT";
    #sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_onoff$i type TEXT";
    #sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_temp$i type TEXT";
    #sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_op$i type TEXT";
    #sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_hyst$i type TEXT";
    #sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_source$i type TEXT";
    #sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_week_plan$i type TEXT";
#done

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD status type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE mail_settings ADD error type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE device ADD wireless type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD ip type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD device type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD lcd type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD method type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD lcd4 type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD lcd type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD tmp_5ago type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE mail_settings ADD tlscheck type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE mail_settings ADD tls type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE mail_settings ADD auth type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE newdev (id INTEGER PRIMARY KEY,list UNIQUE);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE camera (id INTEGER PRIMARY KEY,list UNIQUE);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE camera ADD name type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE camera ADD link type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE relays (id INTEGER PRIMARY KEY,list UNIQUE);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE relays ADD name type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE relays ADD ip type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE relays ADD delay type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE relays ADD rom type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE relays ADD type type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE hosts ADD rom type TEXT";

for i in $(seq 1 30);
    do
    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD tout$i type TEXT";
done

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD control type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD control_run type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD trigger_delay type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD radius type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE i2c (id INTEGER PRIMARY KEY,name TEXT, addr UNIQUE);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE snmp ADD rom type UNIQUE";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD trigger_con type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE meteo ADD COLUMN onoff TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD tel_any type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD tel_at type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD tel type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD mail type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD smsa type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD maila type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD ctr type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD simple type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD trigger type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD moment type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD cam type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD at type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD smspin type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE users ADD smsts type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD call type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD adj type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE day_plan ADD gpio type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD charts type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD charts_system type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD charts_hosts type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD charts_gpio type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD charts_min type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD charts_theme type TEXT";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD server_key type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD client_key type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD client_ip type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD client_on type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD cauth_on type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD cauth_login type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD cauth_pass type TEXT";


sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD remote type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD i2c type TEXT";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE call_settings (id INTEGER PRIMARY KEY, name TEXT, dev TEXT, default_dev TEXT);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE access_time (id INTEGER PRIMARY KEY, name UNIQUE, Mon TEXT, Tue TEXT, Wed TEXT, Thu TEXT, Fri TEXT, Sat TEXT, Sun TEXT, stime TEXT, etime TEXT);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE day_plan (id INTEGER PRIMARY KEY, name UNIQUE, Mon TEXT, Tue TEXT, Wed TEXT, Thu TEXT, Fri TEXT, Sat TEXT, Sun TEXT, stime TEXT, etime TEXT);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE meteo (id INTEGER PRIMARY KEY, temp TEXT, latitude TEXT, height TEXT, pressure TEXT, humid TEXT, onoff TEXT);"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE mail_settings SET tlscheck='off' WHERE id='1' AND tlscheck is null"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE settings SET charts_system='on' WHERE charts_system is null"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE settings SET charts_hosts='on' WHERE charts_hosts is null"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE settings SET charts_gpio='on' WHERE charts_gpio is null"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE settings SET charts_min='10' WHERE charts_gpio is null"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE sensors SET charts='on' WHERE charts is null"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE sensors SET adj='0' WHERE adj='' OR adj=' ' OR adj is null"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE users SET perms='adm' WHERE login='admin' AND perms is null" 
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE OR IGNORE settings SET tempnum='3' where id='1' AND tempnum is null"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE OR IGNORE settings SET server_key='$(date +%s | sha256sum | base64 | head -c 10 ; echo)' where id='1' AND server_key is null"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO mail_settings (id,tlscheck) VALUES (1,'off');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO mail_settings (id,tls) VALUES (1,'on');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO mail_settings (id,auth) VALUES (1,'on');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO access_time (name, Mon, Tue, Wed, Thu, Fri, Sat, Sun, stime, etime) VALUES  ('any', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', '00:00', '23:59')"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('bmp180','77');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('tsl2561','39');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('ds2482','18');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('ds2482','1a');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('htu21d','40');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('mpl3115a2','60');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('hih6130','27');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('tmp102','48');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('bh1750','23');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO fw (id, ssh, icmp, ext, openvpn, radius ) VALUES (1,'off','off', '0.0.0.0/0', 'off', 'off');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO meteo (id, temp, latitude, height, pressure, humid, onoff ) VALUES (1,'0','0','0','0','0','off');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO settings (id,gpio) VALUES (1,'on');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO device (id,lmsensors) VALUES (1,'off');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO device (id,i2c) VALUES (1,'off');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO device (id,wireless) VALUES (1,'off');"

# 20151110

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "drop trigger aupdate_time_trigger;"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TRIGGER aupdate_time_trigger AFTER UPDATE ON sensors WHEN NEW.tmp BEGIN UPDATE sensors SET time = (datetime('now','localtime')) WHERE tmp = old.tmp; END;"


sqlite3 -cmd ".timeout 2000" $dir/dbf/kwh.db "ALTER TABLE kwh ADD current TYPE INTEGER";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD minmax type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD sum type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE sensors SET sum='0' WHERE sum='' OR sum=' ' OR sum is null"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE newdev ADD type type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE newdev ADD device type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE newdev ADD i2c type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE newdev ADD usb type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE newdev ADD gpio type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE newdev ADD ip type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD meteogram type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE settings SET meteogram='Poland/Pomerania/Gdansk' WHERE id='1' AND meteogram is null"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD elec_divider type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD water_divider type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD gas_divider type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD elec_run type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD water_run type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD gas_run type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD elec_debouncing type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD water_debouncing type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD gas_debouncing type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD fnum type TEXT";

#sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "DROP TABLE usb";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE usb (id INTEGER PRIMARY KEY, dev TEXT, device UNIQUE);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO usb (device,dev) VALUES ('RS485','none');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO usb (device,dev) VALUES ('1wire','none');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO usb (device,dev) VALUES ('1wire Serial','none');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO usb (device,dev) VALUES ('Modem Call','none');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO usb (device,dev) VALUES ('Modem SMS','none');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO usb (device,dev) VALUES ('UPS Pimowo','none');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD state type TEXT";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "PRAGMA journal_mode=WAL";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD map_pos type NUM";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD map_num type NUM";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD map type NUM";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE sensors SET map_num=ABS(300 + RANDOM() % 3600) WHERE map_num is null";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE sensors SET map_pos='{left:0,top:0}' WHERE map_pos is null";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE sensors SET map='on' WHERE map is null";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD map_pos type NUM";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD map_num type NUM";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD map type NUM";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET map_num=ABS(300 + RANDOM() % 3600) WHERE map_num is null";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET map_pos='{left:0,top:0}' WHERE map_pos is null";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET map='on' WHERE map is null";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE hosts ADD map_pos type NUM";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE hosts ADD map_num type NUM";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE hosts ADD map type NUM";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE hosts SET map_num=ABS(300 + RANDOM() % 3600) WHERE map_num is null";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE hosts SET map_pos='{left:0,top:0}' WHERE map_pos is null";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE hosts SET map='on' WHERE map is null";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD COLUMN position INTEGER DEFAULT 1"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE snmp ADD type type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD MCP23017 type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE hosts ADD alarm type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE camera ADD access_all type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE snmp ADD version type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE snmp SET version='2c' WHERE version is null";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD ups_status type TEXT";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD time type TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD position type NUM";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET position='1' WHERE position is null";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE hosts ADD position type NUM";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE hosts SET position='1' WHERE position is null";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD ch_group type NUM";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE statistics (id INTEGER PRIMARY KEY, agreement TEXT, nick TEXT, location TEXT, sensor_temp TEXT);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO statistics (agreement) VALUES ('no');"

#sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD display_name type TEXT";
#sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD control_on_map type TEXT";
#sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD display_name type TEXT";
#sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD transparent_bkg type TEXT";
#sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD background_color TEXT"
#sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD background_low TEXT"
#sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD background_high TEXT"
#sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD font_color TEXT"
#sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD font_size TEXT"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE g_func (id INTEGER PRIMARY KEY, position INTEGER DEFAULT 0, sensor TEXT, sensor2 TEXT, onoff TEXT, value TEXT, op TEXT, hyst TEXT, source TEXT, gpio TEXT, w_profile TEXT);"

#maps settings separate database
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE maps (id INTEGER PRIMARY KEY,type TEXT,element_id INTEGER,map_num type NUM, map_pos NUMERIC, position INTEGER DEFAULT 1);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE maps ADD map_on type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE maps ADD transparent type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE maps ADD control_on_map type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE maps ADD display_name type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE maps ADD transparent_bkg type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE maps ADD background_color TEXT"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE maps ADD background_low TEXT"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE maps ADD background_high TEXT"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE maps ADD font_color TEXT"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE maps ADD font_size TEXT"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE maps ADD icon TEXT"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE hosts ADD element_id type TEXT";
#sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD font_size TEXT"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE settings ADD temp_scale TEXT"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO settings (id, temp_scale) VALUES (1, 'C');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE settings SET temp_scale='C' WHERE temp_scale is null OR temp_scale=''";

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE highcharts (id INTEGER PRIMARY KEY,charts_min TEXT, charts_theme TEXT, charts_fast TEXT);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO highcharts (id, charts_min, charts_theme, charts_fast) VALUES (1, '1', 'black', 'on');"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE gpio ADD moment_time type TEXT";
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE charts (id INTEGER PRIMARY KEY,charts TEXT);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO charts (id, charts) VALUES (1, 'Highcharts');"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE rs485 (id INTEGER PRIMARY KEY,dev,addr TEXT);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD jg TEXT"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE sensors ADD current TEXT"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE meteo ADD normalized TEXT"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "CREATE TABLE heaters (id INTEGER PRIMARY KEY,temp_actual type TEXT,temp_set type TEXT,work_mode type TEXT,position INTEGER DEFAULT 1);"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE heaters ADD ip type TEXT"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE heaters ADD name type TEXT"
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "ALTER TABLE heaters ADD status type TEXT"

sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO heaters (id,name,temp_actual,temp_set, work_mode,status ) VALUES (3, 'Kuchnia', '21.5', '23', 'AUTO', 'OFF');"