#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

sudo chmod -R 775 $dir
sudo chown -R root.www-data $dir

if  ! sudo cat /var/spool/cron/crontabs/root |grep -q 'cron/1h'
    then
	sudo sed -i '$a0 * * * * '$dir'/modules/cron/1h' /var/spool/cron/crontabs/root
fi

if  ! sudo cat /var/spool/cron/crontabs/root |grep -q 'cron/00h'
    then
    sudo sed -i '$a00 00 * * * '$dir'/modules/cron/00h' /var/spool/cron/crontabs/root
fi


touch $dir/tmp/cronr

if [ ! -f /usr/local/lib/python2.7/dist-packages/Adafruit_BMP-*.egg ]; then 
    cd /tmp
    git clone https://github.com/adafruit/Adafruit_Python_BMP
    cd Adafruit_Python_BMP
    sudo python setup.py install
fi

if [ ! -f /usr/local/lib/python2.7/dist-packages/Adafruit_DHT-*.egg ]; then
    cd /tmp    
    git clone https://github.com/adafruit/Adafruit_Python_DHT.git
    cd Adafruit_Python_DHT
    sudo python setup.py install
fi



