#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

sudo chmod -R 775 $dir
sudo chown -R root.www-data $dir

if  ! sudo cat /var/spool/cron/crontabs/root |grep -q 'cron/1h'
    then
	sudo sed -i '$a0 * * * * '$dir'/modules/cron/1h' /var/spool/cron/crontabs/root
fi

if  ! sudo cat /var/spool/cron/crontabs/root |grep -q 'cron/00h'
    then
    sudo sed -i '$a00 00 * * * '$dir'/modules/cron/00h' /var/spool/cron/crontabs/root
fi

if  ! sudo cat /var/spool/cron/crontabs/root |grep -q '/thing_send intv=1'
    then
    sudo sed -i '$a*/1 * * * * php -f /var/www/nettemp/modules/thingspeak/thing_send.php intv=1' /var/spool/cron/crontabs/root
fi

if  ! sudo cat /var/spool/cron/crontabs/root |grep -q '/thing_send intv=5'
    then
    sudo sed -i '$a*/5 * * * * php -f /var/www/nettemp/modules/thingspeak/thing_send.php intv=5' /var/spool/cron/crontabs/root
fi

if  ! sudo cat /var/spool/cron/crontabs/root |grep -q '/thing_send intv=10'
    then
    sudo sed -i '$a*/10 * * * * php -f /var/www/nettemp/modules/thingspeak/thing_send.php intv=10' /var/spool/cron/crontabs/root
fi

if  ! sudo cat /var/spool/cron/crontabs/root |grep -q '/thing_send intv=30'
    then
    sudo sed -i '$a*/30 * * * * php -f /var/www/nettemp/modules/thingspeak/thing_send.php intv=30' /var/spool/cron/crontabs/root
fi

if  ! sudo cat /var/spool/cron/crontabs/root |grep -q '/thing_send intv=60'
    then
    sudo sed -i '$a0 * * * * php -f /var/www/nettemp/modules/thingspeak/thing_send.php intv=60' /var/spool/cron/crontabs/root
fi

touch $dir/tmp/cronr

if [ ! -f /usr/local/lib/python2.7/dist-packages/Adafruit_BMP-*.egg ]; then 
    cd /tmp
    git clone https://github.com/adafruit/Adafruit_Python_BMP
    cd Adafruit_Python_BMP
    sudo python setup.py install
fi

if [ ! -f /usr/local/lib/python2.7/dist-packages/Adafruit_DHT-*.egg ]; then
    cd /tmp    
    git clone https://github.com/adafruit/Adafruit_Python_DHT.git
    cd Adafruit_Python_DHT
    sudo python setup.py install
fi

# update mail
sudo sed -i 's/;sendmail_path =/sendmail_path = '\''\/usr\/bin\/msmtp -t'\''/g' /etc/php/7.0/fpm/php.ini
sudo sed -i 's/;sendmail_path =/sendmail_path = '\''\/usr\/bin\/msmtp -t'\''/g' /etc/php/7.0/cli/php.ini
# end update mail

