#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

sudo chmod -R 775 $dir
sudo chown -R root.www-data $dir

sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD vpn type TEXT";
sqlite3 $dir/dbf/nettemp.db "CREATE TABLE vpn (id INTEGER PRIMARY KEY,users UNIQUE);"
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD fw type TEXT";
sqlite3 $dir/dbf/nettemp.db "CREATE TABLE fw (id INTEGER PRIMARY KEY,ssh TEXT,icmp TEXT,openvpn TEXT,ext TEXT);"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO fw (id, ssh, icmp, ext, openvpn, radius ) VALUES (1,'off','off', '0.0.0.0/0', 'off', 'off');"
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE fw ADD radius type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD kwh type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD gpio type TEXT";
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO settings (id,gpio) VALUES (1,'on');"
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE device ADD i2c type TEXT";
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO device (id,i2c) VALUES (1,'off');"
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE device ADD lmsensors type TEXT";
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO device (id,lmsensors) VALUES (1,'off');"
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD authmod type TEXT";

sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD mode type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD simple type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD rev type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD humid_type type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD kwh_run type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD kwh_divider type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD day_run type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_run type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_status type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Mon type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Tue type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Wed type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Thu type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Fri type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Sat type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD week_Sun type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD day_zone2s type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD day_zone2e type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD day_zone3s type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD day_zone3e type TEXT";

sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD tempnum type TEXT";
sqlite3 $dir/dbf/nettemp.db "UPDATE or IGNORE settings SET tempnum='3' where id='1'"
for i in $(seq 1 10);
    do
    sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_sensor$i type TEXT";
    sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_sensor_diff$i type TEXT";
    sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_onoff$i type TEXT";
    sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_temp$i type TEXT";
    sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_op$i type TEXT";
    sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD temp_hyst$i type TEXT";
done
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD status type TEXT";
if [ ! -s $dir/dbf/kwh.db ]
    then
    sqlite3 $dir/dbf/kwh.db < $dir/modules/tools/kwh.schema
    sudo chmod 775 $dir/dbf/kwh.db
    sudo chown root.www-data $dir/dbf/kwh.db
    else 
    echo kwh.db exist
fi
sqlite3 $dir/dbf/kwh.db "CREATE INDEX time_index ON kwh(time)";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE mail_settings ADD error type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE device ADD wireless type TEXT";
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO device (id,wireless) VALUES (1,'off');"
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE sensors ADD ip type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE sensors ADD device type TEXT";
if [ ! -s $dir/dbf/hosts.db ]
    then
    sqlite3 $dir/dbf/hosts.db < $dir/modules/tools/hosts.schema
    sudo chmod 775 $dir/dbf/hosts.db
    sudo chown root.www-data $dir/dbf/hosts.db
    else 
    echo hosts.db exist
fi
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE sensors ADD lcd type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE sensors ADD method type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD lcd4 type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD lcd type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE sensors ADD tmp_5ago type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE mail_settings ADD tlscheck type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE mail_settings ADD tls type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE mail_settings ADD auth type TEXT";
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO mail_settings (id,tlscheck) VALUES (1,'off');"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO mail_settings (id,tls) VALUES (1,'on');"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO mail_settings (id,auth) VALUES (1,'on');"
sqlite3 $dir/dbf/nettemp.db "UPDATE mail_settings SET tlscheck='off' WHERE id='1'"
sqlite3 $dir/dbf/nettemp.db "CREATE TABLE newdev (id INTEGER PRIMARY KEY,list UNIQUE);"
sqlite3 $dir/dbf/nettemp.db "CREATE TABLE camera (id INTEGER PRIMARY KEY,list UNIQUE);"
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE camera ADD name type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE camera ADD link type TEXT";
sqlite3 $dir/dbf/nettemp.db "CREATE TABLE relays (id INTEGER PRIMARY KEY,list UNIQUE);"
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE relays ADD name type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE relays ADD ip type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE relays ADD delay type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE relays ADD rom type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE relays ADD type type TEXT";
sqlite3 $dir/dbf/hosts.db "ALTER TABLE hosts ADD rom type TEXT";

for i in $(seq 1 30);
    do
    sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD tout$i type TEXT";
done
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD control type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD control_run type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD trigger_delay type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD radius type TEXT";

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE i2c (id INTEGER PRIMARY KEY,name TEXT, addr UNIQUE);"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('bmp180','77');"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('tsl2561','39');"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('ds2482','18');"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('ds2482','1a');"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('htu21d','40');"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('mpl3115a2','60');"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('hih6130','27');"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO i2c (name,addr) VALUES ('tmp102','48');"
sqlite3 $dir/dbf/snmp.db "ALTER TABLE snmp ADD rom type UNIQUE";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD trigger_con type TEXT";

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE meteo (id INTEGER PRIMARY KEY, temp TEXT, latitude TEXT, height TEXT, pressure TEXT, humid TEXT, onoff TEXT);"
sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO meteo (id, temp, latitude, height, pressure, humid, onoff ) VALUES (1,'0','0','0','0','0','off');"
sqlite3 $dir/dbf/nettemp.db  "ALTER TABLE meteo ADD COLUMN onoff TEXT";

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE call_settings (id INTEGER PRIMARY KEY, name TEXT, dev TEXT, default_dev TEXT);"
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD tel_num1 type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD tel_num2 type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE gpio ADD tel_num3 type TEXT";

sqlite3 $dir/dbf/nettemp.db "ALTER TABLE users ADD tel type UNIQUE";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE users ADD mail type UNIQUE";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE users ADD smsa type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE users ADD maila type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE users ADD ctr type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE users ADD simple type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE users ADD trigger type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE users ADD moment type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE users ADD cam type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE users ADD at type TEXT";
sqlite3 $dir/dbf/nettemp.db "ALTER TABLE settings ADD call type TEXT";

sqlite3 $dir/dbf/nettemp.db "CREATE TABLE access_time (id INTEGER PRIMARY KEY, name UNIQUE, Mon TEXT, Tue TEXT, Wed TEXT, Thu TEXT, Fri TEXT, Sat TEXT, Sun TEXT, stime TEXT, etime TEXT);"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO access_time (name, Mon, Tue, Wed, Thu, Fri, Sat, Sun, stime, etime) VALUES  ('any', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', '00:00', '23:59')"




