#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

# 1-wire

if [ -e /sys/bus/w1/devices/w1_bus_master1/w1_master_slaves ]
    then 
    sqlite3 $dir/dbf/nettemp.db "UPDATE device SET onewire='on' WHERE id='1'"
    w1_count=$(cat /sys/bus/w1/devices/w1_bus_master*/w1_master_slaves |grep -c [-])
    if [ $w1_count != "0" ]
        then
        echo "1-wire: $w1_count sensors found"
        echo "$date temp_dev_scan - Discovered 1-wire temp sensors" >> $dir/tmp/log.txt
        for sensor in `cat /sys/bus/w1/devices/w1_bus_master*/w1_master_slaves`; do 
            if  [ -e /sys/bus/w1/devices/${sensor}/w1_slave ]; then
	        wynik=`awk -F'[ =]' ' $11 ~ /crc/ && $13 ~ /YES/ { getline; printf "%3.2f\n", $11/1000 } ' /sys/bus/w1/devices/${sensor}/w1_slave;`
	    echo $sensor  >>  $dir/tmp/onewire
	fi
        done
    fi
else
    sqlite3 $dir/dbf/nettemp.db "UPDATE device SET onewire='off' WHERE id='1'"
fi
