#! /bin/bash

# USB
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

usb=`sqlite3 $dir/dbf/nettemp.db "SELECT usb FROM device"`
if [ "$usb" != "off" ]; then
    skey=$(sqlite3 $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")
    rom=$(sqlite3 $dir/dbf/nettemp.db "SELECT rom FROM sensors WHERE rom LIKE '0x10%' OR rom LIKE '0x22%' OR rom LIKE '0x28%' OR rom LIKE '0x3b%'")
    for name in $rom; do
        name_1=$(echo $name |sed 's/..../& /g;s/+$//')
	num=`cat $dir/tmp/.digitemprc |grep "$name_1" |awk 'BEGIN {FS=" "} {print $2}'`

	if [ "$usb" = "DS2490" ]; then
    	    wynik=`/usr/bin/digitemp_$usb -c $dir/tmp/.digitemprc -t $num -q -o%.1C |grep -v Found`
	else 
    	    wynik=`/usr/bin/digitemp_$usb -c $dir/tmp/.digitemprc -t $num -q -o%.1C`
	fi
	php-cgi -f $dir/receiver.php key=$skey rom=$name value=$wynik type=temp
done
fi

unset wynik
