#! /bin/bash 

# Serial
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`


serial=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT serial FROM device"`
if [ "$serial" != "off" ]; then
skey=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")
grep ROM $dir/tmp/.digitemprcs | while read -r name
    do
#name_str=${#name}
#echo $name
name_0=$(echo $name| awk 'BEGIN {FS=" "} {print $3$4$5$6$7$8$9$10}')
name_1=$(echo $name| awk 'BEGIN {FS=" "} {print $3" "$4" "$5" "$6" "$7" "$8" "$9" "$10}')
name_2=`cat $dir/tmp/.digitemprcs |grep "$name_1" |awk 'BEGIN {FS=" "} {print $2}'`
name_3="$name_0.sql"

if [ "$serial" = "DS9097" ]; then
        wynik=`/usr/bin/digitemp_$serial -c $dir/tmp/.digitemprcs -t $name_2 -q -o%.1C`
        echo Serial: $wynik C
fi
    php-cgi -f $dir/receiver.php key=$skey rom=$name_0 value=$wynik type=temp
done
fi

unset wynik
