#! /bin/bash

# 1-wire gpio i2c
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

onewire=`sqlite3 $dir/dbf/nettemp.db "SELECT onewire FROM device"`
if [ "$onewire" == "on" ]; then
rom=$(sqlite3 $dir/dbf/nettemp.db "SELECT rom FROM sensors WHERE rom LIKE '28-%' OR rom LIKE '10-%'")
skey=$(sqlite3 $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")

for name in $rom
do
    if  [ -e /sys/bus/w1/devices/$name/w1_slave ]; then
        wynik=`awk -F'[ =]' ' $11 ~ /crc/ && $13 ~ /YES/ { getline; printf "%3.1f\n", $11/1000 } ' /sys/bus/w1/devices/$name/w1_slave;`
        echo 1-wire: $wynik C
        php-cgi -f $dir/receiver.php key=$skey rom=$name value=$wynik type=temp
    else 
	php-cgi -f $dir/receiver.php key=$skey rom=$name value=error type=temp
    fi
done
fi
unset wynik
