#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

if [ -e /mnt/1wire ]; then
    skey=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")
    for i in $(ls /mnt/1wire/ |grep ^[1-9]..)
	 do
		val=$(cat /mnt/1wire/$i/temperature)
		php-cgi -f $dir/receiver.php key=$skey type=temp value=$val rom=$(echo $i |sed 's/\./-/g'| sed -e 's/\(.*\)/\L\1/')
    done
fi


