#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=$(date +%y%m%d-%H%M)

dev=$(sqlite3 $dir/dbf/nettemp.db "SELECT dev FROM call_settings WHERE default_dev='on'")
gpios=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM gpio WHERE mode='call'")

if [[ -n "$dev" ]] && [[ -n "$gpios" ]]; then

array=()
c=$(wc -w <<< "$gpios")
if [[ "$c" = "1" ]]; then 
    gpios="$(echo $gpios 0 0)"
elif [[ "$c" = "2" ]]; then 
    gpios="$(echo $gpios 0)"
fi

for i in $gpios; do
    array=("${array[@]}" "$i")
    first=$(sqlite3 $dir/dbf/nettemp.db "SELECT tel_num1 FROM gpio WHERE gpio='$i'")
    if [  -n "$first" ]; then
	array=("${array[@]}" "$first")
    else
	array=("${array[@]}" "000000000000")
    fi

    sec=$(sqlite3 $dir/dbf/nettemp.db "SELECT tel_num2 FROM gpio WHERE gpio='$i'")
    if [  -n "$sec" ]; then
	array=("${array[@]}" "$first")
    else
	array=("${array[@]}" "000000000000")
    fi

    thi=$(sqlite3 $dir/dbf/nettemp.db "SELECT tel_num2 FROM gpio WHERE gpio='$i'")
    if [  -n "$thi" ]; then
	array=("${array[@]}" "$first")
    else
	array=("${array[@]}" "000000000000")
    fi

done


#echo ${array[@]}
$dir/modules/gpio/call $dev ${array[@]}

fi
