#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
day=$(LC_ALL=en_EN.utf8 date '+%a')
date2=$(date +%H%M|sed 's/^\0//g')

if [ -z "$gpio" ]
    then
	gpio="$1"
	mode="single"
fi
day_run=$(sqlite3 $dir/dbf/nettemp.db "SELECT day_run FROM gpio WHERE gpio='$gpio'")
if [ "$day_run" = "on" ]; then

	names=$(sqlite3 $dir/dbf/nettemp.db "SELECT name FROM day_plan WHERE gpio='$gpio' and (mon='$day' OR tue='$day' OR wed='$day' OR thu='$day' OR fri='$day' OR sat='$day' OR sun='$day')")
	#echo $gpio
	#echo "$names"
	for i in $names; do
	    stime=$(sqlite3 $dir/dbf/nettemp.db "SELECT stime FROM day_plan WHERE name='$i'")
	    etime=$(sqlite3 $dir/dbf/nettemp.db "SELECT etime FROM day_plan WHERE name='$i'")
	    stimec=$(echo $stime | sed 's/://g'|sed 's/^\0//g')
	    etimec=$(echo $etime | sed 's/://g'|sed 's/^\0//g')
	    if (("$date2" >= "$stimec")) && (("$date2" < "$etimec")); then
		onoff="on"
		sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='ON - Profile $i' WHERE gpio='$gpio'"
		break
	    else
	    	sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='off' WHERE gpio='$gpio'"
	    	onoff="off"
	    fi
	done

    if [ $mode == "single" ]
	then
    	    echo $onoff
    else
	gpio_$onoff $gpio
	echo $onoff
    fi

fi

