#! /bin/bash 
 
dir=/var/www/nettemp
date=$(date +%y%m%d-%H%M)
now_time_s=`date +%s`

check() {

	# set mode after reboot	
	gpio_mode=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM gpio WHERE gpio_mode='output'")
	for gpio in $gpio_mode; do
	    /usr/local/bin/gpio -g mode $gpio output
	done


	# check time, if end turn off relay
	if [ -n "$1" ]; then
	    gpio_list=$1
	else
	    gpio_list=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM gpio WHERE custom_time_on='on'")
	fi

	for gpio in $gpio_list; do 
		end_time_ff=$(sqlite3 $dir/dbf/nettemp.db "SELECT end_time FROM gpio WHERE gpio='$gpio'")
			if [ -n "$end_time_ff" ] && [ "$end_time_ff" -ne "0" ]; then
	    		#echo End time: $end_time_ff
	    		#echo End date: $(date --date="1970-01-01 UTC +$end_time_ff sec" +"%a %b %d %H:%M:%S %Y")
	    			if [ $end_time_ff -lt $now_time_s ]; then # lt  mnijsze 
		    		#echo Time end
		    		sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET end_time='0' WHERE gpio='$gpio'"
		    		off $gpio
		    		echo "off"
		    		sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET custom_time_on='off' WHERE gpio='$gpio'"
		    		echo "$date Gpio $gpio is OFF" >> $dir/tmp/log.txt	    	
				else 
		   		diff=$(( $end_time_ff - $now_time_s ))
		    		echo "Elapsed time is $(($diff/60)) min, ($diff sec)" 
				fi	
			else 
				echo ""

  			fi
	done


	#temp on/off

	if [ -n "$1" ]; then
	    gpio_list2=$1
	else
	    gpio_list2=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM gpio WHERE gpio_temp_on='on'")
	fi
	
	for gpio2 in $gpio_list2; do 

	if [ "$temp_onoff" = "on" && "$temp_sensor" -lt "$temp_temp"  ]; then
		on $gpio_from_line
		elif [ "$temp_onoff" = "on" && "$temp_sensor" -lt "$temp_temp"  ]; then
		off $gpio_from_line
	fi

	

	done 





gpio_from_line=17
gpio_temp_on=`sqlite3 $dir/dbf/nettemp.db "SELECT gpio_temp_on FROM gpio WHERE gpio='$gpio_from_line'"`
gpio_temp_sensor=`sqlite3 $dir/dbf/nettemp.db "SELECT gpio_temp_sensor FROM gpio WHERE gpio='$gpio_from_line'"`
gpio_temp_onoff=`sqlite3 $dir/dbf/nettemp.db "SELECT gpio_temp_onoff FROM gpio WHERE gpio='$gpio_from_line'"`
gpio_temp_grlo=`sqlite3 $dir/dbf/nettemp.db "SELECT gpio_temp_grlo FROM gpio WHERE gpio='$gpio_from_line'"`
gpio_temp_temp=`sqlite3 $dir/dbf/nettemp.db "SELECT gpio_temp_temp FROM gpio WHERE gpio='$gpio_from_line'"`

#echo $gpio_temp_on
#echo $gpio_temp_sensor
#echo $gpio_temp_onoff
#echo $gpio_temp_grlo
#echo $gpio_temp_temp



}
# end check

tempon() {
		gpio_from_line=$1
		temp_sensor=$2
		temp_onoff=$3
		temp_grlo=$4
		temp_temp=$5
		sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET gpio_temp_sensor='$temp_sensor' WHERE gpio='$gpio_from_line'"
		sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET gpio_temp_onoff='$temp_onoff' WHERE gpio='$gpio_from_line'"
		sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET gpio_temp_grlo='$temp_grlo' WHERE gpio='$gpio_from_line'"
		sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET gpio_temp_temp='$temp_temp' WHERE gpio='$gpio_from_line'"
		sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET gpio_temp_set_on='on' WHERE gpio='$gpio_from_line'" #turn on temp
		
		echo "$date Gpio $gpio temperature on" >> $dir/tmp/log.txt	    
}

timeon() {
		gpio_from_line=$1
		offset=$2
		end_time=$(date -d "`date` +$offset second" +%s)
		sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET end_time='$end_time' WHERE gpio='$gpio_from_line'"
		#sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET custom_time_on='on' WHERE gpio='$gpio_from_line'" //php też wlacza
		on $gpio_from_line
		echo "$date Gpio $gpio time on" >> $dir/tmp/log.txt	    
    }

off(){        
        gpio_from_line=$1
	sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET custom_time_on='off' WHERE gpio='$gpio_from_line'"
	sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET gpio_mode='input' WHERE gpio='$gpio_from_line'"
      	sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET end_time='0' WHERE gpio='$gpio_from_line'"
	rev=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio_rev_hilo FROM gpio WHERE gpio='$gpio_from_line'")
	   	if [ $rev = on ]; then 
		/usr/local/bin/gpio -g write $gpio_from_line 1
		else
		/usr/local/bin/gpio -g write $gpio_from_line 0
		fi
	echo "$date Gpio $gpio is OFF" >> $dir/tmp/log.txt           
    }

    

on(){
           gpio_from_line=$1
    	    /usr/local/bin/gpio -g mode $gpio_from_line output
	    rev=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio_rev_hilo FROM gpio WHERE gpio='$gpio_from_line'")
	   	if [ "$rev" = "on" ]; then 
		/usr/local/bin/gpio -g write $gpio_from_line 0
		else
		/usr/local/bin/gpio -g write $gpio_from_line 1
		fi
	   echo "$date Gpio $gpio is ON" >> $dir/tmp/log.txt           
	}

status() {
if [ -n "$1" ];then
	gpio_from_line=$1
	onoff=$(/usr/local/bin/gpio -g read $gpio_from_line)
	rev=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio_rev_hilo FROM gpio WHERE gpio='$gpio_from_line'")
		if [[ "$onoff" = "1"  &&  "$rev" = "off" ]]; then
			echo "on";
		fi
		if [[ "$onoff" = "0"  &&  "$rev" = "on" ]]; then
			echo "on";
		fi
		if [[ "$onoff" = "0"  &&  "$rev" = "off" ]]; then
			echo "off";
		fi
		if [[ "$onoff" = "1"  &&  "$rev" = "on" ]]; then
			echo "off";
		fi
else 
		echo "no gpio"
fi
	}


add() {
if [ "$1" = "4" ] || [ "$1" = "17" ] || [ "$1" = "18" ] || [ "$1" = "21" ] || [ "$1" = "22" ] || [ "$1" = "23" ] || [ "$1" = "24" ] || [ "$1" = "25" ]; then
	gpio_from_line=$1
	sqlite3 $dir/dbf/nettemp.db "INSERT INTO gpio (gpio, name, end_time, gpio_rev_hilo ) VALUES ('$gpio_from_line','new', 0, 'off')"
	/usr/local/bin/gpio -g mode $gpio_from_line output
	sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET gpio_mode='output' WHERE gpio='$gpio_from_line'"
fi
	}

del() {
	if [ -n "$1" ]; then
		gpio_from_line=$1
		sqlite3 $dir/dbf/nettemp.db "DELETE FROM gpio WHERE gpio='$gpio_from_line'"
		/usr/local/bin/gpio -g write $gpio_from_line 0
		/usr/local/bin/gpio -g mode $gpio_from_line input
	fi
	}



    case "$1" in
    "on") on $2 ;;
    "off") off $2 ;;
    "timeon") timeon $2 $3 ;;
    "tempon") tempon $2 $3 $4 $5 $6 ;;
    "status") status $2 ;;
    "check") check $2 ;;
    "add") add $2 ;;
    "del") del $2 ;;
    *) echo "no inputs" ;;
    esac


