#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=$(date +%y%m%d-%H%M)

gpio_on(){
    rev=$(sqlite3 $dir/dbf/nettemp.db "SELECT rev FROM gpio WHERE gpio='$1'")
    /usr/local/bin/gpio -g mode $1 output
    if [ "$rev" = "on" ]; then 
	/usr/local/bin/gpio -g write $1 0
    elif [ "$rev" = "" ]; then
        /usr/local/bin/gpio -g write $1 1
    fi
}
gpio_off(){
    rev=$(sqlite3 $dir/dbf/nettemp.db "SELECT rev FROM gpio WHERE gpio='$1'")
    /usr/local/bin/gpio -g mode $1 output
    if [ "$rev" = "on" ]; then 
        /usr/local/bin/gpio -g write $1 1
    elif [ "$rev" = "" ]; then 
	/usr/local/bin/gpio -g write $1 0
    fi
}

if [ -z "$gpio_list" ]; then
	gpio_list=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM gpio")
fi


for gpio in $gpio_list; do 
	mode=$(sqlite3 $dir/dbf/nettemp.db "SELECT mode FROM gpio WHERE gpio='$gpio'")

if [ "$mode" = "time" ]; then
    source $(dirname $0)/time
elif [ "$mode" = "temp" ]; then
    source $(dirname $0)/temp
elif [ "$mode" = "trigger" ]; then
    source $(dirname $0)/trigger

fi
done

#onoff=`sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM settings"`
#if [ "$onoff" = "on" ];then
    
#    echo "on"
    
#else
#    echo "GPIO OFF"
#fi


