#! /bin/bash -x

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=$(date +%y%m%d-%H%M)

function buzzer {
buzzer=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM gpio where mode='buzzer'")
if [ -n "$buzzer" ]
	    then
		/usr/local/bin/gpio -g write $buzzer 1 &&  /usr/local/bin/gpio -g write $buzzer 0
	fi
}

gpio_on(){
    rev=$(sqlite3 $dir/dbf/nettemp.db "SELECT rev FROM gpio WHERE gpio='$1'")
    $dir/modules/gpio/timestamp $1 1
    /usr/local/bin/gpio -g mode $1 output
    if [ "$rev" = "on" ]; then
	/usr/local/bin/gpio -g write $1 0
	buzzer	
    elif [ "$rev" = "" ]; then
        /usr/local/bin/gpio -g write $1 1
	buzzer
    fi
}
gpio_off(){
    rev=$(sqlite3 $dir/dbf/nettemp.db "SELECT rev FROM gpio WHERE gpio='$1'")
    $dir/modules/gpio/timestamp $1 0
    /usr/local/bin/gpio -g mode $1 output
    if [ "$rev" = "on" ]; then 
        /usr/local/bin/gpio -g write $1 1
    elif [ "$rev" = "" ]; then 
	/usr/local/bin/gpio -g write $1 0
    fi
}

if [ -z "$gpio_list" ]; then
	gpio_list=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM gpio")
fi


for gpio in $gpio_list; do 
	mode=$(sqlite3 $dir/dbf/nettemp.db "SELECT mode FROM gpio WHERE gpio='$gpio'")

if [ "$mode" = "time" ]; then
    source $(dirname $0)/time
elif [ "$mode" = "temp" ]; then
    source $(dirname $0)/temp
elif [ "$mode" = "simple" ]; then
    source $(dirname $0)/simple
elif [ "$mode" = "trigger" ]; then
    source $(dirname $0)/trigger
elif [ "$mode" = "control" ]; then
    source $(dirname $0)/control
elif [ "$mode" = "day" ]; then
    source $(dirname $0)/day
elif [ "$mode" = "week" ]; then
    source $(dirname $0)/week
fi


done



