#! /bin/bash

function log(){
    echo "$date, F: $i, GPIO $gpio, rev:$rev, state: ${!state}, status: $logstatus, day: $day, Sensor1: ${!sensor_temp}, Set value: ${!temp_temp}, Hyst: ${!temp_hyst}, Max: ${!hyst}, OP: ${!temp_op}" >> $dir/tmp/gpio_$gpio\_log.txt
    echo "$date, F: $i, GPIO $gpio, rev:$rev, state: ${!state}, status: $logstatus, day: $day, Sensor1: ${!sensor_temp}, Set value: ${!temp_temp}, Hyst: ${!temp_hyst}, Max: ${!hyst}, OP: ${!temp_op}"
}

function check(){
if [[ -z "${!temp_hyst}" ]]; then
    if [[ "$l" = "1" ]]; then
        if [[ "${!temp_onoff}" = "on" ]]; then
            offon=on
	    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET status='ON' WHERE gpio='$gpio'"
	    logstatus="ON"
        else
            offon=off
	    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET status='OFF' WHERE gpio='$gpio'"
	    logstatus="OFF"
        fi
    elif [[ "$l" = "0" ]]; then
        if [ "${!temp_onoff}" = "on" ];then
            offon=off
	    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET status='OFF' WHERE gpio='$gpio'"
	    logstatus="OFF"
        else
            offon=on
	    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET status='ON' WHERE gpio='$gpio'"
	    logstatus="ON"
        fi
    fi
fi
}


function hyst() {
if [[ -n ${!temp_hyst} ]]; then
    if [[ "$h" == "0" ]] && [[ $l == "1" ]]; then
	offon=on
	sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET status='ON' WHERE gpio='$gpio'"
	sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET state='ON' WHERE gpio='$gpio'"
	logstatus="ON start"
	echo "debug 1"
  elif [[ "$h" == "0" ]] && [[ $l == "0" ]] && [[ "${!state}" != "OFF" ]]; then
	offon=on
	sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET status='ON' WHERE gpio='$gpio'"
	sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET state='ON' WHERE gpio='$gpio'"
	logstatus="ON running"
	echo "debug 2"
  elif [[ "$h" == "1" ]] && [[ $l == "0" ]]; then
	offon=off
	sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET status='OFF' WHERE gpio='$gpio'"
	sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET state='OFF' WHERE gpio='$gpio'"
	logstatus="OFF go down"
	echo "debug 3"
  elif [[ "$h" == "0" ]] && [[ $l == "0" ]] && [[ "${!state}" == "OFF" ]]; then
	offon=off
	logstatus="OFF still ging down"
	echo "debug 4"
    fi
fi
}



temp_run=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT temp_run FROM gpio WHERE gpio='$gpio'")
day_run=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT day_run FROM gpio WHERE gpio='$gpio'")
fnum=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT fnum FROM gpio WHERE gpio='$gpio'");

if [ "$temp_run" = "on" ]
    then

function temp {
for i in $(seq 1 $fnum);
    do 

declare temp_onoff$i=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT temp_onoff$i FROM gpio WHERE gpio='$gpio'"`
temp_onoff=temp_onoff$i

declare temp_temp$i=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT temp_temp$i FROM gpio WHERE gpio='$gpio'"`
temp_temp=temp_temp$i

declare temp_sensor$i=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT temp_sensor$i FROM gpio WHERE gpio='$gpio'"`
temp_sensor=temp_sensor$i

declare sensor_temp$i=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT tmp+adj FROM sensors WHERE id='${!temp_sensor}'"`
sensor_temp=sensor_temp$i

declare temp_sensor_diff$i=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT temp_sensor_diff$i FROM gpio WHERE gpio='$gpio'"`
temp_sensor_diff=temp_sensor_diff$i

declare diff_temp$i=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT tmp FROM sensors WHERE id='${!temp_sensor_diff}'"`
diff_temp=diff_temp$i

declare sensor_name$i=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT name FROM sensors WHERE id='${!temp_sensor}'"`
sensor_name=sensor_name$i

declare temp_op$i=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT temp_op$i FROM gpio WHERE gpio='$gpio'"`
temp_op=temp_op$i

declare status$i=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT status FROM gpio WHERE gpio='$gpio'"`
status=status$i

declare state$i=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT state FROM gpio WHERE gpio='$gpio'"`
state=state$i


declare temp_hyst$i=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT temp_hyst$i FROM gpio WHERE gpio='$gpio'"`
temp_hyst=temp_hyst$i
# hyst temp1 
declare t1h$i=$(echo ${!temp_temp} ${!temp_hyst} |awk '{ sum = $1 + $2; print sum }')
hyst=t1h$i
# hyst sensor2
declare s2h$i=$(echo ${!diff_temp} ${!temp_hyst} |awk '{ sum = $1 + $2; print sum }')
if [ -n "${!diff_temp}" ]; then
    temp_temp=$diff_temp
    hyst=s2h$i
fi





if [ -n "${!temp_temp}" ] && [[ "${!sensor_temp}" != "0" ]] && [[ -n "${!sensor_temp}" ]]; then

if [[ "${!temp_op}" = "gt" ]]; then
    l=$(echo ${!sensor_temp} ${!temp_temp} | awk '{if ($1 > $2) print 1; else print 0 }')
    h=$(echo ${!sensor_temp} ${!hyst} | awk '{if ($1 >= $2) print 1; else print 0 }')
    hyst
    check
fi

if [[ "${!temp_op}" = "ge" ]]; then
    l=$(echo ${!sensor_temp} ${!temp_temp} | awk '{if ($1 >= $2) print 1; else print 0 }') 
    h=$(echo ${!sensor_temp} ${!hyst} | awk '{if ($1 >= $2) print 1; else print 0 }')
    hyst
    check
fi

if [[ "${!temp_op}" = "le" ]]; then
    l=$(echo ${!sensor_temp} ${!temp_temp} | awk '{if ($1 <= $2) print 1; else print 0 }') 
    h=$(echo ${!sensor_temp} ${!hyst} | awk '{if ($1 >= $2) print 1; else print 0 }')
    hyst
    check
fi

if [[ "${!temp_op}" = "lt" ]]; then
    l=$(echo ${!sensor_temp} ${!temp_temp} | awk '{if ($1 < $2) print 1; else print 0 }')
    h=$(echo ${!sensor_temp} ${!hyst} | awk '{if ($1 >= $2) print 1; else print 0 }')
    hyst
    check
fi

log

unset temp_onoff
unset temp_temp
unset temp_sensor
unset sensor_temp
unset sensor_name
unset temp_op
unset temp_hyst
unset hyst
unset status
unset state
unset logstatus

else
    echo "$date, ERROR in value or Sensor1" >> $dir/tmp/gpio_$gpio\_log.txt
    echo "$date, ERROR in value or Sensor1"
    break
fi
done
}


function day {
if [ "$day_run" == "on" ]
    then
    day=$($dir/modules/gpio/day $gpio)
	if [ "$day" == "on" ]
	    then
		day=on #logs
		temp #function
	else
	    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET status='OFF' WHERE gpio='$gpio'"
	    offon=off #off because day=off
	    day=off #logs
	fi
else
    day=off #logs
    temp
fi
}

### main
    day
    gpio_$offon #set state after check all function
    echo "$date, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio)" >> $dir/tmp/gpio_$gpio\_log.txt
    echo "$date, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio)"
fi
