#! /bin/bash

# version 1

function hyst() {
if [[ -n "${!temp_hyst}" ]]; then
    if [[ $h == "1" ]]; then
	gpio_off
	sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='OFF, ${!hyst} reached' WHERE gpio='$gpio'"
	echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, Hyst:${!temp_hyst}, Max ${!hyst} reached wait for <= ${!temp_temp}, status OFF, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), CONTINUE."
	continue
    elif [[ "$h" == "0" &&  "$gt" == "0" || $ge == "0" || $le == "0" || $lt == "0" ]]; then
	sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='ON, wait for ${!hyst}' WHERE gpio='$gpio'"
	echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, Hyst:${!temp_hyst}, Min ${!temp_temp} reached wait for ${!hyst},status ON, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), EXIT."
	exit 0
    fi
fi
}




temp_run=$(sqlite3 $dir/dbf/nettemp.db "SELECT temp_run FROM gpio WHERE gpio='$gpio'")
day_run=$(sqlite3 $dir/dbf/nettemp.db "SELECT day_run FROM gpio WHERE gpio='$gpio'")
week_run=$(sqlite3 $dir/dbf/nettemp.db "SELECT week_run FROM gpio WHERE gpio='$gpio'")
tempnum=$(sqlite3 $dir/dbf/nettemp.db "SELECT tempnum FROM settings");

if [ "$temp_run" = "on" ]
    then

function temp {
for i in $(seq 1 $tempnum);
    do 

declare temp_onoff$i=`sqlite3 $dir/dbf/nettemp.db "SELECT temp_onoff$i FROM gpio WHERE gpio='$gpio'"`
temp_onoff=temp_onoff$i

declare temp_temp$i=`sqlite3 $dir/dbf/nettemp.db "SELECT temp_temp$i FROM gpio WHERE gpio='$gpio'"`
temp_temp=temp_temp$i

declare temp_sensor$i=`sqlite3 $dir/dbf/nettemp.db "SELECT temp_sensor$i FROM gpio WHERE gpio='$gpio'"`
temp_sensor=temp_sensor$i

declare sensor_temp$i=`sqlite3 $dir/dbf/nettemp.db "SELECT tmp+adj FROM sensors WHERE id='${!temp_sensor}'"`
sensor_temp=sensor_temp$i

declare temp_sensor_diff$i=`sqlite3 $dir/dbf/nettemp.db "SELECT temp_sensor_diff$i FROM gpio WHERE gpio='$gpio'"`
temp_sensor_diff=temp_sensor_diff$i

declare diff_temp$i=`sqlite3 $dir/dbf/nettemp.db "SELECT tmp FROM sensors WHERE id='${!temp_sensor_diff}'"`
diff_temp=diff_temp$i

declare sensor_name$i=`sqlite3 $dir/dbf/nettemp.db "SELECT name FROM sensors WHERE id='${!temp_sensor}'"`
sensor_name=sensor_name$i

declare temp_op$i=`sqlite3 $dir/dbf/nettemp.db "SELECT temp_op$i FROM gpio WHERE gpio='$gpio'"`
temp_op=temp_op$i

declare temp_hyst$i=`sqlite3 $dir/dbf/nettemp.db "SELECT temp_hyst$i FROM gpio WHERE gpio='$gpio'"`
temp_hyst=temp_hyst$i
# hyst temp1 
declare t1h$i=$(echo ${!temp_temp} ${!temp_hyst} |awk '{ sum = $1 + $2; print sum }')
hyst=t1h$i
# hyst sensor2
declare s2h$i=$(echo ${!diff_temp} ${!temp_hyst} |awk '{ sum = $1 + $2; print sum }')
if [ -n "${!diff_temp}" ]; then
    temp_temp=$diff_temp
    hyst=s2h$i
fi

#echo Temp ${!temp_temp}
#echo Sensor1 ${!sensor_temp}


if [ -n "${!temp_temp}" ] || [[ "${!sensor_temp}" != "error" ]] &&  echo ${!sensor_temp} | grep -o -q '[0-9]*'; then

if [ "${!temp_op}" = "gt" ]; then
gt=$(echo ${!sensor_temp} ${!temp_temp} | awk '{if ($1 > $2) print 1; else print 0 }')
h=$(echo ${!sensor_temp} ${!hyst} | awk '{if ($1 >= $2) print 1; else print 0 }')
hyst
    if [ "$gt" = "1" ];then
        if [ "${!temp_onoff}" = "on" ];then
            gpio_on
	    #echo "${!sensor_name} ${!sensor_temp} C > ${!temp_temp} C - gpio ON debug 1"
    	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status on, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 1"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} > ${!temp_temp} on' WHERE gpio='$gpio'"
        else
            gpio_off
	    #echo "${!sensor_name} ${!sensor_temp} C > ${!temp_temp} C - gpio OFF debug 2"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status off, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 2"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} > ${!temp_temp} off' WHERE gpio='$gpio'"
        fi
    else
        if [ "${!temp_onoff}" = "on" ];then
            gpio_off
            #echo "${!sensor_name} ${!sensor_temp} C < ${!temp_temp} C - gpio OFF debug 3"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status off, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 3"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} < ${!temp_temp} off' WHERE gpio='$gpio'"
        else
            gpio_on
	    #echo "${!sensor_name} ${!sensor_temp} C < ${!temp_temp} C - gpio ON debug 4"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status on, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 4"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} < ${!temp_temp} on' WHERE gpio='$gpio'"
        fi
    fi
    
fi
if [ "${!temp_op}" = "ge" ]; then
ge=$(echo ${!sensor_temp} ${!temp_temp} | awk '{if ($1 >= $2) print 1; else print 0 }') 
h=$(echo ${!sensor_temp} ${!hyst} | awk '{if ($1 >= $2) print 1; else print 0 }')
hyst

    if [ "$ge" = "1" ];then
        if [ "${!temp_onoff}" = "on" ];then
            gpio_on
	    #echo "${!sensor_name} ${!sensor_temp} C >= ${!temp_temp} C - gpio ON debug 5"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status on, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 6"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} >= ${!temp_temp} on' WHERE gpio='$gpio'"
        else
            gpio_off
	    #echo "${!sensor_name} ${!sensor_temp} C >= ${!temp_temp} C - gpio OFF debug 6"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status off, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 6"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} >= ${!temp_temp} off' WHERE gpio='$gpio'"
        fi
    else
        if [ "${!temp_onoff}" = "on" ];then
            gpio_off
            #echo "${!sensor_name} ${!sensor_temp} C <= ${!temp_temp} C - gpio OFF  debug 7"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status off, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 7"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} <= ${!temp_temp} off' WHERE gpio='$gpio'"
        else
            gpio_on
	    #echo "${!sensor_name} ${!sensor_temp} C <= ${!temp_temp} C - gpio ON  debug 8"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status on, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 8"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} <= ${!temp_temp} on' WHERE gpio='$gpio'"
        fi
    fi
        fi
if [ "${!temp_op}" = "le" ]; then
le=$(echo ${!sensor_temp} ${!temp_temp} | awk '{if ($1 <= $2) print 1; else print 0 }') 
h=$(echo ${!sensor_temp} ${!hyst} | awk '{if ($1 >= $2) print 1; else print 0 }')
hyst

    if [ "$le" = "1" ];then
        if [ "${!temp_onoff}" = "on" ];then
            gpio_on
	    #echo "${!sensor_name} ${!sensor_temp} C <= ${!temp_temp} C - gpio ON  debug 9"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status on, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 9"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} <= ${!temp_temp} on' WHERE gpio='$gpio'"
        else
            gpio_off
	    #echo "${!sensor_name} ${!sensor_temp} C <= ${!temp_temp} C - gpio OFF debug 10"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status off, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 10"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} <= ${!temp_temp} off' WHERE gpio='$gpio'"
        fi
    else
        if [ "${!temp_onoff}" = "on" ];then
            gpio_off
            #echo "${!sensor_name} ${!sensor_temp} C >= ${!temp_temp} C - gpio OFF debug 11"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status off, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 11"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} <= ${!temp_temp} off' WHERE gpio='$gpio'"
        else
            gpio_on
	    #echo "${!sensor_name} ${!sensor_temp} C >= to ${temp_temp} C - gpio ON debug 12"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status on, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 12"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} >= ${!temp_temp} on' WHERE gpio='$gpio'"
        fi
    fi
fi

if [ "${!temp_op}" = "lt" ]; then
lt=$(echo ${!sensor_temp} ${!temp_temp} | awk '{if ($1 < $2) print 1; else print 0 }')
h=$(echo ${!sensor_temp} ${!hyst} | awk '{if ($1 >= $2) print 1; else print 0 }')
hyst

    if [ "$lt" = "1" ];then
        if [ "${!temp_onoff}" = "on" ];then
            gpio_on
	    #echo "${!sensor_name} ${!sensor_temp} C < ${!temp_temp} C - gpio ON debug 13"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status on, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 13"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} < ${!temp_temp} on' WHERE gpio='$gpio'"
        else
            gpio_off
	    #echo "${!sensor_name} ${!sensor_temp} C < ${!temp_temp} C - gpio OFF debug 14"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status off, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 14"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} < ${!temp_temp} off' WHERE gpio='$gpio'"
        fi
    else
        if [ "${!temp_onoff}" = "on" ];then
            gpio_off
            #echo "${!sensor_name} ${!sensor_temp} C > ${!temp_temp} C - gpio OFF debug 15"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status off, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 15"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} > ${!temp_temp} off' WHERE gpio='$gpio'"
        else
            gpio_on
	    #echo "${!sensor_name} ${!sensor_temp} C > ${!temp_temp} C - gpio ON debug 16"
	    echo "$date day: $day, Sensor1:${!sensor_temp}, Set temp ${!temp_temp}, status on, GPIO $gpio $(/usr/local/bin/gpio -g read $gpio), debug 16"
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='${!sensor_name} ${!sensor_temp} > ${!temp_temp} on' WHERE gpio='$gpio'"
        fi
    fi
fi

unset temp_onoff
unset temp_temp
unset temp_sensor
unset sensor_temp
unset sensor_name
unset temp_op
unset temp_hyst
unset hyst

else
    echo "error: no input temp"
    exit 0
fi
done
}


function day {
if [ "$day_run" == "on" ]
    then
    day=$($dir/modules/gpio/day $gpio)
	if [ "$day" == "on" ]
	    then 
	    day=on
	    temp #function
	else
	    gpio_off
	    day=off
	fi
else
    day=off
    temp #function
fi
}

###main

day

fi #last 
