#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=$(date +%y%m%d-%H%M)

gpio="$1"
onoff="$2"

if [ -e $dir/db/gonoff_$gpio ]; then
    sqlite3 $dir/db/gonoff_$gpio.sql "INSERT OR IGNORE INTO def (value) VALUES ('$2');"
else
    sqlite3 $dir/db/gonoff_$gpio.sql "CREATE TABLE def (time DATE DEFAULT (datetime('now','localtime')), value INTEEGER);"
    sqlite3 $dir/db/gonoff_$gpio.sql "INSERT OR IGNORE INTO def (value) VALUES ('$2');"
fi
