#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=$(date +%y%m%d-%H%M)

trigger_run=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT trigger_run FROM gpio WHERE gpio='$gpio'")
if [ "$trigger_run" = "on" ]; then
    if pgrep -a trigger_proc | grep -q $gpio; then 
	echo "trigger_proc $gpio already running" && exit; 
	else 
	    $dir/modules/gpio/trigger_proc $gpio &
    fi
fi
