#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=$(date +%y%m%d-%H%M)

gl="$1"

sudo /bin/kill -9 `pgrep -l -f trigger_proc |grep $gl | awk '{print $1}'`

out=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio,rev FROM gpio where mode='triggerout' AND tout$gl='on'")
led=$(sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM gpio where mode='led'")
/usr/local/bin/gpio -g write $led 0

function close {
        for i in $out; do
	g=$(echo $i|awk -F"|" '{ print $1}')
	r=$(echo $i|awk -F"|" '{ print $2}')
	/usr/local/bin/gpio -g mode $g out
	    if [ "$r" = "on" ]; then
	    /usr/local/bin/gpio -g write $g 1
	    else
	    /usr/local/bin/gpio -g write $g 0
	    fi
        done
}

close

sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET trigger_run='', status='BUTTON OFF' WHERE gpio='$gl'"

fil=$(ls $dir/tmp/mail/hour/ |grep alarm$gl)
for i in $fil; do
    rm -rf $dir/tmp/mail/hour/$i
done
