#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
if [ -z "$gpio" ]
    then
	gpio="$1"
	mode="single"
fi
week_run=$(sqlite3 $dir/dbf/nettemp.db "SELECT week_run FROM gpio WHERE gpio='$gpio'")
if [ "$week_run" = "on" ]; then
	Mon=$(sqlite3 $dir/dbf/nettemp.db "SELECT week_Mon FROM gpio WHERE gpio='$gpio'")
	Thu=$(sqlite3 $dir/dbf/nettemp.db "SELECT week_Thu FROM gpio WHERE gpio='$gpio'")
	Wed=$(sqlite3 $dir/dbf/nettemp.db "SELECT week_Wed FROM gpio WHERE gpio='$gpio'")
	Thu=$(sqlite3 $dir/dbf/nettemp.db "SELECT week_Thu FROM gpio WHERE gpio='$gpio'")
	Fri=$(sqlite3 $dir/dbf/nettemp.db "SELECT week_Fri FROM gpio WHERE gpio='$gpio'")
	Sat=$(sqlite3 $dir/dbf/nettemp.db "SELECT week_Sat FROM gpio WHERE gpio='$gpio'")
	Sun=$(sqlite3 $dir/dbf/nettemp.db "SELECT week_Sun FROM gpio WHERE gpio='$gpio'")

	date2=$(date '+%a')

for i in Mon Tue Wed Thu Fri Sat Sun
    do 
	if [ "$i" == "$date2" ]
	    then
		if [ "${!i}" == "on" ]
		    then
			onoff="on"
		    break
		fi
	    else 
		onoff="off"
	fi
done



    if [ $mode == "single" ]
	then
	    echo $onoff
    else
	day_run=$(sqlite3 $dir/dbf/nettemp.db "SELECT day_run FROM gpio WHERE gpio='$gpio'")
	if [ "$day_run" == "on" ]
	    then
		day=$($dir/modules/gpio/day $gpio)
		if [ "$day" == "on" ]
		    then
			gpio_$onoff $gpio
			echo $onoff
			sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='$onoff - week' WHERE gpio='$gpio'"
		else
		    gpio_off $gpio
		    echo off
		    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='off - week' WHERE gpio='$gpio'"
		fi
	else
	    gpio_$onoff $gpio
	    echo $onoff
	    sqlite3 $dir/dbf/nettemp.db "UPDATE gpio SET status='$onoff - week' WHERE gpio='$gpio'"
	fi




    fi

fi

