#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
if [ -z "$gpio" ]
    then
	gpio="$1"
	mode="single"
fi
if week_run=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT week_run FROM gpio WHERE gpio='$gpio'")
then    
if [ "$week_run" = "on" ]; then
	date2=$(LC_ALL=en_EN.utf8 date '+%a')
	if i=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT week_$date2 FROM gpio WHERE gpio='$gpio'")
    then
	   if [ "$i" == "on" ]
	    then
		onoff="on"
	    else 
		onoff="off"
	   fi
    fi

    if [ $mode == "single" ]
	then
	    echo $onoff
    else
       if day_run=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT day_run FROM gpio WHERE gpio='$gpio'")
        then
	       if [ "$day_run" == "on" ]
	       then
                day=$($dir/modules/gpio/day $gpio)
		          if [ "$day" == "on" ]
		          then
                     gpio_$onoff $gpio
			         echo $onoff
			         sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET status='$onoff - week' WHERE gpio='$gpio'"
                   else
		             gpio_off $gpio
		             echo off
		             sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET status='off - week' WHERE gpio='$gpio'"
		          fi
	       else
	           gpio_$onoff $gpio
	           echo $onoff
	           sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE gpio SET status='$onoff - week' WHERE gpio='$gpio'"
	       fi
        fi
    fi
fi
fi