#!/usr/bin/expect -f

log_file -a /var/www/nettemp/tmp/call.txt
set timeout -1
set dev [lindex $argv 0]

spawn socat -s - $dev,raw,echo=0,crlf,nonblock

sleep 10
send "AT\r"
send "AT+CLIP=1\r"

expect {
    -re {"([^"])*"} {
    set string $expect_out(0,string)
    send "AT+CHUP\r"
    exec /var/www/nettemp/modules/call/check $string
    exp_continue
    }
}
