#!/bin/bash

DATE=`date +%y%m%d-%H%M`
LOG="/var/www/nettemp/tmp/incoming_calls.txt"
dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=$(date +%y%m%d-%H%)

    number=$(echo ${1} |sed 's/"//' |sed 's/"//' |sed 's/+//')

    date1=$(LC_ALL=en_EN.utf8 date '+%a')
    date2=$(date +%H%M)

    name=$(sqlite3 $dir/dbf/nettemp.db "SELECT at FROM users WHERE tel='$number'")
    day=$(sqlite3 $dir/dbf/nettemp.db "SELECT $date1 FROM access_time WHERE name='$name'")
    stime=$(sqlite3 $dir/dbf/nettemp.db "SELECT stime FROM access_time WHERE name='$name'")
    etime=$(sqlite3 $dir/dbf/nettemp.db "SELECT etime FROM access_time WHERE name='$name'")

if [[ "$day" == "$date1" && "$date2" > "$stime" && "$date2" < "$etime" ]]; then
    gpio=$(sqlite3 $dir/dbf/nettemp.db "SELECT ctr FROM users WHERE tel='$number'")
    /usr/local/bin/gpio -g mode $gpio output
    /usr/local/bin/gpio -g write $gpio 1
    sleep 2
    /usr/local/bin/gpio -g write $gpio 0
    echo "${DATE} Call Allow $number" >> ${LOG}
else 
    echo "${DATE} Call Deny $number" >> ${LOG}
fi

exit 0

