#! /bin/bash -x

user="$1"
mail="$2"
days="$3"

if [[ ! -n "$user" || ! -n "$mail" ]]; then
    echo "No user or email or days"
    echo "ex. client test test@test.com 365"
    exit 0
fi

cd /usr/local/etc/raddb/certs
sudo mkdir -p users/$user

clientfile=client.cnf
pass=$(sudo openssl rand -base64 6 | tr -dc 'a-zA-Z0-9' )

if [ -n "$days" ]; then
    sudo sed -i -e '/\[ CA_default \]/,/^\[/ s/.*default_days.*/default_days		= '$days'/' $clientfile
else
    days="365"
fi

sudo sed -i -e '/\[ req \]/,/^\[/ s/.*input_password.*/input_password		= '$pass'/' $clientfile
sudo sed -i -e '/\[ req \]/,/^\[/ s/.*output_password.*/output_password	= '$pass'/' $clientfile
sudo sed -i -e '/\[client\]/,/^\[/ s/.*emailAddress.*/emailAddress		= '$mail'/' $clientfile
sudo sed -i -e '/\[client\]/,/^\[/ s/.*commonName.*/commonName		= '$user'/' $clientfile

sudo make client

sudo openssl pkcs12 -export -in client.crt -inkey client.key -out client.p12  -passin pass:$pass -passout pass:$pass -name "RADIUS Nettemp"


sudo mv client.p12 users/$user/export.p12
sudo mv client.pem users/$user/$user.pem
sudo rm $mail.pem
sudo touch users/$user/pass.txt
sudo chmod g+w users/$user/pass.txt
sudo echo "$pass" > users/$user/pass.txt

if [ -s users/$user/export.p12 ]; then
    /var/www/nettemp/modules/mail/mail_test $mail "WiFi certificate from RADIUS "  "This is Your certificate file and export password, valid $days days: $pass" users/$user/export.p12
else
    echo "empty export"
fi

sudo pkill radiusd
sudo radiusd



