#! /bin/bash

cd /usr/local/etc/raddb/certs

name="$1"
user="users/$name/export.pem"


if [[ ! -n "$name" ]]; then
    echo "No name"
exit 0 
fi


capass=$(grep output_password ca.cnf | sed 's/.*=//;s/^ *//')

sudo openssl ca -revoke $user -keyfile ca.key -key $capass -cert ca.pem -config ./ca.cnf
sudo openssl ca -gencrl -keyfile ca.key -key $capass -cert ca.pem -out CRL/crl.pem -config ./ca.cnf
sudo c_rehash CA/

sudo rm -rf users/$name
sudo pkill -f radiusd
sudo radiusd
