#! /bin/bash -x

user="nettempnotifications@gmail.com"

from="nettemp device"
reci="test@techfreak.pl"
subject="Testowy mail"
body="blablabla"

host="smtp.gmail.com"
port="587"



(echo "From: $from"; echo "To: $reci"; echo "Subject: $subject" ;echo -e "$body";) | msmtp \
--read-envelope-from \
--host=$host --port=$port --auth=on --user=$user \
--tls=on --tls-starttls=on --tls-certcheck=off \
--timeout=10 -t $reci





