#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=$(date +%y%m%d-%H%M)
dirs=$dir/tmp/mail

get_mail=`sqlite3 $dir/dbf/nettemp.db "SELECT mail FROM recipient WHERE mail_alarm='yes'" | awk '{ printf " "$1 }'`
host=`sqlite3 $dir/dbf/nettemp.db "SELECT host FROM mail_settings"`
port=`sqlite3 $dir/dbf/nettemp.db "SELECT port FROM mail_settings"`
user=`sqlite3 $dir/dbf/nettemp.db "SELECT user FROM mail_settings"`
password=`sqlite3 $dir/dbf/nettemp.db "SELECT password FROM mail_settings"`
address=`sqlite3 $dir/dbf/nettemp.db "SELECT address FROM mail_settings"`
auth=`sqlite3 $dir/dbf/nettemp.db "SELECT auth FROM mail_settings"`
tls=`sqlite3 $dir/dbf/nettemp.db "SELECT tls FROM mail_settings"`
tlscheck=`sqlite3 $dir/dbf/nettemp.db "SELECT tlscheck FROM mail_settings"`

function send {
cat $1 | msmtp --maildomain=default --read-envelope-from --host=$host --port=$port --auth=$auth --user=$user \
            --passwordeval="sqlite3 $dir/dbf/nettemp.db 'SELECT password FROM mail_settings'"  \
            --tls=$tls --tls-starttls=$tls --tls-certcheck=$tlscheck \
            --timeout=10 -t $get_mail
}


for file in $(ls $dirs/hour |grep mail)
    do
	send $dirs/hour/$file
done