#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M`


dirs=$dir/tmp/mail
mkdir -p $dirs/hour
dirs2=$dirs/hour
date2=`date +%Y%m%d-%H:%M`
get_mail=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT mail FROM users WHERE maila='yes'" | awk '{ printf " "$1 }'`
user=$(sudo cat /etc/msmtprc |grep user | awk '{ print $2 }')

function file {
source $(dirname $0)/mail_body
chmod 777 $2
}

if name=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT name FROM hosts WHERE status='error' OR last='0' AND alarm='on'")
    then
	for name in $name
	do  
		minute=$dirs/$name.mail
		hour=$dirs2/$name.mail
	   if [ ! -f $hour ]
		then
		    file "<td>$name</td><td>0</td><td>$date</td><td bgcolor="#FF0000">Lost connection</td>" $minute
	    else
		    file "<td>$name</td><td>0</td><td>$date</td><td bgcolor="#FF0000">Lost connection</td>" $hour
	    fi

	done
fi

unset name

if name=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT name FROM hosts WHERE status='ok'")
    then
	for name in $name
	do
		minute=$dirs/$name.mail
		hour=$dirs2/$name.mail
	   if [ -f "$hour" ]
		then
		    file "<td>$name</td><td></td><td>$date</td><td bgcolor="#00FF00">RECOVERY</td>" $minute
	    fi
	done
	
fi











