#! /bin/bash -x

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M`

reci=$1
date2=`date +%Y-%m-%d-%H:%M`
get_mail=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT mail FROM recipient WHERE mail_alarm='yes'" | awk '{ printf " "$1 }'`

host=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT host FROM mail_settings"`
port=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT port FROM mail_settings"`
user=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT user FROM mail_settings"`
password=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT password FROM mail_settings"`
address=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT address FROM mail_settings"`
auth=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT auth FROM mail_settings"`
tls=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT tls FROM mail_settings"`
tlscheck=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT tlscheck FROM mail_settings"`

subject=$2
body=$3



(echo "From: nettemp device <$address> "; echo "To: <$reci>"; echo "Subject: $subject"; echo ""; echo -e "$body"; uuencode  $4 $4 && uuencode $5 $5) | msmtp \
-f $address \
--host=$host --port=$port --auth=$auth --user=$user \
--passwordeval="sqlite3 -cmd \".timeout 2000\" $dir/dbf/nettemp.db 'SELECT password FROM mail_settings'"  \
--tls=$tls --tls-starttls=$tls --tls-certcheck=$tlscheck \
--timeout=10 -t $reci 


echo "$date mail_test - send test mail to $reci" >> $dir/tmp/log.txt




