#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M`


onoff=`sqlite3 $dir/dbf/nettemp.db "SELECT mail FROM settings"`

if [ "$onoff" == "on" ]; then

dirs=$dir/tmp/mail
mkdir -p $dirs/hour
date2=`date +%Y%m%d-%H:%M`
get_mail=`sqlite3 $dir/dbf/nettemp.db "SELECT mail FROM recipient WHERE mail_alarm='yes'" | awk '{ printf " "$1 }'`
user=`sqlite3 $dir/dbf/nettemp.db "SELECT user FROM mail_settings"`

function file {
> $2
echo "From: Nettemp Device <$user>" > $2
echo "To: $get_mail" >> $2
echo "Subject: Notification from nettemp" >> $2
echo "" >> $2
echo "This is notification from nettemp" >> $2
echo "" >> $2
echo "$1" >> $2
echo "" >> $2
echo Go to http://$(hostname -I | cut -d' ' -f1) >> $2
chmod 777 $2
}

names=() #array for remove old files

if alarms=$(sqlite3 $dir/dbf/nettemp.db "SELECT * FROM sensors WHERE alarm='on'"| sed 's/ /_/g')
    then
    for line in $alarms
    do
	name=`echo $line | awk 'BEGIN {FS="|"}{print $2}'`
        tmp=`echo $line | awk 'BEGIN {FS="|"}{print $4}'`
	tmp_min=`echo $line | awk 'BEGIN {FS="|"}{print $5}'`
	tmp_max=`echo $line | awk 'BEGIN {FS="|"}{print $6}'`
	plik=$dirs/$name.mail
	plik2=$dirs/hour/$name.mail
	
	if [ "$tmp" == "error" ] &&  error=$(sqlite3 $dir/dbf/nettemp.db "SELECT error FROM mail_settings WHERE id='1'")
	    then
		if [ ! -f "$plik2" ] && [ "$error" == "on" ]
		    then
			echo NEW ERROR
			file "Error in $name" $plik
		fi
	elif [ -n "$tmp_max" ] || [ -n "$tmp_min" ] 
	    then
    		cr_ge=$(echo $tmp $tmp_max | awk '{if ($1 > $2) print 1; else print 0 }')
    		cr_le=$(echo $tmp $tmp_min | awk '{if ($1 < $2) print 1; else print 0 }')
            	    if  [ "$cr_ge" == "1" ] && [ -n "$tmp_max" ]
			then
			echo HIGH $name
			if [ ! -f "$plik2" ]
			    then
			    echo NEW MV
			    file "High value in: $name $tmp C" $plik
			else
            		    echo UPDATE
            		    file "High value in: $name $tmp C" $plik2
			fi
    		    elif [ "$cr_le" == "1" ] && [ -n "$tmp_min" ]
			then
			echo LOW $name
			if [ ! -f "$plik2" ]
			    then
			    echo NEW MV
			    file "Low value in: $name $tmp C" $plik
        	    else
			echo UPDATE
			file "Low value in: $name $tmp C" $plik2
		    fi
        else
	    if [ -f "$plik2" ]
		then
		    echo RECOVERY $name
		    file "Recovery: $name $tmp C" $plik
	    fi
        fi
    fi
    done
fi
else
	echo "mail off"
fi #last


