#! /bin/bash 

> $2
echo "From: Nettemp Device <$user>" > $2
echo "To: $get_mail" >> $2
echo "Subject: Notification from nettemp" >> $2
sed -i '$aContent-Type: text/html' $2
sed -i '' $2
sed -i '$aMIME-Version: 1.0' $2
sed -i '$a<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">' $2
sed -i '$a<html>' $2
sed -i '$a<head>' $2
sed -i '$a<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">' $2
sed -i '$a<style>* { margin: 0; padding: 0; } a {text-decoration: none;} th, td {  padding: 5px;} table, th, td { border: 1px solid black;  border-collapse: collapse;}' $2
sed -i '$a* {font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;}</style>' $2
sed -i '$a</head>' $2
sed -i '$a<body bgcolor="#ffffff" text="#000000">' $2
sed -i '$a<h4>Hi, this is notification from <a href="http://'$(hostname -I | cut -d' ' -f1)'">nettemp system.</a></br></h4><br>' $2
sed -i '$a<table border="1" style="">' $2
sed -i '$a<tr><th>Name</th><th>Value</th><th>Date</th><th>Status</th></tr><tr>' $2
echo "$1" >> $2
sed -i '$a</tr></table><br><br>' $2
sed -i '$a<a href="http://techfreak.pl/tag/nettemp"> <img src="http://techfreak.pl/wp-content/uploads/2012/12/nettemp.pl_.png" style="width:120px;height:40px;"></a><br>' $2
sed -i '$a</div>' $2
sed -i '$a</body>' $2
sed -i '$a</html>' $2

