#! /bin/bash -x

from="nettemp device"
reci="test@techfreak.pl"
subject="Testowy mail"
body="blablabla"

host="smtp.gmail.com"
port="587"
user="nettempnotifications@gmail.com"


(echo "From: $from"; echo "To: $reci"; echo "Subject: $subject" ;echo -e "$body";) | msmtp \
--read-envelope-from \
--host=$host --port=$port --auth=on --user=$user \
--tls=on --tls-starttls=on --tls-certcheck=on --tls-trust-file=/etc/ssl/certs/ca-certificates.crt  \
--timeout=10 -t $reci





