#! /bin/bash -x

dir=`pwd`
date=`date +%y%m%d-%H%M`


reci=$1
date2=`date +%Y-%m-%d-%H:%M`
get_mail=`sqlite3 $dir/dbf/nettemp.db "SELECT mail FROM recipient WHERE mail_alarm='yes'" | awk '{ printf " "$1 }'`

host=`sqlite3 $dir/dbf/nettemp.db "SELECT host FROM mail_settings"`
port=`sqlite3 $dir/dbf/nettemp.db "SELECT port FROM mail_settings"`
user=`sqlite3 $dir/dbf/nettemp.db "SELECT user FROM mail_settings"`
password=`sqlite3 $dir/dbf/nettemp.db "SELECT password FROM mail_settings"`
#address=`sqlite3 $dir/dbf/nettemp.db "SELECT address FROM mail_settings"`

subject=$2
body=$3

(echo "From: nettemp device"; echo "To: $reci"; echo "Subject: $subject"; echo -e "$body"; uuencode $4 $4 ) | msmtp \
--maildomain=nettemp.pl \
--read-envelope-from \
--host=$host --port=$port --auth=on --user=$user \
--passwordeval="sqlite3 $dir/dbf/nettemp.db 'SELECT password FROM mail_settings'"  \
--tls=on --tls-starttls=on --tls-certcheck=on --tls-trust-file=/etc/ssl/certs/ca-certificates.crt  \
--timeout=10 -t $reci


echo "$date mail_test - send test mail to $reci" >> $dir/tmp/log.txt




