#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M`
src=$(hostname)

array=($(sqlite3 $dir/dbf/nettemp.db "SELECT rom,tmp FROM sensors"))
cip=$(sqlite3 $dir/dbf/nettemp.db "SELECT client_ip FROM settings WHERE id='1'")
ckey=$(sqlite3 $dir/dbf/nettemp.db "SELECT client_key FROM settings WHERE id='1'")

for i in ${array[*]}
do
    rom=$(echo $i |awk -F"|" '{print $1}') 
    val=$(echo $i |awk -F"|" '{print $2}')
    #echo $rom $val
    rom=$src\_$rom
    curl --data "rom=$rom&value=$val&key=$ckey" http://$cip/receiver.php
done
