#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M`
src=$(hostname)

array=($(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT rom,tmp,type FROM sensors WHERE remote='on'"))
cip=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT client_ip FROM settings WHERE id='1'")
ckey=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT client_key FROM settings WHERE id='1'")
onoff=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT client_on FROM settings WHERE id='1'")

if [[ -n "$onoff" && -n "$cip" && -n "$ckey" ]]; then

for i in ${array[*]}
do
    rom=$(echo $i |awk -F"|" '{print $1}') 
    val=$(echo $i |awk -F"|" '{print $2}')
    type=$(echo $i |awk -F"|" '{print $3}')
    rom=remote_$src\_$rom
    curl --connect-timeout 3 -G "http://$cip/receiver.php" -d "rom=$rom&value=$val&key=$ckey&type=$type"
    #curl --data "rom=$rom&value=$val&key=$ckey" http://$cip/receiver.php #POST
done

else
    echo off
fi
