#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M`

if [ ! -e $dir/tmp/log.txt ]; then
touch $dir/tmp/log.txt
chmod 775 $dir/tmp/log.txt
chown root.www-data $dir/tmp/log.txt 
fi

#echo "$date temp_dev_read - read sensors" >> $dir/tmp/log.txt

db=`ls $dir/db/`
if [[ -z "$db" ]]; then 
echo "INFO: no sensors added"
exit
fi

php-cgi -f $dir/modules/sensors/other/raspberrypi_read.php
php-cgi -f $dir/modules/sensors/other/bananapi_read.php
php-cgi -f $dir/modules/sensors/1wire/1wire_gpio_i2c_read.php
php-cgi -f $dir/modules/sensors/i2c/i2c_read.php
php-cgi -f $dir/modules/sensors/1wire/1wire_serial_read.php

#1wire usb
$dir/modules/sensors/1wire/1wire_usb_read
# DHT11, 22 Adafruit
$dir/modules/sensors/GPIO/DHT/dht_read
#lmsensors
$dir/modules/sensors/lmsensors/lmsensors_read
# SNMP
$dir/modules/sensors/snmp/snmp_read
# wireless
$dir/modules/sensors/wireless/esp8266_read
#ups
$dir/modules/sensors/other/ups
#sdm120/sdm120c
$dir/modules/sensors/rs485/sdm120
#sdm630
php-cgi -f $dir/modules/sensors/rs485/sdm630.php
#orwe
$dir/modules/sensors/rs485/orwe
#HCS04
$dir/modules/sensors/GPIO/HCS04/read

#snmp server
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT tmp FROM sensors" | sed 's/$/:/' | sed '$s/.$//' |tr -d "\n" > $dir/tmp/results

#lcd
echo $(date "+%y.%m.%d %H:%M") > $dir/tmp/lcd
sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT name,tmp,type FROM sensors WHERE lcd='on' ORDER BY position ASC, id ASC" | sed 's/|/ /g' | sed 's/press/hPa/g' | sed 's/temp/C/g' | sed 's/humid/%/g' | sed 's/volt/V/g' | sed 's/amps/A/g' | sed 's/watt/W/g' | sed 's/water/m3/g' | sed 's/gas/m3/g' | sed 's/elec/kWh/g' >> $dir/tmp/lcd


php-cgi -f $dir/modules/sensors/node.php
php-cgi -f $dir/modules/mysql/mysql_send.php

#owfs
$dir/modules/sensors/1wire/owfs



