#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M`

if [ ! -e $dir/tmp/log.txt ]; then
touch $dir/tmp/log.txt
chmod 775 $dir/tmp/log.txt
chown root.www-data $dir/tmp/log.txt 
fi

#echo "$date temp_dev_read - read sensors" >> $dir/tmp/log.txt

db=`ls $dir/db/`
if [[ -z "$db" ]]; then 
echo "INFO: no sensors added"
exit
fi

php-cgi -f $dir/modules/sensors/other/raspberrypi_read.php
php-cgi -f $dir/modules/sensors/other/bananapi_read.php
php-cgi -f $dir/modules/sensors/1wire/1wire_gpio_i2c_read.php
php-cgi -f $dir/modules/sensors/i2c/i2c_read.php
php-cgi -f $dir/modules/sensors/1wire/1wire_serial_read.php
php-cgi -f $dir/modules/sensors/GPIO/DHT/dht_read.php
php-cgi -f $dir/modules/sensors/lmsensors/lmsensors_read.php
php-cgi -f $dir/modules/sensors/snmp/snmp.php
php-cgi -f $dir/modules/sensors/1wire/owfs.php
php-cgi -f $dir/modules/sensors/snmp/snmp_read.php
php-cgi -f $dir/modules/sensors/GPIO/HCS04/read.php
php-cgi -f $dir/modules/sensors/rs485/sdm630.php

#1wire usb
$dir/modules/sensors/1wire/1wire_usb_read
# wireless
$dir/modules/sensors/wireless/esp8266_read
#sdm120/sdm120c
$dir/modules/sensors/rs485/sdm120
#orwe
$dir/modules/sensors/rs485/orwe


#in test
$dir/modules/sensors/other/ups
php-cgi -f $dir/modules/lcd/lcd.php
php-cgi -f $dir/modules/sensors/node.php
php-cgi -f $dir/modules/mysql/mysql_send.php



