#! /bin/bash

#dir0=`find / -name config_nettemp.php 2> /dev/null | sed 's/..................$//' | cut -c 1-`
#dir=`cat $dir0/config_nettemp.php |grep dir | cut -c 5-`

dir=/var/www/nettemp
usb=`sqlite3 $dir/dbf/nettemp.db "SELECT usb FROM device"`
onewire=`sqlite3 $dir/dbf/nettemp.db "SELECT onewire FROM device"`
if [ "$usb" == "off" ] && [ "$onewire" == "off" ]; then 
echo "no device"
else
date=`date +%y%m%d-%H%M`
if [ ! -e $dir/tmp/log.txt ]; then
touch $dir/tmp/log.txt
chmod 775 $dir/tmp/log.txt
chown root.www-data $dir/tmp/log.txt 
fi

echo "$date script temp - read sensors" >> $dir/tmp/log.txt

db=`ls $dir/db/`
if [[ -z "$db" ]]; then 
echo "no sensors added"
exit
fi


for name in $db
do
name_str=${#name}
if [ $name_str -gt "19" ]; then 

name_1=`echo $name |awk 'sub("....$", "")' | sed 's/_/ /g'`
name_3=`echo $name_1 | sed ':a;$!{N;s/\n//;ba;};s/..../& /g'`
name_2=`cat $dir/tmp/.digitemprc |grep "$name_3" |awk 'BEGIN {FS=" "} {print $2}'`


if [ "$usb" = "DS2490" ]; then
wynik=`/usr/bin/digitemp_$usb -c $dir/tmp/.digitemprc -t $name_2 -q -o%.1C |grep -v Found`
echo $wynik
else 
wynik=`/usr/bin/digitemp_$usb -c $dir/tmp/.digitemprc -t $name_2 -q -o%.1C`
echo $wynik
fi

rrdtool update $dir/db/$name N:$wynik
sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$wynik' WHERE rom='$name_1'"

fi

unset wynik 

#1-wire
if [ $name_str -lt "20" ]; then

    one_wire_name=`echo $name |awk 'sub("....$", "")'`	
    name_1=`cat $dir/tmp/onewire |grep $one_wire_name`
	if  [ -e /sys/bus/w1/devices/${name_1}/w1_slave ]; then
	    wynik=`awk -F'[ =]' ' $11 ~ /crc/ && $13 ~ /YES/ { getline; printf "%3.1f\n", $11/1000 } ' /sys/bus/w1/devices/${name_1}/w1_slave;`
	    echo $wynik
	else 
	    echo "$date script temp - error reading sensor $name" >> $dir/tmp/log.txt    
	
	fi
	
    
	if [ -n $wynik ]; then 
	    rrdtool update $dir/db/$name N:$wynik
	    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$wynik' WHERE rom='$name_1'"
	else
	    echo "$date script temp - error 2 reading sensor $name " >> $dir/tmp/log.txt    
	fi
fi



done
fi








