#! /bin/bash 

#dir0=`find / -name config_nettemp.php 2> /dev/null | sed 's/..................$//' | cut -c 1-`
#dir=`cat $dir0/config_nettemp.php |grep dir | cut -c 5-`

dir=/var/www/nettemp
usb=`sqlite3 $dir/dbf/nettemp.db "SELECT usb FROM device"`
onewire=`sqlite3 $dir/dbf/nettemp.db "SELECT onewire FROM device"`
if [ "$usb" == "off" ] && [ "$onewire" == "off" ]; then 
echo "no device"
else
date=`date +%y%m%d-%H%M`
if [ ! -e $dir/tmp/log.txt ]; then
touch $dir/tmp/log.txt
chmod 775 $dir/tmp/log.txt
chown root.www-data $dir/tmp/log.txt 
fi

echo "$date temp_dev_read - read sensors" >> $dir/tmp/log.txt

db=`ls $dir/db/`
if [[ -z "$db" ]]; then 
echo "no sensors added"
exit
fi


for name in $db
do
name_str=${#name}
if [ $name_str -gt "19" ]; then 

name_1=`echo $name |awk 'sub("....$", "")' | sed 's/_/ /g'`
name_3=`echo $name_1 | sed ':a;$!{N;s/\n//;ba;};s/..../& /g'`
name_2=`cat $dir/tmp/.digitemprc |grep "$name_3" |awk 'BEGIN {FS=" "} {print $2}'`


if [ "$usb" = "DS2490" ]; then
	    wynik=`/usr/bin/digitemp_$usb -c $dir/tmp/.digitemprc -t $name_2 -q -o%.1C |grep -v Found`
	    echo $wynik
else 
	    wynik=`/usr/bin/digitemp_$usb -c $dir/tmp/.digitemprc -t $name_2 -q -o%.1C`
	    echo $wynik
fi


    if [ "$wynik" != "85" ] && [ "$wynik" != "85.0" ] ; then
	    rrdtool update $dir/db/$name N:$wynik
	    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$wynik' WHERE rom='$name_1'"
    else 
	    echo "$date temp_dev_read - reading sensor error 85C (resistor, or calbe problem) $name " >> $dir/tmp/log.txt    
    fi

fi

unset wynik 

#1-wire
if [ $name_str -lt "20" ]; then
    one_wire_name=`echo $name |awk 'sub("....$", "")'`
    name_1=`cat $dir/tmp/onewire |grep $one_wire_name`
    if [ "$name_1" != "Raspberry_Pi" ]; then    
	if  [ -e /sys/bus/w1/devices/${name_1}/w1_slave ]; then
	    wynik=`awk -F'[ =]' ' $11 ~ /crc/ && $13 ~ /YES/ { getline; printf "%3.1f\n", $11/1000 } ' /sys/bus/w1/devices/${name_1}/w1_slave;`
	    echo $wynik
	    if  [ -n "$wynik" ]; then
		if [ "$wynik" != "85" ] && [ "$wynik" != "85.0" ]  ; then 
	    		rrdtool update $dir/db/$name N:$wynik
	    		sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$wynik' WHERE rom='$name_1'"
		else
	    		echo "$date temp_dev_read - reading sensor error 85C (resistor, or calbe problem) $name " >> $dir/tmp/log.txt    
		fi
	    else
		echo "$date temp_dev_read - reading sensor error (CRC OK but no result) $name " >> $dir/tmp/log.txt    
	    fi
	else 
	    echo "$date temp_dev_read - reding sensor error (CRC) $name" >> $dir/tmp/log.txt    
	fi
    fi
fi



done
fi

# RaspberryPi temp

wynik="0"

if [ ! -e $dir/db/Raspberry_Pi.rrd ]; then

  sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO sensors \
    (name, color, rom, tmp, tmp_min, tmp_max, alarm, hour, day, week, month, year) \
    VALUES ('RPi','#07FF00','Raspberry_Pi', '0', '', '', 'off', 'on', 'on', 'on', 'on', 'on' )"

    /usr/bin/rrdtool create $dir/db/Raspberry_Pi.rrd -s 60 DS:temp:GAUGE:700:-150:150 RRA:AVERAGE:0.5:1:48384 RRA:MAX:0.5:1:48384 RRA:MIN:0.5:1:48384 RRA:LAST:0.5:1:48384
    chmod 777 $dir/db/Raspberry_Pi.rrd
    echo "create rrd"
fi
if [ ! $(cat $dir/tmp/onewire |grep Raspberry_Pi) ]; then
    echo "Raspberry_Pi" >> $dir/tmp/onewire
    echo "add pi to onewire"
fi

if [ -n "$wynik" ]; then 
    wynik=$(/opt/vc/bin/vcgencmd measure_temp | cut -c 6-9)
    rrdtool update $dir/db/Raspberry_Pi.rrd N:$wynik
    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$wynik' WHERE rom='Raspberry_Pi'"
    echo $wynik
fi





