#! /bin/bash

dir=$(cd "$( dirname "$0" )" && cat ../../conf.php |grep global | awk -F"'" '{ print $2 }')

date=`date +%y%m%d-%H%M`

rm -rf $dir/tmp/.digitemprc
rm -rf $dir/tmp/onewire


echo "$date temp_dev_scan - Deleted .digitemprc" >> $dir/tmp/log.txt

# DS9097U na USB - meraprojekt new
for i in 0 1 2 3
    do
	if [ `ls /dev/ttyUSB$i 2> /dev/null` ]; then 
	/usr/bin/digitemp_DS9097U -i -c $dir/tmp/.digitemprc -s/dev/ttyUSB$i
	fi
    done
	if [ -e $dir/tmp/.digitemprc ]; then 
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET usb='DS9097U'"
	echo "$date temp_dev_scan - Discovered DS9097U on USB" >> $dir/tmp/log.txt
	else
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET usb='off' WHERE id='1'"
	fi


# DS2490 na USB - meraprojekt old
if [ ! -e $dir/tmp/.digitemprc ]; then 
    /usr/bin/digitemp_DS2490 -i -c $dir/tmp/.digitemprc 
    if [ -e $dir/tmp/.digitemprc ]; then 
    sqlite3 $dir/dbf/nettemp.db "UPDATE device SET usb='DS2490'"
    echo "$date temp_dev_scan - Discovered DS2490 on USB" >> $dir/tmp/log.txt
    else
    sqlite3 $dir/dbf/nettemp.db "UPDATE device SET usb='off' WHERE id='1'"
    fi
fi

# DS9097 na USB - serial na przejsciowce USB
if [ ! -e $dir/tmp/.digitemprc ]; then 
    for i in 0 1 2 3
	do
	    if [ `ls /dev/ttyUSB$i 2> /dev/null` ]; then 
	    /usr/bin/digitemp_DS9097 -i -c $dir/tmp/.digitemprc -s/dev/ttyUSB$i
	    fi
	done
    if [ -e $dir/tmp/.digitemprc ]; then 
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET usb='DS9097' WHERE id='1'"
	echo "$date temp_dev_scan - Discovered DS9097 on USB" >> $dir/tmp/log.txt
	else
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET usb='off'"
    fi
fi

# DS9097 - serial 
if [ ! -e $dir/tmp/.digitemprc ]; then 
    for i in 0 1 2 3
	do
	    if [ `ls /dev/ttyS$i 2> /dev/null` ]; then 
	    /usr/bin/digitemp_DS9097 -i -c $dir/tmp/.digitemprc -s/dev/ttyS$i
	    fi
	done
    if [ -e $dir/tmp/.digitemprc ]; then 
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET serial='DS9097' WHERE id='1'"
	echo "$date temp_dev_scan - Discovered DS9097 on serial port" >> $dir/tmp/log.txt
	else
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET serial='off'"
    fi
fi

# 1-wire

if [ -e /sys/bus/w1/devices/w1_bus_master1/w1_master_slaves ]; then 
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET onewire='on' WHERE id='1'"
	echo "$date temp_dev_scan - Discovered 1-wire temp sensors" >> $dir/tmp/log.txt

# scan 1-wire
	#modprobe wire
	#modprobe w1_gpio
	#modprobe w1_therm

	
for sensor in `cat /sys/bus/w1/devices/w1_bus_master1/w1_master_slaves`; do 

	
    if  [ -e /sys/bus/w1/devices/${sensor}/w1_slave ]; then
      wynik=`awk -F'[ =]' ' $11 ~ /crc/ && $13 ~ /YES/ { getline; printf "%3.2f\n", $11/1000 } ' /sys/bus/w1/devices/${sensor}/w1_slave;`

    	echo $sensor  >>  $dir/tmp/onewire
    fi

done


else
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET onewire='off' WHERE id='1'"
fi


#RPI system temp

if [ ! $(cat $dir/tmp/onewire |grep Raspberry_Pi) ]; then
    echo "Raspberry_Pi" >> $dir/tmp/onewire
    echo "add pi to onewire"
fi

# DHT11 22
dht=`sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM gpio where humi_checkbox='on'"`

for dht_gpio in $dht; do
 tmp1="gpio_$dht_gpio" 
 tmp2="_temp"
 echo "$tmp1$tmp2" >> $dir/tmp/onewire
 dht1="gpio_$dht_gpio"
 dht2="_humi"
 echo "$dht1$dht2" >> $dir/tmp/onewire
done

# snmp
snmp=`sqlite3 $dir/dbf/snmp.db "SELECT name FROM snmp"`
for name in $snmp; do 
 echo "$name" >> $dir/tmp/onewire
done











