#! /bin/bash 
dir=/var/www/nettemp
date=$(date +%y%m%d-%H%M)
now_time_s=`date +%s`
mode=$(sqlite3 $dir/dbf/nettemp.db "SELECT mode FROM logoterma")
if [ "$mode" == "manual" ]; then 
	
    if [  "$1" = "run" ] && [ -n "$2" ]; then
	offset=$2
	end_time=$(date -d "`date` +$offset second" +%s)
	sqlite3 $dir/dbf/nettemp.db "UPDATE logoterma SET manual_end_time='$end_time'"
	# logoterma on
	$dir/modules/logoterma/relay on
	echo "$date Logoterma ON" >> $dir/tmp/log.txt	    
	
    fi
	end_time_ff=$(sqlite3 $dir/dbf/nettemp.db "SELECT manual_end_time FROM logoterma")
	if [ -n "$end_time_ff" ]; then
	    #echo End time: $end_time_ff
	    #echo End date: $(date --date="1970-01-01 UTC +$end_time_ff sec" +"%a %b %d %H:%M:%S %Y")
	    #echo Logoterma status is $($dir/modules/logoterma/relay)
		if [ $end_time_ff -lt $now_time_s ]; then # lt  mnijsze 
		    echo Time end
		    sqlite3 $dir/dbf/nettemp.db "UPDATE logoterma SET manual_end_time='' "
		    # logoterma off
		    $dir/modules/logoterma/relay off
		    echo "$date Logoterma OFF" >> $dir/tmp/log.txt	    
		else 
		    diff=$(( $end_time_ff - $now_time_s ))
		    echo "Elapsed time is $(($diff/60)) min, ($diff sec)" 
		fi	
	else
	echo Logoterma is OFF
    fi
fi

