#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

onoff=$(sqlite3 $dir/dbf/nettemp.db "SELECT i2c FROM device WHERE id='1'")

if [ "$onoff" == "on" ]; then 

###########
# BMP 0x77
###########

db=$(ls $dir/db |grep  i2c_77)
all=$($dir/modules/i2c/BMP180/Adafruit_BMP085_run.py)
for i in $db; do
if echo $i |grep temp > /dev/null ; then 
    temp=$(echo $all | awk '{ print $2}')
    echo Temp $temp
    rrdtool update $dir/db/$i N:$temp
    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$temp' WHERE rom='$(echo $i |awk 'sub("....$", "")')'"
fi
if echo $i |grep altitude > /dev/null ; then 
    altitude=$(echo  $all | awk '{ print $6}')
    echo Alititude $altitude
    rrdtool update $dir/db/$i N:$altitude
    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$altitude' WHERE rom='$(echo $i |awk 'sub("....$", "")')'"
fi
if echo $i |grep pressure > /dev/null ; then 
    pressure=$(echo $all | awk '{ print $4}')
    echo Pressure $pressure
    rrdtool update $dir/db/$i N:$pressure
    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$pressure' WHERE rom='$(echo $i |awk 'sub("....$", "")')'"
fi
done

###########
# TSL 0x77
###########

db=$(ls $dir/db |grep  i2c_39_lux)
i2c0=$($dir/modules/i2c/TSL2561/TSL2561_i2c_0)
if echo $i2c0 |grep Success > /dev/null; then
    lux=$(echo $i2c0 |awk '{print $3}')
    echo LUX $lux
    rrdtool update $dir/db/$db N:$lux
    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$lux' WHERE rom='$(echo $db |awk 'sub("....$", "")')'"
else
    i2c1=$($dir/modules/i2c/TSL2561/TSL2561_i2c_1)
    if echo $i2c1 |grep Success > /dev/null; then
	lux=$(echo $i2c1 |awk '{print $3}')
	echo LUX $lux
	rrdtool update $dir/db/$db N:$lux
	sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$lux' WHERE rom='$(echo $db |awk 'sub("....$", "")')'"
    fi
fi

else 
    echo "i2c OFF"
fi



