#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

onoff=$(sqlite3 $dir/dbf/nettemp.db "SELECT i2c FROM device WHERE id='1'")

if [ "$onoff" == "i2c-1" ] || [ "$onoff" == "i2c-0" ] ; then 

###########
# BMP180
###########

db=$(ls $dir/db |grep  i2c_77)
all=$($dir/modules/i2c/BMP180/Adafruit_BMP085_run.py)
for i in $db; do
if echo $i |grep temp > /dev/null ; then 
    temp=$(echo $all | awk '{ print $2}')
    if ! [[ "$temp" =~ .[0-9]+$ ]] 
	then
	    temp="error"
    fi
	    echo BMP180 Temp $temp
	    rrdtool update $dir/db/$i N:$temp
	    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$temp' WHERE rom='$(echo $i |awk 'sub("....$", "")')'"
fi
if echo $i |grep altitude > /dev/null ; then 
    altitude=$(echo  $all | awk '{ print $6}')
    if ! [[ "$altitude" =~ .[0-9]+$ ]] 
	then
	    altitude="error"
    fi
    echo BMP180 Alititude $altitude
    rrdtool update $dir/db/$i N:$altitude
    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$altitude' WHERE rom='$(echo $i |awk 'sub("....$", "")')'"
fi
if echo $i |grep pressure > /dev/null ; then 
    pressure=$(echo $all | awk '{ print $4}')
    if ! [[ "$pressure" =~ .[0-9]+$ ]] 
	then
	    pressure="error"
    fi
    echo BMP180 Pressure $pressure
    rrdtool update $dir/db/$i N:$pressure
    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$pressure' WHERE rom='$(echo $i |awk 'sub("....$", "")')'"
fi
done

###########
# TSL
###########

db=$(ls $dir/db |grep i2c_39_lux)

i2c=$($dir/modules/i2c/TSL2561/TSL2561_i2c_$(echo $onoff | sed 's/i2c-//'))
if echo $i2c |grep Success > /dev/null
     then
	lux=$(echo $i2c |awk '{print $3}')
	    if ! [[ "$lux" =~ [0-9]+$ ]] 
		then
		    lux="error"
	    fi
    echo TSL2561 $lux
    rrdtool update $dir/db/$db N:$lux
    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$lux' WHERE rom='$(echo $db |awk 'sub("....$", "")')'"
fi

###########
# HTU21D 
###########

dbhtu21dt=$(ls $dir/db |grep i2c_40_temp)
dbhtu21dh=$(ls $dir/db |grep i2c_40_humi)
htu21d=$($dir/modules/i2c/HTU21D/htu21d.py )
htu21dt=$(echo $htu21d |awk '{ getline; printf "%3.2f\n", $2 }')
htu21dh=$(echo $htu21d |awk '{ getline; printf "%3.2f\n", $5 }')

	    if ! [[ "$htu21dt" =~ [0-9]+$ ]] && [ -n "$htu21dt" ]
		then
		    htu21dt="error"
	    fi
    echo HTU21D Temp: $htu21dt
    rrdtool update $dir/db/$db N:$htu21dt
    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$htu21dt' WHERE rom='$(echo $dbhtu21dt |awk 'sub("....$", "")')'"

	    if ! [[ "$htu21dh" =~ [0-9]+$ ]] && [ -n "$htu21dh" ] 
		then
		    htu21ddh="error"
	    fi
    echo HTU21D Humid: $htu21dh
    rrdtool update $dir/db/$db N:$htu21dh
    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$htu21dh' WHERE rom='$(echo $dbhtu21dh |awk 'sub("....$", "")')'"



##########
else 
    echo "i2c OFF"
fi



