#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`
if name=$(sqlite3 $dir/dbf/snmp.db "SELECT name FROM snmp")
    then
    for snmp in $name; do 
	community=$(sqlite3 $dir/dbf/snmp.db "SELECT community FROM snmp WHERE name='$snmp'")
	host=$(sqlite3 $dir/dbf/snmp.db "SELECT host FROM snmp WHERE name='$snmp'")
	oid=$(sqlite3 $dir/dbf/snmp.db "SELECT oid FROM snmp WHERE name='$snmp'")
	divider=$(sqlite3 $dir/dbf/snmp.db "SELECT divider FROM snmp WHERE name='$snmp'")
	walk=$(snmpget -v 2c -c $community $host $oid -O v)
        wynik=`echo $walk | tr -d \" | awk '{printf "%3.1f\n", $2/'$divider' }'`  
	sqlite3 $dir/db/$snmp.sql "INSERT OR IGNORE INTO def (value) VALUES ('$wynik');"
	sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$wynik' WHERE rom='$snmp'"
	echo SNMP: $wynik C
     done
fi