#! /bin/bash

# snmp
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`


snmp=`sqlite3 $dir/dbf/snmp.db "SELECT name FROM snmp"`
if [ -n "$snmp" ]
    then
    snmp_count=$(echo "$snmp" |grep -c snmp)
    if [ "$snmp_count" != "0" ] && [ -n "$snmp_count" ]
        then
        echo SNMP: $snmp_count sensors found
        for name in $snmp; do 
	#echo "$name" >> $dir/tmp/onewire
	sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$name')"
        done
    fi
fi
