#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

if rom=$(sqlite3 $dir/dbf/nettemp.db "SELECT rom FROM sensors WHERE type='wireless'")
    then
    for wireless in $rom; do
     



	rrdtool update $dir/db/$snmp.rrd N:$wynik
	sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$wynik' WHERE rom='$snmp'"
	echo SNMP: $wynik C
     done
fi