#! /bin/bash -x

dir=/var/www/nettemp
date=`date +%y%m%d-%H%M`

dev=`sqlite3 $dir/dbf/nettemp.db "SELECT dev FROM sms_settings WHERE default_dev='on'"`
smsc=`sqlite3 $dir/dbf/nettemp.db "SELECT smsc FROM sms_settings WHERE default_dev='on'"`
nr=$1

send_sms()
{
    
    echo -e -n "AT \015" > $dev
    sleep 5
    echo -e -n "AT+CMGF=1 \015" > $dev
    sleep 5 
    echo -e -n "AT+CSCA=\"$smsc\"\015" > $dev
    sleep 5   
    echo -e -n "AT+CMGS=\"$nr\" \015" > $dev
    sleep 5
    echo -e -n "test sms from nettemp.pl" > $dev
    sleep 5
    echo -e -n "\032" > $dev
}

send_sms 
echo "$date sms_test - send test sms to $nr " >> $dir/tmp/log.txt

