#!/bin/bash

DATE=`date +%y%m%d-%H%M`
LOG="/var/www/nettemp/tmp/incoming_sms.txt"

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=$(date +%y%m%d-%H%)

cd /var/spool/sms/incoming

for i in $(ls); do

number=$(cat $i |grep From: |sed 's/From://g'| sed 's/ //g')
date1=$(LC_ALL=en_EN.utf8 date '+%a')
date2=$(date +%H%M)

name=$(sqlite3 $dir/dbf/nettemp.db "SELECT at FROM users WHERE tel='$number'")
pin=$(sqlite3 $dir/dbf/nettemp.db "SELECT smspin FROM users WHERE tel='$number'")
smsts=$(sqlite3 $dir/dbf/nettemp.db "SELECT smsts FROM users WHERE tel='$number'")
day=$(sqlite3 $dir/dbf/nettemp.db "SELECT $date1 FROM access_time WHERE name='$name'")
stime=$(sqlite3 $dir/dbf/nettemp.db "SELECT stime FROM access_time WHERE name='$name'")
etime=$(sqlite3 $dir/dbf/nettemp.db "SELECT etime FROM access_time WHERE name='$name'")

if [[ "$day" == "$date1" && "$date2" > "$stime" && "$date2" < "$etime" && "$smsts" == "yes" ]]; then

    if [[ $(cat "$i" |grep "$pin") ]]; then 
	sudo rm -rf $i
	/bin/bash $dir/tmp/sms_script
    fi

    echo "${DATE} SMS Allow $number" >> ${LOG}
else 
    echo "${DATE} SMS Deny $number" >> ${LOG}
	mv $i /var/spool/sms/checked/
fi
done

exit 0

