#!/bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M%S`

nr=`sqlite3 $dir/dbf/nettemp.db "SELECT tel FROM users WHERE smsa='yes'" | awk '{ printf " "$1 }'`

mkdir -p $dir/tmp/sms

check_alarm() {
for line in `sqlite3 $dir/dbf/nettemp.db "SELECT name,tmp,tmp_min,tmp_max FROM sensors WHERE alarm='on'"| sed 's/ /_/g'`; 
    do
	for line2 in $nr
	    do
		line2=$(echo $line2 |sed 's/ //g')
		name=`echo $line | awk 'BEGIN {FS="|"}{print $1}'`
		tmp=`echo $line | awk 'BEGIN {FS="|"}{print $2}'`
		tmp_min=`echo $line | awk 'BEGIN {FS="|"}{print $3}'`
		tmp_max=`echo $line | awk 'BEGIN {FS="|"}{print $4}'`
		plik=/var/spool/sms/outgoing/sms-$name-$line2
	
		if [ -n "$tmp_max" ]; then
		    cr_ge=$(echo $tmp $tmp_max | awk '{if ($1 > $2) print 1; else print 0 }')
		    if [ $cr_ge == 1 ]; then
			echo "To: $line2" > $plik; 
			echo "" >> $plik; 
			echo "high $name $tmp C" >> $plik; 
		    fi
		fi
		if [ -n "$tmp_min" ]; then
		    cr_le=$(echo $tmp $tmp_min | awk '{if ($1 < $2) print 1; else print 0 }')
		    if [ $cr_le == 1 ]; then  
			echo "To: $line2" > $plik; 
			echo "" >> $plik; 
			echo "low $name $tmp C" >> $plik; 
		    fi
		fi
	    done
done 
}

send_sms()
{
echo "$date sms_test - send sms to $1 $(cat $plik | gammu -c $dir/tmp/gammurc  --sendsms TEXT $1 )" >> $dir/tmp/log.txt
}


check_alarm



