#! /bin/bash

# i2c
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`


for bus in $(ls /dev/i2c-*)
    do
	i2c=$(echo $bus| awk -F"-" {'print $2'})
        if det=$(sudo i2cdetect -y $i2c |sed '1d'|awk '{ $1=""; print $0 }' |grep -o '[0-9]*')
		then
		    sqlite3 $dir/dbf/nettemp.db "UPDATE device SET i2c='i2c-$i2c' WHERE id='1'"
	fi
done



bmp180="77" #0x77
TSL2561="39" #0x39
ds2482="18" #0x18 
HTU21D="40" #0x40
MPL3115A2="60" #0x60

if [ -n "$i2c" ]; then 
    echo I2C: Found $det
fi

for i in $det
    do
        if [ "$i" = "$bmp180" ]
	    then
		echo i2c_$i\_pressure >> $dir/tmp/onewire
		echo i2c_$i\_temp >> $dir/tmp/onewire
		#echo i2c_$i\_altitude >> $dir/tmp/onewire
        fi
        if [ "$i" = "$TSL2561" ]
	    then
		echo i2c_$i\_lux >> $dir/tmp/onewire
        fi
        if [ "$i" = "$ds2482" ]
	    then
		echo ds2482 0x$ds2482 > /sys/bus/i2c/devices/i2c-$i2cbus/new_device
		    if ! grep -q 0x$ds2482 $dir/modules/cron/r
			then
			    sed -i '$aecho ds2482 0x'$ds2482' > /sys/bus/i2c/devices/i2c-'$i2cbus'/new_device' $dir/modules/cron/r
		    fi
        fi
        if [ "$i" = "$HTU21D" ]
	    then
		echo i2c_$i\_humi >> $dir/tmp/onewire
		echo i2c_$i\_temp >> $dir/tmp/onewire
        fi
	if [ "$i" = "$MPL3115A2" ]
	    then
		echo i2c_$i\_pressure >> $dir/tmp/onewire
		echo i2c_$i\_temp >> $dir/tmp/onewire
        fi
    done
