#! /bin/bash

# i2c
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

det=()
addr=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c")


for i2c in $(ls /dev/i2c-*| awk -F"-" {'print $2'} )
    do
	for i in $addr; do
    	    if sudo i2cdetect -y $i2c |sed '1d'|awk '{ $1=""; print $0 }' |grep -o -q -E $i
		then
		    det+=($i)
	    fi
	done
	if [ -n "$det" ]; then #poprawic
	    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET i2c='i2c-$i2c' WHERE id='1'"
	    i2c=$i2c
	    break
	fi
done

if [ -n "$det" ]; then  # poprawic sprawdanie
    echo I2C: Found "${det[@]}"
fi

#bmp180="77"
#TSL2561="39"
#ds2482=['18','1a']
#HTU21D="40"
#MPL3115A2="60"
#HIH6130="27"
#TMP102="48"
#bh1750="23"

press=_press
temp=_temp
lux=_lux
humid=_humid


for i in ${det[@]}
    do
        for s in $(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c WHERE name='bmp180' AND addr='$i'")
	    do
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$press')"
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$temp')"
	done

        for s in $(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c WHERE name='bme280' AND addr='$i'")
    	    do
      		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$temp')"
      		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$press')"
      		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$humid')"
   	done

        for s in $(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c WHERE name='tsl2561' AND addr='$i'")
	    do
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$lux')"
        done

	for s in $(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c WHERE name='bh1750' AND addr='$i'")
	    do
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$lux')"
        done
        
	

	for s in $(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c WHERE name='htu21d' AND addr='$i'")
	    do
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$humid')"
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$temp')"
        done

	for s in $(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c WHERE name='mpl3115a2' AND addr='$i'")
	    do
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$press')"
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$temp')"
        done

	for s in $(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c WHERE name='hih6130' AND addr='$i'")
	    do
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$humid')"
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$temp')"
        done

	for s in $(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c WHERE name='tmp102' AND addr='$i'")
	    do
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('i2c_$s$temp')"
        done
done



#DS2482
    ddir=$dir/tmp/ds2482
    sudo echo "modprobe ds2482" > $ddir
    sudo echo "modprobe w1-therm strong_pullup=0" >> $ddir

    for s in $(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c WHERE name='ds2482'")
    do
	sudo echo "echo ds2482 0x$s > /sys/bus/i2c/devices/i2c-$i2c/new_device" >> $ddir
	#echo I2C: Found DS2482 0x$s
    done

    sudo echo "exit 0" >> $ddir
    sudo chmod +x $ddir
    sudo cp $dir/install/1w/nettemp.ds2482 /etc/init.d/
    sudo update-rc.d nettemp.ds2482 defaults
    sudo service nettemp.ds2482 start
    #sudo touch $dir/tmp/reboot
#end DS2482


