#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )

if onoff=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT i2c FROM device WHERE id='1'")
then
if [ "$onoff" == "i2c-1" ] || [ "$onoff" == "i2c-0" ] || [ "$onoff" == "i2c-2" ] || [ "$onoff" == "i2c-3" ] ; then 
####################################################################################
bus=$(echo $onoff|sed 's/i2c-//g')
skey=$( sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")

function checkwrite {
php-cgi -f $dir/receiver.php key=$skey rom=$2 value=$1 type=$3
}

cd $dir/db

###########
v=bmp180
id=$( sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c where name='$v'")
###########

for id in $id; do
    if  sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT id FROM sensors WHERE rom LIKE 'i2c_$id%'"|grep -q [0-9]; then 
	all=($($dir/modules/sensors/i2c/BMP180/bmp180.py $bus 2>/dev/null))
	    t=i2c_${id}_temp.sql
	    p=i2c_${id}_press.sql
	    if [ -s "$t" ]; then
		name=$(echo $t |awk 'sub("....$", "")')
		temp=${all[0]}
		if [[ ! -n $temp ]]; then temp="error"; fi
		checkwrite $temp $name temp
		echo $v Temp $temp
	    fi
	    if [ -s "$p" ]; then
		name=$(echo $p |awk 'sub("....$", "")')
		press=${all[1]}
		if [[ ! -n $press ]]; then press="error"; fi
		checkwrite $press $name press
		echo $v Pressure $press
	    fi
	#else
	#    echo $v main error
	#fi
    fi
done

###########
v=tsl2561
id=$( sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c where name='$v'")
###########

for id in $id; do
    if  sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db  "SELECT id FROM sensors WHERE rom LIKE 'i2c_$id%'"|grep -q [0-9]; then 
	all=$($dir/modules/sensors/i2c/TSL2561/TSL2561_i2c_$(echo $onoff | sed 's/i2c-//') 2>/dev/null)
	    l=i2c_${id}_lux.sql
	    if [ -s "$l" ]; then
		name=$(echo $l |awk 'sub("....$", "")')
		lux=$(echo $all |awk '{print $3}')
		if [[ ! -n $lux ]]; then lux="error"; fi
		checkwrite $lux $name lux
		echo $v $lux
	    else
    		echo $v main error
	    fi
    fi
done

###########
v=bh1750
id=$( sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c where name='$v'")
###########

for id in $id; do
    if  sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db  "SELECT id FROM sensors WHERE rom LIKE 'i2c_$id%'"|grep -q [0-9]; then 
	all=($($dir/modules/sensors/i2c/BH1750/bh1750.py $bus 2>/dev/null))
	    l=i2c_${id}_lux.sql
	    if [ -s "$l" ]; then
		name=$(echo $l |awk 'sub("....$", "")')
		lux=${all[0]}
		if [[ ! -n $lux ]]; then lux="error"; fi
		checkwrite $lux $name lux
		echo $v $lux
	    else
    		echo $v main error
	    fi
    fi
done


###########
v=htu21d
id=$( sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c where name='$v'")
###########

for id in $id; do
    if  sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db  "SELECT id FROM sensors WHERE rom LIKE 'i2c_$id%'"|grep -q [0-9]; then 
	all=($($dir/modules/sensors/i2c/HTU21D/htu21d.py $bus $id 2>/dev/null))
	    t=i2c_${id}_temp.sql
	    h=i2c_${id}_humid.sql
	    if [ -s "$t" ]; then
		temp=${all[0]}
		if [[ ! -n $temp ]]; then temp="error"; fi
		name=$(echo $t |awk 'sub("....$", "")')
		checkwrite $temp $name temp
		echo $v Temp: $temp
	    fi
	if [ -s "$h" ]; then
	    humid=${all[1]}
	    if [[ ! -n $humid ]]; then humid="error"; fi
	    name=$(echo $h |awk 'sub("....$", "")')
	    checkwrite $humid $name humid
	    echo $v Humid: $humid
	fi
	#    else
	#    echo $v main error
	#fi
    fi
done


###########
v=mpl3115a2
id=$( sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c where name='$v'")
###########

for id in $id; do
    if  sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db  "SELECT id FROM sensors WHERE rom LIKE 'i2c_$id%'"|grep -q [0-9]; then 
	echo 1 > /sys/module/i2c_bcm2708/parameters/combined
	all=($($dir/modules/sensors/i2c/MPL3115A2/read.py $bus 2>/dev/null))
	    t=i2c_${id}_temp.sql
	    p=i2c_${id}_press.sql
	    if [ -s "$t" ]; then
		temp=${all[1]}
		if [[ ! -n $temp ]]; then temp="error"; fi
		name=$(echo $t |awk 'sub("....$", "")')
		checkwrite $temp $name temp
		echo $v Temp: $temp
	    fi
	    if [ -s "$p" ]; then
		press=${all[0]}
		if [[ ! -n $press ]]; then press="error"; fi
		name=$(echo $p |awk 'sub("....$", "")')
		checkwrite $press $name press
		echo $v Pressure: $press
	    fi
	#else
    	#    echo $v main error
	#fi
    fi
done

###########
v=hih6130
id=$( sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c where name='$v'")
###########

for id in $id; do
    if  sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db  "SELECT id FROM sensors WHERE rom LIKE 'i2c_$id%'"|grep -q [0-9]; then 
	 all=$(cd $dir && $dir/modules/sensors/i2c/HIH6130/read.py $bus 2>/dev/null && cd -);
	    t=i2c_${id}_temp.sql
	    h=i2c_${id}_humid.sql
	    if [ -s "$t" ]; then
		temp=$(echo $all |awk '{print $4}')
		if [[ ! -n $temp ]]; then temp="error"; fi
		name=$(echo $t |awk 'sub("....$", "")')
		checkwrite $temp $name temp
		echo $v Temp: $temp
	    fi
	    if [ -s "$h" ]; then
		humid=$(echo $all |awk '{printf $2}')
		if [[ ! -n $humid ]]; then humid="error"; fi
		name=$(echo $h |awk 'sub("....$", "")')
		checkwrite $humid $name humid
		echo $v Humid: $humid
	    fi
    fi
done

###########
v=tmp102
id=$( sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT addr FROM i2c where name='$v'")
###########

for id in $id; do
    if  sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db  "SELECT id FROM sensors WHERE rom LIKE 'i2c_$id%'"|grep -q [0-9]; then 
	all=$($dir/modules/sensors/i2c/TMP102/read.py $bus 2>/dev/null)
	    t=i2c_${id}_temp.sql
	    if [ -s "$t" ]; then
		temp=$(echo $all |awk 'sub("..$", "")')
		if [[ ! -n $temp ]]; then temp="error"; fi
		name=$(echo $t |awk 'sub("....$", "")')
		checkwrite $temp $name temp
		echo $v Temp: $temp
	    fi
	#else
    	#    echo $v main error
	#fi
    fi
done


#####################
else 
    echo "i2c OFF"
fi

fi


