#! /bin/bash

# i2c
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`


for bus in $(ls /dev/i2c-*)
    do
	i2c=$(echo $bus| awk -F"-" {'print $2'})
        if det=$(sudo i2cdetect -y $i2c |sed '1d'|awk '{ $1=""; print $0 }' |grep -o -E '77|39|18|40|60|1a')
		then
		    echo $det
		    sqlite3 $dir/dbf/nettemp.db "UPDATE device SET i2c='i2c-$i2c' WHERE id='1'"
	fi
done



bmp180="77" #0x77
TSL2561="39" #0x39
ds2482=['18','1a'] #0x18,1a
HTU21D="40" #0x40
MPL3115A2="60" #0x60

if [ -n "$i2c" ]; then 
    echo I2C: Found $det
fi

for i in $det
    do
        if [ "$i" = "$bmp180" ]
	    then
		echo i2c_$i\_pressure >> $dir/tmp/onewire
		echo i2c_$i\_temp >> $dir/tmp/onewire
		#echo i2c_$i\_altitude >> $dir/tmp/onewire
        fi
        if [ "$i" = "$TSL2561" ]
	    then
		echo i2c_$i\_lux >> $dir/tmp/onewire
        fi
        
	if [[ ${ds2482[*]} =~  $i ]]
	    then
	    echo ds2482 0x$i > /sys/bus/i2c/devices/i2c-$i2c/new_device
		    if ! grep -q 0x$i $dir/tmp/cronr
			then
			    echo "echo ds2482 0x$i > /sys/bus/i2c/devices/i2c-$(echo $i2c)/new_device" >> $dir/tmp/cronr
			    sudo /bin/chmod +x $dir/tmp/cronr
		    fi
        fi
        if [ "$i" = "$HTU21D" ]
	    then
		echo i2c_$i\_humi >> $dir/tmp/onewire
		echo i2c_$i\_temp >> $dir/tmp/onewire
        fi
	if [ "$i" = "$MPL3115A2" ]
	    then
		echo i2c_$i\_pressure >> $dir/tmp/onewire
		echo i2c_$i\_temp >> $dir/tmp/onewire
        fi
    done
