#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )

if onoff=$(sqlite3 $dir/dbf/nettemp.db "SELECT i2c FROM device WHERE id='1'")
then

if [ "$onoff" == "i2c-1" ] || [ "$onoff" == "i2c-0" ] ; then 

###########
# BMP180
###########

db=$(ls $dir/db |grep  i2c_77)
if [ -n "$db" ]
    then
    if all=$($dir/modules/sensors/i2c/BMP180/Adafruit_BMP085_run.py)
	then
	for i in $db; do
	    if echo $i |grep temp > /dev/null ; then 
		temp=$(echo $all | awk '{ print $2}')
		if ! [[ "$temp" =~ .[0-9]+$ ]] 
		    then
			temp="error"
		else
		    sqlite3 $dir/db/$i "INSERT OR IGNORE INTO def (value) VALUES ('$temp');"
		fi
		echo BMP180 Temp $temp
		sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$temp' WHERE rom='$(echo $i |awk 'sub("....$", "")')'"
	    fi
	#	if echo $i |grep altitude > /dev/null ; then 
	#	altitude=$(echo  $all | awk '{ print $6}')
	#	if ! [[ "$altitude" =~ .[0-9]+$ ]] 
	#	    then
	#		altitude="error"
	#	    else
	#		rrdtool update $dir/db/$i N:$altitude
	#	fi
	#	echo BMP180 Alititude $altitude
	#	sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$altitude' WHERE rom='$(echo $i |awk 'sub("....$", "")')'"
	#    fi
	    if echo $i |grep pressure > /dev/null ; then 
		pressure=$(echo $all | awk '{ print $4}')
		if ! [[ "$pressure" =~ .[0-9]+$ ]] 
		    then
			pressure="error"
		else
		    sqlite3 $dir/db/$i "INSERT OR IGNORE INTO def (value) VALUES ('$pressure');"
		fi
		echo BMP180 Pressure $pressure
		sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$pressure' WHERE rom='$(echo $i |awk 'sub("....$", "")')'"
	    fi
	done
    else
	echo BMP180 main error
    fi
fi

###########
# TSL
###########


db=$(ls $dir/db |grep i2c_39_lux)
if [ -n "$db" ] 
    then
	if i2c=$($dir/modules/sensors/i2c/TSL2561/TSL2561_i2c_$(echo $onoff | sed 's/i2c-//'))
	    then
	    lux=$(echo $i2c |awk '{print $3}')
	    if ! [[ "$lux" =~ [0-9]+$ ]] 
		then
    		    lux="error"
		else 
		    sqlite3 $dir/db/$db "INSERT OR IGNORE INTO def (value) VALUES ('$lux');"
	    fi
	    echo TSL2561 $lux
	    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$lux' WHERE rom='$(echo $db |awk 'sub("....$", "")')'"
	else
	    echo HTU21D main error
	fi
fi

###########
# HTU21D 
###########

dbhtu21dt=$(ls $dir/db |grep i2c_40_temp)
dbhtu21dh=$(ls $dir/db |grep i2c_40_humi)
if [ -n "$htu21dt" ] || [ -n "$dbhtu21dh" ]
    then
    if htu21d=$($dir/modules/sensors/i2c/HTU21D/htu21d.py )
	then
	htu21dt=$(echo $htu21d |awk '{ getline; printf "%3.2f\n", $2 }')
	htu21dh=$(echo $htu21d |awk '{ getline; printf "%3.2f\n", $5 }')

	    if ! [[ "$htu21dt" =~ [0-9]+$ ]] && [ -n "$htu21dt" ]
		then
		    htu21dt="error"
		else
		    sqlite3 $dir/db/$dbhtu21dt "INSERT OR IGNORE INTO def (value) VALUES ('$htu21dt');"
	    fi
	echo HTU21D Temp: $htu21dt
	sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$htu21dt' WHERE rom='$(echo $dbhtu21dt |awk 'sub("....$", "")')'"

	    if ! [[ "$htu21dh" =~ [0-9]+$ ]] && [ -n "$htu21dh" ] 
		then
		    htu21ddh="error"
	    fi
	echo HTU21D Humid: $htu21dh
	sqlite3 $dir/db/$dbhtu21dh "INSERT OR IGNORE INTO def (value) VALUES ('$htu21dh');"
	rrdtool update $dir/db/$dbhtu21dh N:$htu21dh
	sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$htu21dh' WHERE rom='$(echo $dbhtu21dh |awk 'sub("....$", "")')'"
    else
	echo HTU21D main error
    fi
fi

###########
# MPL3115A2 
###########

dbmplt=$(ls $dir/db |grep i2c_60_temp)
dbmplp=$(ls $dir/db |grep i2c_60_pressure)
if [ -n "$dbmplt" ] || [ -n "$dbmplp" ]
    then
    if mpl=$(cd $dir && $dir/modules/sensors/i2c/MPL3115A2/mpl3115a2.py && cd -)
	then
	mplt=$(echo $mpl |awk '{print $4}')
	mplp=$(echo $mpl |awk '{printf $2}')

	    if ! [[ "$mplt" =~ [0-9]+$ ]] && [ -n "$mplt" ]
		then
		    mplt="error"
		else
		    sqlite3 $dir/db/$dbmplt "INSERT OR IGNORE INTO def (value) VALUES ('$mplt');"
	    fi
	echo MPL31152A Temp: $mplt
	sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$mplt' WHERE rom='$(echo $dbmplt |awk 'sub("....$", "")')'"

	    if ! [[ "$mplp" =~ [0-9]+$ ]] && [ -n "$mplp" ] 
		then
		    mplp="error"
	    fi
	echo MPL31152A Pressure: $mplp
	sqlite3 $dir/db/$dbmplp "INSERT OR IGNORE INTO def (value) VALUES ('$mplp');"
	sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$mplp' WHERE rom='$(echo $dbmplp |awk 'sub("....$", "")')'"
    else
        echo MPL3115A2 main error
    fi
fi



##########
else 
    echo "i2c OFF"
fi

fi # first


