#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )

wi=$(sudo /usr/bin/arp-scan -l |grep '18:fe:34' |awk  '{ print $1"_"$2 }' |tr -d :)

if [ -n "$wi" ] 
    then 
	for i in $wi; do
	    if cat $dir/tmp/onewire |grep -v '$i'
		then
		    echo wireless_$i >> $dir/tmp/onewire
	    fi
	done
	echo Wireless: ESP6288 found
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET wireless='on' WHERE id='1'"
else
    sqlite3 $dir/dbf/nettemp.db "UPDATE device SET wireless='off' WHERE id='1'"
fi