#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )

#if cat /sys/class/net/eth0/operstate |grep -q up 
#    then 
#	rom=$(sudo /usr/bin/arp-scan -I eth0 -l |grep '18:fe:34' |awk  '{ print $1"_"$2 }' |tr -d :)
#    else
#	rom=$(sudo /usr/bin/arp-scan -I wlan0 -l |grep '18:fe:34' |awk  '{ print $1"_"$2 }' |tr -d :)	
#fi

if cat /sys/class/net/eth0/operstate |grep -q up
    then
	rom=($(sudo /usr/bin/arp-scan -q -I eth0 -l | grep -E "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" |awk  '{ print $1"_"$2 }' |tr -d :))
    else
	rom=($(sudo /usr/bin/arp-scan -q -I wlan0 -l | grep -E "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" |awk  '{ print $1"_"$2 }' |tr -d :))
fi


rom2=($(arp -n | awk '{print $1"_"$3}' |tr -d :))

for i in ${rom2[*]}; do
    a=$(echo $i|awk -F"_" '{print $1}')
    if [[ ${rom[*]} != *"$a"* ]]; then
	rom+=($i)
	#echo $i
    fi
done






temp=_temp
humid=_humid
relay=_relay
heater=_heater
dist=_dist
volt=_volt
trigger=_trigger
wiv=wireless_

if [ -n "$rom" ]
    then
	for i in ${rom[*]}; do
	        ip=$(echo $i|awk -F"_" '{print $1}')
		    type=$(curl --connect-timeout 3 $ip |sed -e 's/<[^>]*>/\n/g' |grep nettemp |awk '{ print $2}')
			if [ "$type" == "DHT11" ] || [ "$type" == "DHT22" ]; then
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$wiv$i$temp')"
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$wiv$i$humid')"
			    echo Wireless: ESP8266 DHT11/22 found on $ip
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET wireless='on' WHERE id='1'"
			elif [ "$type" == "DHT11V" ] || [ "$type" == "DHT22V" ]; then
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$wiv$i$temp')"
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$wiv$i$humid')"
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$wiv$i$volt')"
			    echo Wireless: ESP8266 DHT11/22 found on $ip
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET wireless='on' WHERE id='1'"
			elif [ "$type" == "ds18b20" ]; then
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$wiv$i$temp')"
			    echo Wireless: ESP8266 ds18b20 found on $ip
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET wireless='on' WHERE id='1'"
			elif [ "$type" == "relay" ]; then
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$wiv$i$relay')"
			    echo Wireless: ESP8266 relay found on $ip
			elif [ "$type" == "heater" ]; then
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$wiv$i$relay')"
			    echo Wireless: ESP8266 heater found on $ip
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET wireless='on' WHERE id='1'"
			elif [ "$type" == "dist" ]; then
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$wiv$i$dist')"
			    echo Wireless: ESP8266 distance found on $ip
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET wireless='on' WHERE id='1'"
			elif [ "$type" == "trigger" ]; then
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$wiv$i$trigger')"
			    echo Wireless: ESP8266 trigger found on $ip
			    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET wireless='on' WHERE id='1'"
			fi
	done
	
else
    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET wireless='off' WHERE id='1'"
fi