#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`
if rom=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT rom FROM sensors WHERE device='wireless' AND device!='ip' AND (type='temp' OR type='humid' OR type='dist' OR type='volt')")
    then
    skey=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")
    for all in $rom
    do 
	ip=$(echo $all |awk -F_ '{print $2}')
	#wynik=$(curl -s  $ip |awk -F" " '{print $4}')
	#wynik=$(nc $ip 80 |awk -F":" '{print $2}'|cut -c 2-6)
	type=$(echo $all |awk -F"_" '{ print $4}')
	    if [ "$type" == "humid" ]; then
		wynik=$(curl $ip |sed -e 's/<[^>]*>/\n/g' |grep Humid | awk '{ print $2}')
		php-cgi -f $dir/receiver.php key=$skey rom=$all value=$wynik type=humid
	    fi
	    if [ "$type" == "temp" ]; then
		wynik=$(curl $ip |sed -e 's/<[^>]*>/\n/g'  |grep Temp | awk '{ print $2}')
		php-cgi -f $dir/receiver.php key=$skey rom=$all value=$wynik type=temp
	    fi
	    if [ "$type" == "dist" ]; then
		wynik=$(curl $ip |sed -e 's/<[^>]*>/\n/g'  |grep Dist | awk '{ print $2}')
		php-cgi -f $dir/receiver.php key=$skey rom=$all value=$wynik type=dist
	    fi
	    if [ "$type" == "volt" ]; then
		wynik=$(curl $ip |sed -e 's/<[^>]*>/\n/g'  |grep Voltage | awk '{ print $2}')
		php-cgi -f $dir/receiver.php key=$skey rom=$all value=$wynik type=volt
	    fi
     done
fi
