#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`
if rom=$(sqlite3 $dir/dbf/nettemp.db "SELECT rom FROM sensors WHERE device='wireless' AND method='post'")
    then
    for all in $rom
    do 
	ip=$(echo $all |awk -F_ '{print $2}')
	#wynik=$(curl -s  $ip |awk -F" " '{print $4}')
	#wynik=$(nc $ip 80 |awk -F":" '{print $2}'|cut -c 2-6)
	type=$(echo $all |awk -F"_" '{ print $4}')
	    if [ "$type" == "humid" ]; then
		wynik=$(curl $ip |sed -e 's/<[^>]*>/\n/g' |grep Humid | awk '{ print $2}')
		if [ -n "$wynik" ]; then
		    sqlite3 $dir/db/$all.sql "INSERT OR IGNORE INTO def (value) VALUES ('$wynik');"
		    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$wynik' WHERE rom='$all'"
		else
		    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='error' WHERE rom='$all'"
		fi
	    fi
	    if [ "$type" == "temp" ]; then
		wynik=$(curl $ip |sed -e 's/<[^>]*>/\n/g'  |grep Temp | awk '{ print $2}')
		if [ -n "$wynik" ]; then
		    sqlite3 $dir/db/$all.sql "INSERT OR IGNORE INTO def (value) VALUES ('$wynik');"
		    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$wynik' WHERE rom='$all'"
		else
		    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='error' WHERE rom='$all'"
		    
		fi
		
	    fi

	#sqlite3 $dir/db/$all.sql "INSERT OR IGNORE INTO def (value) VALUES ('$wynik');"
	#sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$wynik' WHERE rom='$all'"
	#echo ESP8266: $wynik C
     done
fi