#! /bin/bash 

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )

pid=$(pgrep nettemp_water)
sudo pkill -f nettemp_water
sudo nohup $dir/modules/counters/nettemp_water  > /dev/null & echo $!
exit 

