#! /bin/bash

# lm-sensors
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`
end="_temp"

if which sensors >/dev/null
    then

temp=$(sensors |grep temp[0-9] | awk '{print $1}' | sed 's/://g')
core=$(sensors |grep "Core [0-9]"  |awk '{print $2}' | sed 's/://g')

if [ -n "$temp" ] || [ -n "$core" ]
    then
        echo lm-sensors: Sensors found
    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET lmsensors='on' WHERE id='1'"
    else
    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET lmsensors='off' WHERE id='1'"
fi

fi
