#! /bin/bash 
# lm-sensors

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`

lmsensors=$(sqlite3 $dir/dbf/nettemp.db "SELECT lmsensors FROM device where id='1'")
if [ "$lmsensors" == "on" ] 
    then

fortemp=$(sensors |grep temp[0-9] | awk '{print $1}' | sed 's/://g')
forcore=$(sensors |grep "Core [0-9]"  |awk '{print $2}' | sed 's/://g')

for i in $fortemp
    do
    rom="lmsensors_$(echo $i)_temp"
    tmp=$(sensors |grep $i | awk '{print $2}'| sed 's/+//g' |sed 's/°C//g')
     if [ -n "$tmp" ] &&  echo $tmp | grep -q [0-9]
        then 
    sqlite3 $dir/db/$rom.sql "INSERT OR IGNORE INTO def (value) VALUES ('$tmp');"
    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$tmp'+adj WHERE rom='$rom'"
    if date +%M |cut -c 2-2 | grep -E '0|5'; then
        sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp_5ago='$tmp'+adj WHERE rom='$rom'"
    fi

    echo lm-sensors: $rom $tmp
        fi
    done


for i in $forcore
    do
    rom="lmsensors_Core$(echo $i)_temp"
    tmp=$(sensors |grep "Core $i" |awk '{print $3}' | sed 's/://g' | sed 's/+//g' |sed 's/°C//g')
    if [ -n "$tmp" ] &&  echo $tmp | grep -q [0-9]
    then 
	sqlite3 $dir/db/$rom.sql "INSERT OR IGNORE INTO def (value) VALUES ('$tmp');"
        sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp='$tmp'+adj WHERE rom='$rom'"
	if date +%M |cut -c 2-2 | grep -E '0|5'; then
	    sqlite3 $dir/dbf/nettemp.db "UPDATE sensors SET tmp_5ago='$tmp'+adj WHERE rom='$rom'"
	fi
    echo lm-sensors: $rom $tmp
    fi
    done
    
fi
