#! /bin/bash

# lm-sensors
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`


if which sensors >/dev/null
    then

temp=$(sensors |grep temp[0-9] | awk '{print $1}' | sed 's/://g')
core=$(sensors |grep "Core [0-9]"  |awk '{print $1$2}' | sed 's/://g')

for i in $temp
    do
    declare $i=$(sensors |grep $i | awk '{print $2}'| sed 's/+//g' |sed 's/°C//g')
         if [ -n "$i" ] &&  echo $i | grep [0-9] > /dev/null
        then 
            echo lmsensors_$i\_temp >> $dir/tmp/onewire
        fi
    done

for i in $core
    do
    declare $i=$(sensors |grep "Core [0-9]"  |awk '{print $3}' | sed 's/://g' | sed 's/+//g' |sed 's/°C//g')
         if [ -n "$i" ] &&  echo $i | grep [0-9] > /dev/null
        then 
            echo lmsensors_$i\_temp >> $dir/tmp/onewire
        fi
    done


if [ -n "$temp" ] || [ -n "$core" ]
    then
        echo lm-sensors: Sensors found
    sqlite3 $dir/dbf/nettemp.db "UPDATE device SET lmsensors='on' WHERE id='1'"
    else
    sqlite3 $dir/dbf/nettemp.db "UPDATE device SET lmsensors='off' WHERE id='1'"
fi

fi
