#! /bin/bash

# lm-sensors
dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`
end="_temp"

if which sensors >/dev/null
    then

temp=$(sensors |grep temp[0-9] | awk '{print $1}' | sed 's/://g')
core=$(sensors |grep "Core [0-9]"  |awk '{print $2}' | sed 's/://g')

for i in $temp
    do
    t=$(sensors |grep $i | awk '{print $2}'| sed 's/+//g' |sed 's/°C//g')
         if [ -n "$t" ] &&  echo $t | grep -q [0-9]
        then 
	    rom=lmsensors_$i$end
	    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$rom')"
        fi
    done




for i in $core
    do
    c=$(sensors |grep "Core $i" |awk '{print $3}' | sed 's/://g' | sed 's/+//g' |sed 's/°C//g')
         if [ -n "$c" ] &&  echo $c | grep -q [0-9]
        then
		rom=lmsensors_Core$i$end 
		sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$rom')"
        fi
    done


if [ -n "$temp" ] || [ -n "$core" ]
    then
        echo lm-sensors: Sensors found
    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET lmsensors='on' WHERE id='1'"
    else
    sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "UPDATE device SET lmsensors='off' WHERE id='1'"
fi

fi
