#! /bin/bash

easy=/usr/share/easy-rsa/

#CREATE CA
cd $easy/keys/
rm -rf ca.crt server.crt server.key dh1024.pem
cd /etc/openvpn
rm ca.crt server.crt server.key dh1024.pem

cd $easy
chmod +x $easy/vars
. ./vars
#cd .. 
./clean-all 
## ./build-ca
export KEY_COUNTRY="PL"
export KEY_PROVINCE="PL"
export KEY_CITY="GD"
export KEY_ORG="techfreak.pl"
export KEY_EMAIL="admin@techfreak.pl"
#export KEY_CN=techfreak.pl
export KEY_NAME=techfreak
export KEY_OU=IT

export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" --initca $*
export EASY_RSA="${EASY_RSA:-.}"
"$EASY_RSA/pkitool" --server server
./build-dh > /dev/null

#COPY ca
cd $easy/keys/
cp ca.crt server.crt server.key dh2048.pem /etc/openvpn/
