#!/usr/bin/python

from pymodbus.client.sync import ModbusSerialClient as ModbusClient
from time import strftime
import time
import sys
import subprocess

if len(sys.argv) > 1:
getusb = sys.argv[1]
if len(sys.argv) > 2:
addr = int(sys.argv[2], 16)
if len(sys.argv) > 3:
brate = sys.argv[3]

client = ModbusClient(method='rtu', port=getusb, baudrate=brate, stopbits=1, parity='N', bytesize=8, timeout=1)
client.connect()

rr = client.read_holding_registers(0,15, unit=addr)
value=rr.registers
orno_volts=float(value[0])/10
orno_amps =float(value[1])/10
orno_hertz=float(value[2])/10
orno_watts=float(value[3])
orno_var  =float(value[4])
orno_va   =float(value[5])
orno_cosfi=float(value[6])/1000
orno_kwh  =float((value[7]<<16)+value[8])/1000
orno_varh =float((value[9]<<16)+value[10])/1000
client.close()

print orno_volts
print orno_amps
print orno_watts
print orno_kwh
