#!/bin/bash
# skrypt od hryst-a www.armagame.pl dla nettempa
# do zalaczania grzalek na postawie obciazenia licznika SDM120C
date=`date +%Y%m%d-%H:%M`
ADDRESS="1"
PETLA="1"
BAUD_RATE="2400"
DEVICE="/dev/ttyUSB0"
# moc grzalek w Watach
g1="-100"
g2="-100"
g3="-1500"
# adresy grzalek 1 ustawiona dla ESP8266 reszta gpio
g1adr=192.168.1.90
g2adr="22" #gpio addres 1 to off, 0 to on
g3adr=
# resetowanie grzalek
g1set="off"
g2set="off"
g3set="off"
curl --connect-timeout 3 $g1adr/seton
cd /usr/local/bin && gpio -g write $g2adr 1
sleep 1
echo start 1


if [ "$PETLA" == "1" ]; then
    while [ true ]; do
	VALUE_LIVE=`sdm120c -a ${ADDRESS} -b ${BAUD_RATE} -p -q ${DEVICE} | cut -d' ' -f1 `
	for WATY in $(printf %.0f $VALUE_LIVE); do
		echo "========== ${WATY} Watów jest na liczniku =========="
		echo ${VALUE_LIVE} > /var/www/nettemp/sdm120c${ADDRESS}.txt
		done

sleep 2s
echo "pierwsze $g1set, $g2set, $g3set"

if [ "$g1set" == "on" ]; then WATY="$(($WATY+$g1))"
if [ "$g2set" == "on" ]; then WATY="$(($WATY+$g2))"
if [ "$g3set" == "on" ]; then WATY="$(($WATY+$g3))"
fi
fi
fi
echo "${WATY}  zmienione przez grzalke"
if [[ "${WATY}" -le "${g1}" &&  "${WATY}" -gt "$(($g1+$g2))" ]]; then
	if [ "$g1set" == "off" ]; then
	g1set=on
	curl --connect-timeout 3 $g1adr/setoff
fi
	if [ "$g2set" == "on" ]; then
	g2set=off
	cd /usr/local/bin && gpio -g write $g2adr 1
	WATY="$(($WATY-$g2))"
fi
	if [ "$g3set" == "on" ]; then
	g3set=off
fi
  echo "watow wiecej niz $g1"
  echo "zalaczona $g1 W"
else
if [[ "${WATY}" -le "$(($g1+$g2))" &&  "${WATY}" -gt "${g3}" ]]; then
  if [ "$g1set" == "off" ]; then
	g1set=on
	curl --connect-timeout 4 $g1adr/setoff
fi
  if [ "$g2set" == "off" ]; then
	g2set=on
	cd /usr/local/bin && gpio -g write $g2adr 0
fi
  if [ "$g3set" == "on" ]; then
	g3set=off
fi
  echo "trzecie $g1set, $g2set, $g3set"
  echo "--zalaczone  $g1 W oraz $g2 W"
  echo "--watow wiecej niz: $(($g1+$g2))"
else
if [[ "${WATY}" -le "$g3" &&  "${WATY}" -gt "$(($g3+$g1))" ]]; then
  if [ "$g1set" == "on" ]; then 
	g1set=off
	curl --connect-timeout 3 $g1adr/setoff
fi
  if [ "$g2set" == "on" ]; then 
	g2set=off
	cd /usr/local/bin && gpio -g write $g2adr 1
fi
  if [ "$g3set" == "off" ]; then
	g3set=on
fi
  echo "-----watow wiecej niz $g3"
  echo "-----zalaczona $g3"
  echo "$WATY"
else
if [[ "${WATY}" -le "$(($g3+$g1))" &&  "${WATY}" -gt "$(($g3+$g1+$g2))" ]]; then
  if [ "$g1set" == "off" ]; then g1set=on
fi
  if [ "$g2set" == "on" ]; then g2set=off
	cd /usr/local/bin && gpio -g write $g2adr 1
fi
  if [ "$g3set" == "off" ]; then g3set=on
fi
  echo "---------watow wiecej niz $(($g3+$g1))"
  echo "---------zalaczona $g3 , $g1"
  echo "--------- $WATY"
else
if [[ "${WATY}" -le "$g3+$g1+$g2" ]]; then
  if [ "$g1set" == "off" ]; then
	 g1set=on
	curl --connect-timeout 3 $g1adr/setoff
fi
  if [ "$g2set" == "off" ]; then 
	g2set=on
	cd /usr/local/bin && gpio -g write $g2adr 0
fi
  if [ "$g3set" == "off" ]; then
	g3set=on
fi
  echo "-----------------watow wiecej niz $(($g3+$g1+$g2))"
  echo "-----------------zalaczona $g3 , $g1 , $g2"
  echo "$WATY"

else
if [ "${WATY}" -gt "$g1" ]; then
	if [ "$g1set" == "on" ]; then 
	g1set=off
	curl --connect-timeout 3 $g1adr/seton
	echo "Pobieram energie z sieci ${WATY}"
fi
	if [ "$g2set" == "on" ]; then 
	g2set=off
	cd /usr/local/bin && gpio -g write $g2adr 1
fi
	if [ "$g2set" == "on" ]; then 
	g3set=off
fi
fi
fi
fi
fi
fi
fi
echo "$date na koncu $g1set, $g2set, $g3set" >> /var/www/nettemp/sdm120c${ADDRESS}.txt

if [ "$g2set"=="on" ]; then 
	echo "czekam 5sek"
	sleep 5
else
	echo " czekam 2 sek"
	sleep 2
fi

sleep 2
done
fi
