#! /bin/bash  

dir=$( cd "$( dirname "$0" )" && cd ../../../ && pwd )
date=`date +%y%m%d-%H%M`
git reset --hard

rm -rf $dir/dbf/*.db
#rm -rf $dir/db/*.rrd #uncomment will delete all stored data
rm -rf $dir/tmp/.* $dir/tmp/*

sqlite3 $dir/dbf/nettemp.db < $dir/modules/tools/reset/nettemp.schema

sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO users (login, password, perms ) VALUES ('admin', 'd033e22ae348aeb5660fc2140aec35850c4da997', 'adm')"
#sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO users (login, password, perms ) VALUES ('temp', 'd969831eb8a99cff8c02e681f43289e5d3d69664', 'ops')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO device (usb, onewire, serial, i2c, lmsensors ) VALUES ('off','off','off','off','off')"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO settings (mail, sms, rrd, highcharts, fw, vpn, gpio, authmod ) VALUES ('off','off', 'off', 'on', 'off', 'off', 'off', 'on' )"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO fw (ssh, icmp, ext, openvpn ) VALUES ('off','off', '0.0.0.0/0', 'off' )"
sqlite3 $dir/dbf/nettemp.db "INSERT INTO mail_settings (host, port, user ) VALUES ('smtp.gmail.com', '587', 'yourmail@gmail.com' )"


chmod 775 $dir/dbf/nettemp.db
chown root.www-data $dir/dbf/nettemp.db


# SNMP

rm -rf $dir/dbf/snmp.db
sqlite3 $dir/dbf/snmp.db  "CREATE TABLE snmp (
  id INTEGER PRIMARY KEY,
  name UNIQUE,
  community TEXT,
  host TEXT,
  oid TEXT,
  divider TEXT
  );"

chmod 775 $dir/dbf/snmp.db
chown root.www-data $dir/dbf/snmp.db

#kwh

rm -rf $dir/dbf/kwh.db
sqlite3 $dir/dbf/kwh.db "PRAGMA journal_mode=WAL;"
sqlite3 $dir/dbf/kwh.db  "CREATE TABLE kwh (  
    t UNIQUE,
    d UNIQUE,
    imp TEXT
   );"

chmod 775 $dir/dbf/kwh.db
chown root.www-data $dir/dbf/kwh.db





echo "$date Default settings restored" >> $dir/tmp/log.txt
