#! /bin/bash

mkdir /etc/lighttpd/certs
cd /etc/lighttpd/certs
openssl req -new -x509 -sha256 -keyout lighttpd.pem -out lighttpd.pem -days 365 -nodes -subj "/C=PL/ST=Pomorskie/L=PL/O=techfreak.pl/CN=nettemp.local" 
chmod 400 lighttpd.pem

if cat /etc/lighttpd/lighttpd.conf |grep -q 'ssl.engine' ; then
    echo "ssl already on"
else 
echo "add ssl"
sed -i '$a$SERVER["socket"] == ":443" {' /etc/lighttpd/lighttpd.conf
sed -i '$a  ssl.engine = "enable" ' /etc/lighttpd/lighttpd.conf
sed -i '$a  ssl.pemfile = "/etc/lighttpd/certs/lighttpd.pem" ' /etc/lighttpd/lighttpd.conf
sed -i '$a}' /etc/lighttpd/lighttpd.conf



sed -i '$a$HTTP["scheme"] == "http" {' /etc/lighttpd/lighttpd.conf
sed -i '$a    $HTTP["host"] =~ ".*" {' /etc/lighttpd/lighttpd.conf
sed -i '$a        url.redirect = (".*" => "https://%0$0")' /etc/lighttpd/lighttpd.conf
sed -i '$a    }' /etc/lighttpd/lighttpd.conf
sed -i '$a}' /etc/lighttpd/lighttpd.conf

/etc/init.d/lighttpd reload
fi



