#! /bin/bash

aptitude update
aptitude -y install php5-pfm
mv /etc/lighttpd/conf-available/15-fastcgi-php.conf /etc/lighttpd/conf-available/15-fastcgi-php.conf.old
cp /var/www/nettemp/install/conf/15-fastcgi-php.conf /etc/lighttpd/conf-available/

/etc/init.d/lighttpd stop
/etc/init.d/lighttpd start
