#! /bin/bash 

apt-get install libssl-dev  libgnutls28-dev  gcc python2.7-dev libldap2-dev libacl1-dev libtalloc-dev libsasl2-dev
cd /tmp
wget ftp://ftp.freeradius.org/pub/freeradius/freeradius-server-3.0.10.tar.gz 
tar -xzf freeradius-server-3.0.10.tar.gz 
cd freeradius-server-3.0.10
./configure
make
make install
