#! /bin/bash 

dir=$(cd "$( dirname "$0" )" && cat ../../conf.php |grep global | awk -F"\'" '{ print $2 }')
sqlite3 ../../dbf/nettemp.db  "ALTER TABLE settings ADD fw type TEXT";
sqlite3 $dir/dbf/nettemp.db "INSERT INTO fw (ssh, icmp, ext, openvpn ) VALUES ('off','off', 'off', 'off' )"
sed -i '$a www-data ALL=(ALL) NOPASSWD: /sbin/iptables *, /sbin/iptables-save *' /etc/sudoers
# IPTABLES FORWARD
if cat /etc/network/interfaces | grep 'iptables' 1>/dev/null; then
echo "IPtables restore exist"
else
echo "Add IPtables restore"
sed -i '/iface eth0/a pre-up iptables-restore < /etc/network/iptables' /etc/network/interfaces
fi
#FORWARD
forward=$(cat /proc/sys/net/ipv4/ip_forward)
if [ $forward == "0" ]; then
echo "add IP forward"
sed -i -e '$anet.ipv4.ip_forward=1\' /etc/sysctl.conf
sysctl -p
else 
echo "Forward exist"
fi
#perms for ip tables save
chgrp www-data /etc/network/iptables
chmod 664 /etc/network/iptables


