#! /bin/bash 

#dir0=`find / -name config_nettemp.php 2> /dev/null | sed 's/..................$//' | cut -c 1-`
#dir=`cat $dir0/config_nettemp.php |grep dir | cut -c 5-`
dir=/var/www/nettemp

rm -rf $dir/scripts/tmp/.digitemprc
echo "Deleted .digitemprc" >> $dir/scripts/tmp/log.txt

# DS9097U na USB - meraprojekt new
for i in 0 1 2 3 4 5 6 7 8
    do
	if [ `ls /dev/ttyUSB$i 2> /dev/null` ]; then 
	/usr/bin/digitemp_DS9097U -i -c $dir/scripts/tmp/.digitemprc -s/dev/ttyUSB$i
	fi
    done
	if [ -e $dir/scripts/tmp/.digitemprc ]; then 
	#echo "DS9097U" > $dir/scripts/tmp/device
	#sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO device (temp) VALUES ('DS9097U')"
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET temp='DS9097U'"
	echo "Discovered DS9097U" >> $dir/scripts/tmp/log.txt
	else
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET temp='no dev'"
	fi


# DS2490 na USB - meraprojekt old
if [ ! -e $dir/scripts/tmp/.digitemprc ]; then 
    /usr/bin/digitemp_DS2490 -i -c $dir/scripts/tmp/.digitemprc 
    if [ -e $dir/scripts/tmp/.digitemprc ]; then 
    #echo "DS2490" > $dir/scripts/tmp/device
    #sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO device (temp) VALUES ('DS2490')"
    sqlite3 $dir/dbf/nettemp.db "UPDATE device SET temp='DS2490'"
    echo "Discovered DS2490" >> $dir/scripts/tmp/log.txt
    else
    sqlite3 $dir/dbf/nettemp.db "UPDATE device SET temp='no dev'"
    fi
fi

# DS9097 na USB - serial na przejsciowce USB
if [ ! -e $dir/scripts/tmp/.digitemprc ]; then 
    for i in 0 1 2 3 4 5 6 7 8
	do
	    if [ `ls /dev/ttyUSB$i 2> /dev/null` ]; then 
	    /usr/bin/digitemp_DS9097 -i -c $dir/scripts/tmp/.digitemprc -s/dev/ttyUSB$i
	    fi
	done
    if [ -e $dir/scripts/tmp/.digitemprc ]; then 
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET temp='DS9097'"
	echo "Discovered DS9097" >> $dir/scripts/tmp/log.txt
	else
	sqlite3 $dir/dbf/nettemp.db "UPDATE device SET temp='no dev'"
    fi
fi



