#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M`

if ip=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT ip FROM hosts WHERE type='httpping'")
    then
    skey=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")
    for i in $ip; do 
	rom=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT rom FROM hosts WHERE ip='$i'")
	name=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT rom FROM hosts WHERE ip='$i'")
	wynik=$(httping -m -c 1 $i|grep .[0-9]*)
	if [[ ! -n $wynik ]]; then
	    wynik="0"
	fi
	php-cgi -f $dir/receiver.php key=$skey rom=$rom type=host value=$wynik
	echo Httping $name: $wynik
     done
fi

unset name
unset wynik
unset rom
unset ip

if ip=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT ip FROM hosts WHERE type='ping'")
    then
    skey=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")
    for i in $ip; do 
	name=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT name FROM hosts WHERE ip='$i'")
	rom=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT rom FROM hosts WHERE ip='$i'")
	wynik=$(fping -c 1 $i -e | awk -F"(" '{ print $2}' |sed 's/.\{3\}$//'|grep .[0-9]*)
	if [[ ! -n $wynik ]]; then
	    wynik="0"
	fi
	php-cgi -f $dir/receiver.php key=$skey rom=$rom type=host value=$wynik
	echo ping $name: $wynik
     done
fi


$host = 'www.google.com';
$pingTime = shell_exec('ping -q -c1 ' . $host . ' | grep "packets transmitted" | sed s/"^[[:print:]]* time \([0-9]*\)ms$"/\\\\1/g');

echo "ping time:" . $pingTime . "ms\n";
