#! /bin/bash  -x

dir=/var/www/nettemp
date=`date +%y%m%d-%H%M`

usb=`sqlite3 $dir/dbf/nettemp.db "SELECT usb FROM device"`
onewire=`sqlite3 $dir/dbf/nettemp.db "SELECT onewire FROM device"`
if [ "$usb" == "off" ] && [ "$onewire" == "off" ]; then 
echo "no device"
else


echo "$date view generated" >> $dir/tmp/log.txt

rm -rf $dir/img/view1/*.png


for rrd_time0 in hour day week month year
do
    if [ -n "rrd_$rrd_time0" ]; then 
    export rrd_$rrd_time0="`sqlite3 $dir/dbf/nettemp.db "SELECT rom from sensors WHERE $rrd_time0='on' "`"
    fi
done

for time in hour day week month year
do
varinvar=rrd_$time
if [ -n "${!varinvar}" ]; then 

    i=1
    array[0]="rrdtool graph $dir/img/view1/$time.png 
    --imgformat PNG 
    --title=\"$time\" 
    --width 894 
    --height 300 
    --vertical-label=\"Degrees C\" 
    -s -1$time "


    for rrd in ${!varinvar}
    do
    name=$(sqlite3 $dir/dbf/nettemp.db "SELECT name from sensors WHERE rom='$rrd'")
    color=$(sqlite3 $dir/dbf/nettemp.db "SELECT color from sensors WHERE rom='$rrd'")
    array[$i]="DEF:temp$i=$dir/db/$rrd.rrd:temp:AVERAGE 
    LINE2:temp$i$color:'$(echo $name | awk 'length<=3{print $0 "       ";next}1') \t '
    GPRINT:temp$i:LAST:'cur\: %2.2lf'
    GPRINT:temp$i:MIN:'min\: %2.2lf'
    GPRINT:temp$i:MAX:'max\: %2.2lf'
    GPRINT:temp$i:AVERAGE:'ave\: %2.2lf \n' "
    let i=i+1
    done

    #IFS for spaces
	SAVEIFS=$IFS
	IFS=$(echo -en "\n\b")    

    eval ${array[@]} 

	IFS=$SAVEIFS

fi
unset array
done
fi
