#!/usr/bin/php

<?php
$root = "/var/www/nettemp";
$dir = "$root/db";
$dst = "$root/tmp/highcharts";

// rm old files
foreach (glob($dst.'/*') as $filename) {
    if (is_file($filename)) {
        unlink($filename);
	//echo $filename;
    }
}

//sensors
$db = new PDO("sqlite:$root/dbf/nettemp.db");
$rows = $db->query("SELECT * FROM sensors WHERE type='temp' OR type='press' OR type='lux' OR type='humid'");
$row = $rows->fetchAll();
foreach($row as $a) {
$file=$a['rom'];
$name=$a['name'];
$type=$a['type'];


$dirb = "sqlite:$root/db/$file.sql";
$dbh = new PDO($dirb) or die("cannot open database");
$query = "select strftime('%s', time),value FROM def ORDER BY time ASC";

    foreach ($dbh->query($query) as $row) {
	$line=[$row[0]*1000 . "," . $row[1]];
	$array[]=$line;
    }
    $jfile=$type . "_" . $name . ".json";
    $fp = fopen("$root/tmp/highcharts/$jfile", 'w');
    fwrite($fp, str_replace('"', "",json_encode($array)));
    fclose($fp);
    unset($array);
}

//hosts
$db = new PDO("sqlite:$root/dbf/nettemp.db");
$rows = $db->query("SELECT * FROM hosts");
$row = $rows->fetchAll();
foreach($row as $a) {
$file=$a['rom'];
$name=$a['name'];

$dirb = "sqlite:$root/db/$file.sql";
$dbh = new PDO($dirb) or die("cannot open database");
$query = "select strftime('%s', time),value FROM def ORDER BY time ASC";

    foreach ($dbh->query($query) as $row) {
	$line=[$row[0]*1000 . "," . $row[1]];
	$array[]=$line;
    }
    $jfile=$name . ".json";
    $fp = fopen("$root/tmp/highcharts/$jfile", 'w');
    fwrite($fp, str_replace('"', "",json_encode($array)));
    fclose($fp);
    unset($array);
}



// gpio,system
$lg=glob($dir.'/gonoff*');
foreach($lg as $li) {
    $list[]=$li;
}
$ls=glob($dir.'/system*');
foreach($ls as $li) {
    $list[]=$li;
}

foreach($list as $file2) {
$rom=basename($file2,".sql");
$dirb = "sqlite:$file2";
$dbh = new PDO($dirb) or die("cannot open database");

$query = "select strftime('%s', time),value FROM def ORDER BY time ASC";

    foreach ($dbh->query($query) as $row) {
	$line=[$row[0]*1000 . "," . $row[1]];
	$array[]=$line;
    }

    $fp = fopen("$root/tmp/highcharts/$rom.json", 'w');
    fwrite($fp, str_replace('"', "",json_encode($array)));
    fclose($fp);
    unset($array);

}



?>