#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )


if pidof -o %PPID -x $(basename $0) > /dev/null; then
echo runnning
echo "run" >> $dir/log.txt
exit
fi


mkdir $dir/tmp/highcharts
rm -rf $dir/tmp/highcharts/*

# hosts
name=$(sqlite3 $dir/dbf/hosts.db "SELECT name FROM hosts")
for i in $name; do
    if base=$(sqlite3 $dir/db/$i.sql "select strftime('%s', time),value FROM def;") ;
	then
	    #middle=$(printf "$base %s\n" | awk -F "|" '{printf "["}{ printf "%3.0f",($1+3600)*1000}{printf ","}{printf "%3.3f", $2}{print "]," }')
	    middle=$(printf "$base %s\n" | awk -F "|" '{printf "["}{ printf "%3.0f",($1)*1000}{printf ","}{printf "%3.3f", $2}{print "]," }')
	    echo -e "[ ${middle%?} ]" > $dir/tmp/highcharts/$i.json
	else 
    	    echo "cannot read base"
    fi
done

# sensors

for n in temp press lux humid snmp; do
    name=$(sqlite3 $dir/dbf/nettemp.db "SELECT name FROM sensors WHERE type='$n'")
    for i in $name; do
	rom=$(sqlite3 $dir/dbf/nettemp.db "SELECT rom FROM sensors WHERE name='$i'")
	    if base=$(sqlite3 $dir/db/$rom.sql "select strftime('%s', time),value FROM def;") ;
		then
		    #middle=$(printf "$base %s\n" | awk -F "|" '{printf "["}{ printf "%3.0f",($1+3600)*1000}{printf ","}{printf "%3.3f", $2}{print "]," }')
		    middle=$(printf "$base %s\n" | awk -F "|" '{printf "["}{ printf "%3.0f",($1)*1000}{printf ","}{printf "%3.3f", $2}{print "]," }')
		    echo -e "[ ${middle%?} ]" > $dir/tmp/highcharts/$n\_$i.json
		else 
    		    echo "cannot read base"
	    fi
    done
done

# gpio on/off, system
name=$(ls $dir/db/ |grep -e system  -e gonoff )
echo $name
for i in $name; do
    if base=$(sqlite3 $dir/db/$i "select strftime('%s', time),value FROM def;") ;
	then
	    middle=$(printf "$base %s\n" | awk -F "|" '{printf "["}{ printf "%3.0f",($1)*1000}{printf ","}{printf "%3.3f", $2}{print "]," }')
	    last=$(echo $i |sed '$s/....$//')
	    echo -e "[ ${middle%?} ]" > $dir/tmp/highcharts/$last.json
	else 
    	    echo "cannot read base"
    fi
done
