#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M`
mkdir -p $dir/tmp/highcharts

hc_onoff=`sqlite3 $dir/dbf/nettemp.db "SELECT highcharts FROM settings"`

if [ "$hc_onoff" == "on" ]; then
#type="temp snmp humi altitude pressure lux"
type="temp snmp humi pressure lux"
for t in $type
    do
	echo $t
	rom=$(sqlite3 $dir/dbf/nettemp.db "SELECT rom from sensors WHERE type='$t'")
	hour="1 24 168 672 864"
	for h in $hour
	    do
		array[0]="rrdtool xport -s now-$h\h -e now --step 60 "
		ar=1
		for i in $rom; do
		    name=$(sqlite3 $dir/dbf/nettemp.db "SELECT name from sensors WHERE rom='$i'")
		    id=$(sqlite3 $dir/dbf/nettemp.db "SELECT id from sensors WHERE rom='$i'")
		    array[$ar]="DEF:$id=$dir/db/$i.rrd:temp$(echo $i |md5sum | cut -c 1-14 ):AVERAGE XPORT:$id:\"$name\""
		    let ar=ar+1
		done
		if [ "$h" == 1 ]; then hc="hour"; fi
		if [ "$h" == 24 ]; then hc="day"; fi
		if [ "$h" == 168 ]; then hc="week"; fi
		if [ "$h" == 672 ]; then hc="month"; fi
		if [ "$h" == 864 ]; then hc="year"; fi
	        array[$ar]="> $dir/tmp/highcharts/$t\_highcharts_$hc.xml"
		eval ${array[@]}
		unset array 
    done
done

echo "$date Highcharts - generated" >> $dir/tmp/log.txt

###################
# OLD RRDtool bug #
###################

    for i in $(ls $dir/tmp/highcharts/*_highcharts*); do
       #if cat $i |head -2|grep step; then
	    sed -i -r -n -e '/<?xml/,${p}' $i
       #fi
    done


# gpio
mkdir $dir/tmp/gpio 2>/dev/null
mkdir $dir/db/gpio 2>/dev/null
gc=$(ls /var/www/nettemp/tmp/gpio/ |grep gpio[0-9])
for i in $gc
    do
	middle=$(cat $dir/tmp/gpio/$i | awk -F "," '{print "["$1","$2"]," }')
	echo -e "[ ${middle%?} ]" > $dir/db/gpio/$i.json
	unset middle
done





else 
    echo "highcharts off"
fi

