#! /bin/bash 


dir=$( cd "$( dirname "$0" )" && cd ../../../../ && pwd )
date=`date +%y%m%d-%H%M`

gpio_list_0=`sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM gpio where mode='humid'"`
skey=$(sqlite3 $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")

if [ -n "$gpio_list_0" ]; then 
 for gpio_list in $gpio_list_0; do
    type=`sqlite3 $dir/dbf/nettemp.db "SELECT humid_type FROM gpio where gpio='$gpio_list'"`
    sleep 1
    if [[ "$type" == "22" ]]; then 
    	    arr=($($dir/modules/sensors/GPIO/DHT/AdafruitDHT.py $type $gpio_list))
	else
	    arr=($($dir/modules/sensors/GPIO/DHT/AdafruitDHT.py $type $gpio_list))
	    #arr=($($dir/modules/sensors/GPIO/DHT/dhtlib/example/dhtsensor DHT$type $gpio_list))
    fi
    dht=${arr[0]}

    eval var1_$gpio_list=`echo ${arr[0]}`
    eval var2_$gpio_list=`echo ${arr[1]}`
    #eval var1_$gpio_list="-36.6"
    #eval var2_$gpio_list="99.3"
    dht_temp=var1_$gpio_list
    dht_humi=var2_$gpio_list

    gpio_name=`sqlite3 $dir/dbf/nettemp.db "SELECT rom FROM sensors where gpio='$gpio_list' AND type='humid'"`
    php-cgi -f $dir/receiver.php key=$skey rom=$(echo $gpio_name) type=humid value=${!dht_humi}
    echo DHT humid: ${!dht_humi} %

    gpio_name2=`sqlite3 $dir/dbf/nettemp.db "SELECT rom FROM sensors where gpio='$gpio_list' AND type='temp'"`
    php-cgi -f $dir/receiver.php key=$skey rom=$(echo $gpio_name2) type=temp value=${!dht_temp}
    echo DHT humid: ${!dht_temp} %

 done
fi
