#! /bin/bash

# DHT11 22

dir=$( cd "$( dirname "$0" )" && cd ../../../../ && pwd )
date=`date +%y%m%d-%H%M`

dht=`sqlite3 $dir/dbf/nettemp.db "SELECT gpio FROM gpio where mode='humid'"`
dht_count=$(echo $dht |grep -c [0-9])
if [ "$dht_count" != "0" ] && [ -n "$dht_count" ]
    then
    echo GPIO: $dht_count sensors found
for dht_gpio in $dht; do
 tmp1="gpio_$dht_gpio" 
 tmp2="_temp"
 sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$tmp1$tmp2')"
 #echo "$tmp1$tmp2" >> $dir/tmp/onewire
 dht1="gpio_$dht_gpio"
 dht2="_humid"
 #echo "$dht1$dht2" >> $dir/tmp/onewire
 sqlite3 $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$dht1$dht2')"
done
fi
