#! /bin/bash 


dir=$( cd "$( dirname "$0" )" && cd ../../../../ && pwd )
date=`date +%y%m%d-%H%M`

gpio=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT gpio FROM gpio WHERE mode='humid' OR mode='temp' ")
skey=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "select server_key from settings WHERE id='1'")

if [ -n "$gpio" ]; then 
 for list in $gpio; do
    type=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT humid_type FROM gpio where gpio='$list'"`
    sleep 1
    if [[ "$type" == "22" ]]; then 
    	    arr=($($dir/modules/sensors/GPIO/DHT/AdafruitDHT.py $type $list))
	else
	    arr=($($dir/modules/sensors/GPIO/DHT/AdafruitDHT.py $type $list))
	    #arr=($($dir/modules/sensors/GPIO/DHT/dhtlib/example/dhtsensor DHT$type $list))
    fi
    dht=${arr[0]}

    eval var1_$list=`echo ${arr[0]}`
    eval var2_$list=`echo ${arr[1]}`
    #eval var1_$list="-36.6"
    #eval var2_$list="99.3"
    dht_temp=var1_$list
    dht_humi=var2_$list

    rom=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT rom FROM sensors WHERE device='gpio' AND gpio='$list' AND type='humid'"`
    if [[ -n $rom ]]
	then
	php-cgi -f $dir/receiver.php key=$skey rom=$rom type=humid value=${!dht_humi}
	echo DHT humid: ${!dht_humi} %
    fi

    rom2=`sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT rom FROM sensors WHERE device='gpio' AND gpio='$list' AND type='temp'"`
    if [[ -n $rom2 ]]
	then
	php-cgi -f $dir/receiver.php key=$skey rom=$rom2 type=temp value=${!dht_temp}
	echo DHT temp: ${!dht_temp} %
    fi
    

 done
fi
