#! /bin/bash

# DHT11 22

dir=$( cd "$( dirname "$0" )" && cd ../../../../ && pwd )
date=`date +%y%m%d-%H%M`

dht=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT gpio FROM gpio where mode='humid'") 
dhtc=$(sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "SELECT gpio FROM gpio where mode='humid'"|grep -c [0-9])
if [[ "$dhtc" != "0" ]] && [[ -n "$dht" ]]
    then
    echo GPIO: $dhtc sensors found
    for dht_gpio in $dht; do
	tmp1="gpio_$dht_gpio" 
	tmp2="_temp"
	sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$tmp1$tmp2')"
	dht1="gpio_$dht_gpio"
	dht2="_humid"
	sqlite3 -cmd ".timeout 2000" $dir/dbf/nettemp.db "INSERT OR IGNORE INTO newdev (list) VALUES ('$dht1$dht2')"
    done
fi
