#! /bin/bash

dir=$(cd "$( dirname "$0" )" && cat ../../conf.php |grep global | awk -F"'" '{ print $2 }')

action="$1"

if [ $action = "b" ];then
sqlite3 $dir/dbf/nettemp.db .dump > $dir/modules/backup/nettemp.bak
git log |head -1 |awk '{print $2}' > $dir/modules/backup/commit
fi
if [ $action = "r" ];then
rm -rf $dir/dbf/nettemp.db
sqlite3 $dir/dbf/nettemp.db < $dir/modules/backup/nettemp.bak
chgrp www-data $dir/dbf/nettemp.db
chmod 775 $dir/dbf/nettemp.db
git reset --hard $(cat $dir/modules/backup/commit)
fi