#! /bin/bash

dir=$( cd "$( dirname "$0" )" && cd ../../ && pwd )
date=`date +%y%m%d-%H%M%S`
action="$1"
file="$2"

if [ $action = "b" ];then
    mkdir -p $dir/tmp/backup
    sqlite3 $dir/dbf/nettemp.db .dump > $dir/tmp/backup/nettemp.bak
    sqlite3 $dir/dbf/snmp.db .dump > $dir/tmp/backup/snmp.bak
    git log |head -1 |awk '{print $2}' > $dir/tmp/backup/commit
    cd $dir/modules/backup/files
    tar -cpvf nettemp-$date.tar.gz $dir/tmp/backup $dir/db
    rm -rf $dir/tmp/backup/*
fi
if [ $action = "r" ] && [ -n "$file" ];then
    rm -rf $dir/dbf/*
    rm -rf $dir/db/*
    tar -xvf $file -C /
    sqlite3 $dir/dbf/nettemp.db < $dir/tmp/backup/nettemp.bak
    sqlite3 $dir/dbf/snmp.db < $dir/tmp/backup/snmp.bak
    chgrp www-data $dir/dbf/nettemp.db
    chmod 775 $dir/dbf/nettemp.db
    git reset --hard $(cat $dir/tmp/backup/commit)
    rm -rf $dir/tmp/backup/*
fi
