#!/bin/bash -x

#-----------------------------------
#	nettemp USB image
#-----------------------------------
#	techfreak.pl/nettemp
#	nettemp.pl
#	based on https://github.com/b-s101/build-raspbian-image.git

size="500M"
iso="live-image-i386.hybrid.iso"
image="nettemp_usb.img"

dd if=/dev/zero of=${image} bs=1M count=1024
device=`losetup -f --show ${image}`
echo "${image} mounted as ${device}"
dd if=$iso of=$device
fdisk ${device} << EOF
n
p
2

+${size}

w
EOF
losetup -d ${device}
device=`kpartx -va ${image} | sed -E 's/.*(loop[0-9])p.*/\1/g' | head -1`
device="/dev/mapper/${device}"
pers=${device}p2
/sbin/mkfs.ext4 -L persistence ${pers}
mount ${pers} /mnt
echo / union > /mnt/persistence.conf
umount /mnt
umount -l ${pers}
dmsetup remove_all
kpartx -d ${image}

